### ISSUE TITLE
4.2.2 Cryptographic Specifications is mixing together 2 keys (formatting/markup issue?)

### ISSUE THREAD

**Issue by andyatyeo** [usnistgov/FIPS201#205]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Intercede

**Organization Type (see below for codes)**: 2
 
**Reference (Include section/paragraph or pdf line number)**: section 4.2.2 top of page 58 on the November 2020 pdf draft, lines 1800 to 1804
 
**Comment (Include rationale for comment)**: 
The text below the bold section "PIV Card application administration key" seems to be mixing up concepts that relate to the "PIV card application administration key" and the "Secure Messaging key" - certainly it is at odds with sections 4.2.2.6 and 4.2.2.7
 
**Suggested Change**: 
I think this may be a formatting/markup issue, where page 58 intends to list "PIV Card application administration key" and "Secure Messaging key" as 2 separate bold-headed sections to indicate 2 separate keys, but an issue with the markup makes it seem to merge into a single section that looks like it is mixing the 2 different keys together.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
I've checked and confirmed this is a formatting error in the source text, good catch!

**Comment by jricher** [comment]
Suggest accept.
