### ISSUE TITLE
Comment for NOT Deprecating SYM-CAK and SYM-CAK Authentication

### ISSUE THREAD

**Issue by markjdale** [usnistgov/FIPS201#207]
**Organization Name (N/A, if individual)**:  XTec, Incorporated

**Organization Type (see below for codes)**:  2 = Industry
 
**Reference (Include section/paragraph or pdf line number)**: 
•	Section 4.2.2.3, Line 1866
•	Section 6.2.4, Line 2316
 
**Comment (Include rationale for comment)**: 
 
Please see attached document

**Suggested Change**: 

Please see attached document
 
---
[XTec, Incorporated - Comment for NOT Deprecating SYM-CAK - 01282021.docx](https://github.com/usnistgov/FIPS201/files/5888957/XTec.Incorporated.-.Comment.for.NOT.Deprecating.SYM-CAK.-.01282021.docx)

 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Needs discussion. One of the primary arguments is derived from post-quantum security: do we need to keep SYM-CAK for a PQ world? There's also mention of the better speed of symmetric and inter-agency usage of combinations of PKI-CAK and SYM-CAK if both are kept and one is preferred.

**Comment by regenscheid** [comment]
Decline- Agencies have not identified compelling use cases to retain SYM-CAK.  The difficulties of symmetric key management, and the related interagency interoperability challenges, make use of SYM-CAK challenging to meet the goals of PIV.
