### ISSUE TITLE
Reference for “American Association of Motor Vehicle Administrators”

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#208]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Office of Information & Technology (OI&T), Office of Information Security (OIS)

**Organization Type (see below for codes)**: 1 = Federal
 
**Reference (Include section/paragraph or pdf line number)**: line 1379 (page 35)
 
**Comment (Include rationale for comment)**: Reference to “American Association of Motor Vehicle Association’s”
 
**Suggested Change**: This should likely be “American Association of Motor Vehicle Administrators”
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept
