### ISSUE TITLE
Proposed Physical Access Control System (PACS) credential cancelation list 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#209]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Generic Smart Cards LLC

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 5.5.3
 
**Comment (Include rationale for comment)**: Unlike logical access, PACS solutions generally leverage a credential identifier from which access privileges and other services are then linked.  Having a lightweight revocation solution for PACS that conveys issuer trust status, searchable by credential identifier, would provide many benefits 
 
**Suggested Change**: See Document "FIPS201-3 Contribution Clause 5.5.3 UUID Canceled List v2.pdf" sent with this spreadsheet

[FIPS201-3 Contribution Clause 5.5.3 UUID Canceled List v2.pdf](https://github.com/usnistgov/FIPS201/files/5894511/FIPS201-3.Contribution.Clause.5.5.3.UUID.Canceled.List.v2.pdf)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend not accepting. Proposal is for a new revocation mechanism for PACS use that each card issuer would be required to maintain. Not clear what the advantage of this is (other than being lightweight, perhaps) over CRLs and such.

**Comment by regenscheid** [comment]
Decline- We don't see a sufficient advantage to warrant a new requirement on issuers to provide an additional revocation mechanism/status service.
