### ISSUE TITLE
Minimum requirement for PIV Credential eligibility determination is a completed and favorably adjudicated FBI NCHC and a submitted Tier 1 investigation

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#210]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NASA

**Organization Type (see below for codes)**: 1 - Federal 
 
**Reference (Include section/paragraph or pdf line number)**: Sec 2.2 Line 557
 
**Comment (Include rationale for comment)**: The minimum requirement for issuance of a PIV is submission of the investigation and completion of the FBI NCHC, as explained in the following paragraph.  These paragraphs need to be modified to address the minimum and address continued eligibility for the PIV credential.
 
**Suggested Change**: "The minimum requirement for PIV Credential eligibility determination is a completed and favorably adjudicated FBI NCHC and a submitted Tier 1 investigation.  Continued PIV eligibility is determined by the completed and favorably adjudicated Tier 1 investigation."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
maybe improve wording.  Line 560 should stress the case of "when no adjudication exists".

**Comment by regenscheid** [comment]
Accept in principle, reworking per #363
