### ISSUE TITLE
Clearly define the use of biometric comparison

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#211]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NASA

**Organization Type (see below for codes)**: 1 = Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec 2.4 Line 600, Sec 2.5 Line 836 
 
**Comment (Include rationale for comment)**: "Biometric" is used throughout the document for the purpose of comparison but only fingerprint biometric comparisons are ever detailed as an option (line 600).  If the intention is to only allow fingerprint biometric comparison, that needs to be expressely stated.  If the intention is to allow fingerprint, iris, or facial image biometric comparison (line 636) that needs to be explained.
 
**Suggested Change**: Clearly define the use of biometric comparison to either be limited to fingerprint biometric comparison or to allow comparison of all other biometrics (iris, facial image).  Recommend allowing comparison of all biometric types captured during enrollments when a biometric comparison is needed.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
In Section 2.3, we intended to require comparing against the fingerprints taken for the background investigation.  However, in other areas, biometric comparison was intended to include other biometrics. We were explicit about this in line 836.  We could clarify line 636 to include that same language from line 836 that described using other optional biometrics.
