### ISSUE TITLE
Will the Department of State be establishing a group to support identity proofing inquiries?

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#212]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NASA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec 2.7 Line 772
 
**Comment (Include rationale for comment)**: No guidance has been forthcoming from the Department of State and such guidance has not been easily available in the past.  Is it the intention of this document for the Department of State to issue guidance, similar to OPM issuing the final credentialing standard, for such issuance?  Will the Department of State be establishing a group to support such identity proofing inquiries?  Is this specifically for PIV-I credentials or is there an as yet unreleased method for issuing foreign nationals a PIV without an investigation and residency as required in the OPM Final Credentialing Standard?
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Noted- Out of scope for FIPS 201
