### ISSUE TITLE
Supervised remote identity proofing requirements 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#213]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NASA

**Organization Type (see below for codes)**: 1- Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec 2.7.1 Line 795
 
**Comment (Include rationale for comment)**: "Requiring the station to be maintained in a controlled-access environment and monitored by staff limits options such as enrollment kits that can be mailed to the applicant or even remotely placed kiosks.  Supervised remote should not rely on staff at a location but instead the process to securely access the enrollment service and the pre-registration and sponsorship of the individual to be enrolled.  Requiring staff to monitor the equipment does not work for remote areas where population and need for enrollment is greatly reduced.

The option to allow a shippable enrollment kit (cameras, readers, etc.) would be useful and the only change to the existing requirements would be the first bullet under supervised remote identity proofing.  The recommended change would allow for the current proposed implementation of staffing (maintained in a secure manner) and would also allow options for a kit to be securely shipped to an applicant or even a kiosk to be placed at a specific location.  The process for using an enrollment kit could be the following: kit is shipped and tracked by issuer; kit is recevied; enrollment is scheduled; operator and applicant connect via video conferencing; operator provides code to unlock kit; applicant sets up kit in view of operator; applicant performs enrollment with oprator guidance; enrollment is completed; kit is placed back in package and sealed using tamper-resistant tap; video conference is ended; kit will then be shipped and tracked back to issuer."
 
**Suggested Change**: Change the first bullet under supervised remote identity proofing requirements to: "The station SHALL be maintained in a secure manner and SHALL be monitored by an operator while it is being used."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
This issue is represented in [580](https://github.com/usnistgov/FIPS201/issues/580) - suggest to close
