### ISSUE TITLE
How enrollment records can be shared between organizations

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#214]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NASA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec 2.8.2 Line 876
 
**Comment (Include rationale for comment)**: Is NIST proposing a solution for how enrollment records can be shared between organizations so these operations can be accomplished?  Currently there is no single location where enrollment records reside or can be bridged (e.g., FPKI bridge, CVS for investigations).  Can this be a mandatory item and can this be somehow managed by a central Agency (e.g., DCSA)?
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline as it is out of scope.  The current approach  to exchange enrollment record is documented in SP 800-156 (Import/Export of Chain of Trust). NIST has no authority to mandate central storage of enrollment record or require exchange (rather than go through re-enrollment).

**Comment by regenscheid** [comment]
Decline per above.
