### ISSUE TITLE
Use of the CHUID should still be allowed within the authentication perimeter (layered access control)

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#215]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NASA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec 6.2.5 Line 2341
 
**Comment (Include rationale for comment)**: Use of the CHUID should still be allowed within the authentication perimeter (layered access control).  For instance, once I have authenticated to a controlled/limited/exclusion space with PKI I should be able to use CHUID to access areas of equal or lesser security requirements within the perimeter.

**Suggested Change**: Deprecate section 6.2.5, Authentication Using the CHUID but do not remove it.  Speficy that use of the CHUID for authentication should only be used after an initial authentication using one of the other approved methods.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend not accepting. The CHUID authentication mechanism was already deprecated in FIPS 201-2 and it's not clear why this use case couldn't use a more secure mechanism within the perimeter.

**Comment by regenscheid** [comment]
Decline- The CHUID authentication mechanism was deprecated in FIPS 201-2 for security reasons, and will be removed from -3 for that reason. We will, however, provide additional considerations and guidance in SP 800-116.
