### ISSUE TITLE
Comments on FIPS 201-3 by Elaine Barker

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#216]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NIST, Elaine Barker

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: See word.doc attachment 
 
**Comment (Include rationale for comment)**: See word.doc attachment
 
**Suggested Change**: See word.doc attachment

[Comments on FIPS 201.docx](https://github.com/usnistgov/FIPS201/files/5894717/Comments.on.FIPS.201.docx)

 ---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion on how to implement Elaine Barker's requested edits. See word.doc.

**Comment by regenscheid** [comment]
Accept- mostly editorial comments.

**Comment by jricher** [comment]
Partial accept, some items incorporated.
