### ISSUE TITLE
Biometric Data

### ISSUE THREAD

**Issue by cheriecarlson** [usnistgov/FIPS201#217]
### All Fields Are Required
**Organization Name (N/A, if individual)**:  NASA

**Organization Type (see below for codes)**: 1
 
**Reference (Include section/paragraph or pdf line number)**: 2.3
 
**Comment (Include rationale for comment)**:  2.3 is vague.  Needs further explanation of biometric data and it's use prior to this and the following sections using biometrics.
 
**Suggested Change**: 
 Further define Biometric Data and is use

--- 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
suggesting noting. The "use" of the biometric data is the topic of section 2.5.  Further in-depth details are in SP 800-73  and SP 800-76.

**Comment by regenscheid** [comment]
Decline.  The current section is clear- currently, biometric data collected for background investigations is limited to a full set of fingerprints.
