### ISSUE TITLE
Lorrin Massengill Comments on FIPS 201-3 Draft

### ISSUE THREAD

**Issue by lmasseng** [usnistgov/FIPS201#218]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Department of Veteran's Affairs (VA)

**Organization Type (see below for codes)**: 1
 
**Reference (Include section/paragraph or pdf line number)**: 

1. Line 989, Section 2.9.3 PIV Card Activation Reset
2. Line 1040, Section General Computing Platform
3. Line 1075, Section 2.9.4 PIV Card Termination Requirements
4. After line 1530, Table 4-1. Name Examples
5. After line 1530, Table 4-1. Name Examples

 
**Comment (Include rationale for comment)**: 
 
**Suggested Change**: 

1. Would not refer to this as Card Activation. It is a PIV card PIN and/or data reset.
2. "The operator authenticates the owner of the PIV Card through an independent procedure." Vague wording, would recommend adding examples for clarity.
3. "Per OPM guidance, the Central Verification System (or successor) SHALL be updated to reflect the change in status." Just wanted to comment that this may be difficult for some agencies to implement. CVS can be managed by a different office responsible for adjudications/suitability. If a case management system is not in place, they may not get a notification indicating the user has been terminated or separated from the agency. In which case, the notification and CVS change will have to be a manual data entry.
4. Example column is empty.
5. Page 40, Bottom left, seems to have a formatting issue with a long Contractor name in green.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
1. Suggest accept, the section seems to be specifically about PIN reset.
2. Suggest accept in principle to reword.
3. Suggest noted.
4. and 5. Suggest accept. Something seems to have gone wrong post-rendering with the PDF. This section renders fine from source, so I suspect this might have to do with the accessibility post-processing step.

**Comment by lmasseng** [comment]
Thanks for the update Justin! 😊

**Comment by hferraio** [comment]
1)  Suggest to decline. Section 2.9.3 is also about card activation using OCC - although it is covered last in the section 2.9.3.  For that reason, card activation is the correct term as the card can be activated by PIN or OCC.

**Comment by jricher** [comment]
1. Accept in principle. Two methods are listed, will add an introductory sentence to clarify.
2. Accept in principle. Will reword or provide examples.
3. Noted.
4. & 5. Accept, will fix rendering error.

**Comment by jricher** [comment]
4&5: Confirmed that the table rendering issues are from the post-production process on the PDF, will review section 508 process to make sure this doesn't break again.

**Comment by jricher** [comment]
@hferraio  to follow up for guidance on examples/wording/requirements on (2)

**Comment by jglosx3** [comment]
Accept in Principle -
Sub-bullet 1. Updated wording on PIN reset
Sub-bullet 2. Updated wording 
Sub-bullet 3. Noted
Sub-bullet 4. & 5. Examples for names have been updated and formatting corrected
