### ISSUE TITLE
Provide Guidance for Using FIDO Derived Credentials

### ISSUE THREAD

**Issue by adricasti** [usnistgov/FIPS201#219]
**Organization Name**: HID Global

**Organization Type**: 2-Industry
 
**Reference**: Section 2.6.3 Authentication Using PIV Asymmetric Cryptography
 
**Comment (Include rationale for comment)**: With WebAuthn and FIDO specifications reaching maturity and being available in all major platforms, the opportunity to leverage a widely available mechanism for authentication emerges and we believe there is value on recommending its usage.
 
**Suggested Change**: Add a section with guidance for using FIDO, for example like this: 

**6.2.3.x Authentication with a Derived FIDO Credential (FIDO-PK)**

A FIDO credential could be created following the guidelines provided in Section 2.10 where a valid PIV card is used establish cardholder identity. The derived FIDO credential is then scoped and stored only by the relying party that would use it for subsequent re-authentication. 

The following steps SHALL be performed for FIDO-PK: 
- The relying system issues a `navigator.credentials.get` [WebAuthn](https://www.w3.org/TR/webauthn-2/) request to obtain an identity assertion. It is also possible that the relying party issues directly a lower level `authenticatorGetAssertion` to the authenticator, for example in an embedded system that does not have a WebAuthn API layer. This request includes the relying party id and MAY include a user id.  If there is no user id in the request, this means that a FIDO Resident Key is expected to provide both identity and authentication.
- The relying system verifies that the returned assertion is valid. This includes verifying that the user identity verification information satisfies the relying system request.
- The relying system validates that the PIV certificate the FIDO-PK credential is bound to is valid using certificate path validation as specified in [RFC 5280] 

Some of the characteristics of the FIDO-PK based authentication are as follows: 
- Same benefits as the PKI-AUTH mechanism 
- The relying system can control the types of authenticators it accepts during derived credential binding. 
- The relying system can verify or request specific user verification mechanisms that can include PIN or biometric verification. 
- Derived FIDO credentials can reside in roaming or embedded authenticators that work with desktop and mobile platforms.

**Comment by jimfenton** [comment]
Recommend not accepting. Derived credentials are covered in SP 800-157, and even there the proposed text might be too authenticator-specific.

**Comment by regenscheid** [comment]
Decline- Out of scope for FIPS 201-3, but may be addressed in SP 800-157 revision.
