### ISSUE TITLE
Include Graduated Authentication Assurance Levels for Derived Credentials

### ISSUE THREAD

**Issue by adricasti** [usnistgov/FIPS201#220]
**Organization Name**: HID Global

**Organization Type**: 2-Industry
 
**Reference**: Section: 6.3. PIV Support of Graduated Authentication Assurance Levels 
 
**Comment (Include rationale for comment)**: At the beginning of section 6 it is stated that graduated authenticator assurance levels are also applicable to derived PIV credentials, but Section 6.3 only mentions the PIV Credential.  It would be useful to include examples of acceptable derived credentials.
 
**Suggested Change**: Add a Table after current Table 6-1. Acceptable Examples of Derived Credentials for Physical Access; and include for the different PAL an example of a valid derived credential, for example a FIDO Level 2 authenticator with resident keys capabilities. 

Add a Table after current Table 6-2. Acceptable Examples of Derived Credentials for Logical Access; and include the different authentication assurance levels with examples like accessing a native mobile application or a Web Page in a mobile device as well as a regular desktop through a Web browser.

**Comment by jimfenton** [comment]
Recommend not accepting. This belongs in SP 800-157, not here.
