### ISSUE TITLE
Clarify if only unencrypted HTTP is supported for CRL Distribution

### ISSUE THREAD

**Issue by adricasti** [usnistgov/FIPS201#221]
**Organization Name**: HID Global

**Organization Type**: 2-Industry
 
**Reference**: Section: 5.5.1 Certificate and CRL Distribution, first paragraph
 
**Comment (Include rationale for comment)**: The Standard requires the use of HTTP.  Some may infer that HTTPS is also supported or even preferred. Using HTTPS adds complexity to shared hosting of supporting services so it would be good to clarify if it's indeed included.
 
**Suggested Change**: Add a phrase to the first paragraph stating if HTTPS is also supported or even encouraged or if it’s a deliberate choice to limit the protocol to HTTP.

**Comment by adricasti** [comment]
This is the same observation as #243

**Comment by currydm** [comment]
Propose team discussion on use of HTTPS.

**Comment by regenscheid** [comment]
Reject- this issued is already covered in RFC 5280.
