### ISSUE TITLE
Add OpenID Connect to the suggested federation standards

### ISSUE THREAD

**Issue by adricasti** [usnistgov/FIPS201#222]
**Organization Name**: HID Global

**Organization Type**: 2-Industry
 
**Reference**: Section 7.2 Second Paragraph
 
**Comment (Include rationale for comment)**: OpenID Connect is a well known federation standard that is worth including in the suggested references.
 
**Suggested Change**: Extend the last phrase in the second paragraph to read: For example, the information can be presented using technologies defined in [RFC 8485] or [SAML-AC] or [OpenID Connect].

Add the corresponding references to [OpenID Connect Federation](https://openid.net/specs/openid-connect-federation-1_0.html) and [OpenID Connect for Identity Assurance](https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html)

**Comment by jricher** [comment]
Suggest partial accept, the OpenID Connect for Identity Assurance is applicable here, but plain OpenID Connect is not.

**Comment by jricher** [comment]
Accept in principle to add OIDC4IA.
