### ISSUE TITLE
DoD clarification on "National Security System"

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#225]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 6. Applicability Line 79 
 
**Comment (Include rationale for comment)**: This section leaves open to interpretation whether a physical location can be classifed as a "National Security System".  DoD recommends providing clarification.
 
**Suggested Change**: DoD recommends updating as follows: "This Standard is applicable to identification issued by federal departments and agencies to federal employees and contractors for gaining physical access to federally controlled facilities; and for gaining logical access to federally controlled information systems, except for “national security systems” as defined by 44 U.S.C. 3542(b)(2) and [SP 800-59]."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion to clarify term National Security Systems.

**Comment by regenscheid** [comment]
Decline- Per FISMA, Federal Information Processing Standards are applicable to non-national security systems.  The proposed change would have misrepresented the scope and applicability.
