### ISSUE TITLE
DoD update language for PIV Credential Eligibility determination

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#226]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.2 Credential Requirement Line 557
 
**Comment (Include rationale for comment)**: Lines 557-559, should reference the Office of Personnel Management (OPM) Credentialing Standards Procedures memorandum, titled “Credentialing Standards Procedures for Issuing Personal Identity Verification Cards under HSPD-12 and New Requirement for Suspension or Revocation of Eligibility for Personal Identity Verification Credentials,” dated December 15, 2020.  This OPM memorandum includes information that could be considered to the contrary of how Section 2.2 is drafted.  For example, in the case of non-citizen U.S. Federal employees hired and working in foreign locations, such as local nationals working at an overseas DoD Installation, a Tier 1 investigation is improbable.  
 
**Suggested Change**: "DoD recommends updating language to: “The minimum requirement for PIV Credential eligibility determination for U.S. nationals worldwide and for non-U.S. nationals at locations within the United States is a completed and favorably adjudicated Tier 1 investigation, formerly called a National Agency Check with Written Inquiries (NACI).  The minimum requirement for non-U.S. nationals at locations outside the United States are established in OPM Credentialing Standards for Issuing Personal Identity Verification…"".

DoD also recommends adding reference to document (footnote or otherwise)."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Sugest to Accept-in-part: Per OPM, there is no contradiction as the credentialing process standard are not any different from what was previously stated in the “the 2008 FCS” , rather it goes into greater detail on the most recent guidance.   Note line 549  states D/As shall use the credentialing eligibility standards issued by OPM & OMB. And under footnote 3 we list the FCS and subsequent standards.  

If we want to be more clear on the topic we could add to footnote 5.  See CSP for foreign national vetting considerations.

**Comment by regenscheid** [comment]
Decline: OPM guidance indicates that a favorably adjudicated Tier 1 investigation is the minimum requirement without exception.  In particular, the requirements for non-US citizens has not changed.

There are several relevant guidance documents from OPM and OMB, so it is not possible to provide a single reference.

**Comment by jglosx3** [comment]
Discuss previous decision to decline. This may be a partially accept.

**Comment by regenscheid** [comment]
Partial Accept- The final version of FIPS 201-3 includes a reference to the new credentialing standards procedures memo released in 2020.  Other recommended changes were not incorporated.  As previously noted, the current OPM guidance indicates that a favorably adjudicated Tier 1 investigation is the minimum requirement without exception. In particular, the requirements for non-US citizens has not changed.
