### ISSUE TITLE
DoD language clarification for PIV enrollment record

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#227]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal 
 
**Reference (Include section/paragraph or pdf line number)**: 2.2 Credential Requirement Line 564
 
**Comment (Include rationale for comment)**: This section states "once the investigation is completed… report the final eligibility determination to the Central Verification System (or successor).  This determination SHALL be record in the PIV enrollment record to reflect PIV eligibility for the PIV cardholder and, if applicable, their enrollment in the Continuous Vetting Program." DoD recommends clarification to better align this section with other language in the document about the PIV enrollment record and clarify that how it is constructed (or stored) is within the Federal PIV issuers purview.  
 
**Suggested Change**: DoD recommends the sentence to updated to the following: "...This determination SHALL be recorded in (or available for) the PIV enrollment record..."

 ---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
relates to DHS's #345

**Comment by regenscheid** [comment]
Rephrase starting from:

Once the investigation is completed, the authorized adjudicative entity SHALL adjudicate
the investigation and report the final eligibility determination to the Central Verification
System (or successor) and, if applicable, their enrollment in the Continuous Vetting Program.  This determination SHALL be recorded (or available to) in the PIV enrollment record to reflect PIV eligibility for the PIV cardholder.

**Comment by hferraio** [comment]
Also see #228 with suggested text.
