### ISSUE TITLE
DoD clarify language for implementation of PIV enrollment record to Federal PIV issues 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#229]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.6 PIV Enrollment Record Line 642
 
**Comment (Include rationale for comment)**: It is DoD's understanding that NIST's intent for the PIV enrollment record is to identify items that could be included but leave most of implementation to Federal PIV issuers.  DoD recommends adding specific language to this section to provide clarification and to emphasize this intention. 
 
**Suggested Change**: DoD recommends the following be added to this section, "As long as data can be retrieved when needed by the PIV issuer, then there is no requirement for data that may reside in other authoritative system to be duplicated in the PIV issuance system."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
We might want to add a note to state that the enrollment record is a logical representation of the record that might be stored in different systems.

**Comment by regenscheid** [comment]
Decline.  While we agree with the point that the commenter is making, we believe the current text allows this.  In addition, #228 will add text clarifying that the PIV enrollment record may be stored in different places.
