### ISSUE TITLE
DoD SHALL requirements for PIV enrollment records

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#230]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD 

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.6 PIV Enrollment Record Line 642
 
**Comment (Include rationale for comment)**: It is DoD's understanding that NIST's intent for the PIV enrollment record is to identify items that could be included but leave most of implementation to Federal PIV issuers.  The SHALL requirements for the PIV enrollment record are spread across the document.  DoD recommends providing all SHALL requirements for the PIV enrollment records in this section.  This will ensure PIV issuers can clearly identify the requirements that must be implemented (SHALL) vs. the ones that SHOULD or COULD be implemented.  
 
**Suggested Change**: "DoD recommends that this section include all SHALL requirements for the PIV enrollment records.  Our review identified the following items:

*  Line 566
* Line 938

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
discuss - I think the section is pretty throughout - containing all / most items that are applicable to an enrollment record.
