### ISSUE TITLE
DoD clearly defining cryptographic security features

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#231]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: PIV ID Proofing Line 718
 
**Comment (Include rationale for comment)**: This section states "When they are available, cryptographic security features SHOULD be used to validate evidence."  DoD recommends providing clarification on meaning or intent, as it is currently unclear what "cryptographic security feature" is intended to cover.

 
**Suggested Change**: "DoD recommends clearly defining cryptographic security features by adding ""A cryptographic security feature could include, but is not limited to PKI mutual authentication, MRZ signature validation of passports,…"" or other relevant examples.
"

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Will clarify the intent- namely that evidence that is digitally signed should be cryptographically verified (e.g., e-passports).
