### ISSUE TITLE
DoD remove requirement for a REAL ID Act compliant ID cards in the ID proofing process

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#232]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: PIV Identity Proofing and Registration Requirements Line 731
 
**Comment (Include rationale for comment)**: This section creates a new requirement for driver licenses used for identity proofing be REAL ID Act compliant.  There are serveal mitigating factors for PIV card issuance, including that PIV card applicants must present a secondary ID proofing document, complete a FBI records check, and complete background investigation.  Many U.S. states continue to issue both REAL ID Act compliant and non-compliant ID cards.  Given scope/applicability of REAL ID Act and existing mitigating factors, DoD recommends against this requirement.
 
**Suggested Change**: DoD recommends NIST remove the requirement for a REAL ID Act compliant ID cards in the ID proofing process.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
dublicate to DHS [#376](https://github.com/usnistgov/FIPS201/issues/376)

**Comment by hferraio** [comment]
suggest to close issue as it is represented in issue [376](https://github.com/usnistgov/FIPS201/issues/376)

**Comment by jglosx3** [comment]
Duplicate of Issue #376:
