### ISSUE TITLE
DoD recommends a 4th item be added to revocation process

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#233]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Section 2.9.1 Line 922 Section 2.9.4 Line 1071
 
**Comment (Include rationale for comment)**: This revision appears to allow certificate to not be revoked if the PIV is collected and destroyed by the card issuer.  While destruction of the PIV cards ensures loss of private keys, it does not address potential user behavior issues with email clients (e.g., potential for an unrevoked public key from a collected/destroyed PIV to be available for use in encryption transactions) and confusion (potential for user to recover an unrevoked encryption certificate for a destroyed PIV and continue to use it) when it comes to encryption keys.
 
**Suggested Change**: DoD recommends a 4th item be added to the revocation process to ensure there are no user behavior issues: "Even if the PIV card was collected and destroyed, the certificate corresponding to the key management key SHALL be revoked, if the key management key is present."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion on adding 4th item to revocation process.

**Comment by regenscheid** [comment]
Will reconsider a recommendation to revoke KMK certificates after reviewing application behavior.

**Comment by jricher** [comment]
Accept in principle to add a similar requirement.

**Comment by regenscheid** [comment]
After reviewing the existing language in the working draft, I do not believe any change is needed.  It is not necessary or desirable to revoke the KMK in all reissuance scenarios.  If the KMK certificate is still valid, it can restored from escrow and placed on the new card.  It is arguably desirable to revoke the KMK certificate when an employee is terminated, or if the KMK is rekeyed, but that is scenario-specific and nothing in FIPS 201 would preclude that.
