### ISSUE TITLE
DoD update language to provide consistency with this section and lines 1085-1086

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#234]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.9.4 PIV Card Termination Requirements Line 922
 
**Comment (Include rationale for comment)**: Update this section to provide consistency between this section and lines 1085-1086.  
 
**Suggested Change**: DoD recommends adding the following to this section, "In addition, the PIV Card termination procedures SHALL ensure all derived PIV credentials bound to the PIV account are invalidated as specified in Section 2.10.2."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Reference is a bit conflicted; line 922 is in section 2.9.1 on PIV card reissuance. Lines 1085 -1086 are in section 2.9.4.

Recommend not accepting; if the reference is to section 2.9.4 the existing text is already in that section, and if it's in 2.9.1, derived PIV termination should not be required on PIV reissuance.

**Comment by jimfenton** [comment]
Not accepting for reasons described above.
