### ISSUE TITLE
DoD recommendation to add Remote post-issuance updates language

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#235]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.9.2 PIV Card Post-Issuance Update Requirements Line 974
 
**Comment (Include rationale for comment)**: This section requires remote update of PIVs be conducted over mutually authenticated communication between the issuance infrastructure, user's web browser, and user's PIV.  DoD has seen significant dropped transactions and errors in our remote update capability implementing a similar requirement.  DoD is migrating to a solution that will allow more transactions to be conducted successfully and still provide a secure mechanism.  DoD recommends adding language to cover DoD's emerging post-issuance implementation, which DoD believes provides sufficient mechanism to perform those transactions securely while decreasing failures.

**Suggested Change**: DoD recommends adding the following to this section: "Remote post-issuance updates are sufficiently secure when performed over a server-side only TLS session used in conjunction with the Global Platform Secure (GP) channel where the keys used to establish the GP channel are known only to the issuer and are housed in a FIPS 140 Level 3 device."  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Recommend Decline. DOD is recommended specific vendor  implementation.  The current language allows the solution recommend by DoD but does not mandate it.

**Comment by regenscheid** [comment]
Decline- The existing text does not require TLS, or any other particular protocol.  What is describe by the commenter would satisfy the existing requirements in Section 2.9.2.
