### ISSUE TITLE
DoD recommendation to add clarity about PIN resets 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#236]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD 

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.9.3 PIV Card Activation Reset Line 1036
 
**Comment (Include rationale for comment)**: This section establishes a requirement for PIVs that support OCC biometric comparison needing to do more to reset a PIN than successfully compare the biometrics.  It is unclear what other requirements (i.e., connected to issuer operator and issuance operator authenticates the owner of PIV) must be met in this scenario and what specific risk is attempting to be mitigated.  
 
**Suggested Change**: "DoD recommends NIST add clarity to this section about PIN resets by identifying two specific PIN reset function:
1) ""PIN reset to an unlocked/blocked PIN in which the user knows the PIN or leverages the OCC biometric comparison.  This should not require connection to issuance infrastructure.""
2) ""PIN reset to a locked/block PIN which fits into the current language in this section."" "
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
case #1 is addressed in line 994-995  - just a few lines up.   Maybe start a new paragraph with  line 994 to bring attention to it?

**Comment by regenscheid** [comment]
We will consider revising this section to further describe how PIN resets can be accomplished using OCC.
