### ISSUE TITLE
DoD issuer of PIV card and of derived credential definition too narrow

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#237]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.10.1 Line 1111
 
**Comment (Include rationale for comment)**: This Section requires the issuer of the PIV card and of a derived credential be one and the same entity; this definition is too narrow to account for Agencies where the issuers of derived credentials are not the organization that manages the PIV issuance.  (REF: The "[d]erived PIV credentials SHALL be bound to the cardholder's PIV account only by the organization that manages that PIV account", and the binding is described as follows, "[i]issuance of a derived PIV credential is an instance of the post-enrollment binding".)
 
**Suggested Change**: "DoD recommends changing 1111-1113 as follows, ""Derived PIV credentials SHALL be bound to the cardholder’s PIV account only by the organization
that manages that PIV account life-cycle management bound to the cardholder’s PIV account or eligibility."""
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Needs further discussion. I don't understand the distinction between the proposed wording and the current wording (modulo awkward proposed wording) but perhaps I don't understand the organizational construct the proposed wording allows.

**Comment by hferraio** [comment]
see also issue [330](https://github.com/usnistgov/FIPS201/issues/330) and issue [410](https://github.com/usnistgov/FIPS201/issues/410)

**Comment by jimfenton** [comment]
Issue is clarity between the home agency of the cardholder and possible other agencies (e.g., US Access) that might be performing some functions as their agent. The intent is that the home agency has these responsibilities, but the text needs to make that clearer.
