### ISSUE TITLE
DoD recommendation for Zone 2F

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#238]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 4.1.4.1 Mandatory Items on the Front of the PIV Card
 
**Comment (Include rationale for comment)**: DoD requests that NIST add additional language to provide acceptable alternative approaches for Zone 2F: Name.  
 
**Suggested Change**: DoD recommends adding the following to this section: "Line 1 contains Last Name only, using 10pt Arial Bold.  If is is too long, the font size is lowered until it does fit.  Line 2 contains First Name, Middle Name, Suffix.  If it is too long, the Middle Name is reduced to Middle Initial. If it is still too long, font size is lowered until it does fit.  7pt is the lowest the font size used."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Decline.  What is described by the commenter is already allowed by the existing language.
