### ISSUE TITLE
DoD recommends adding as a mandatory element to the PIV authentication certificate a UPN in the Subject Alternate Name field

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#239]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.1 PIV Authentication Key Line 1836 4.2.4 PIV Unique Identifiers Line 1969
 
**Comment (Include rationale for comment)**: It has become more and more difficult to support authentication interoperability between different federal agency PIV cards as many applications use User Principal Names (UPNs) as a mechanism to provision and manage accounts. Some Federal agencies implement UPNs that are constructed as e-mail addresses while other use random agency specific identifiers.  This does not guarantee uniqueness nor decrease the possibility of duplicates. Additionally, there is no federal-wide requirement for all federal agencies to maintain a identity service provider (IdP) and until such is implemented federal-wide, these interoperability challenges need to be addressed through other mechanisms .  Positive adjudication of this comment will significant enhance interoperability (for example, this will aid DoD-VA interoperability and onboarding new federal entities to the Federal Electronic Health Record system).

 
**Suggested Change**: "DoD recommends adding as a mandatory element to the PIV authentication certificate a UPN in the Subject Alternate Name field that conforms with an existing FIPS 201/SP 800-73 attributes (i.e., the last 16 digits of the Federal Agency Smart Card Number (FASCN), i.e., cardholder specific identifier).  The construction of the UPN should be the last 16 digits of the FASCN@federal agency abbreviation (e.g., last 16 digits of FACSN@mil or last 16 digits of FASCN@va).  
"

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, federation through an IdP is more robust than such a constructed on-card identifier.

**Comment by hferraio** [comment]
See also [301](https://github.com/usnistgov/FIPS201/issues/301),  [484](https://github.com/usnistgov/FIPS201/issues/484), [300](https://github.com/usnistgov/FIPS201/issues/300)

**Comment by jglosx3** [comment]
Folks,

Lets review resolution on Issue #239.  It is decline but we don't give rational. The note indicated it is related to #300, #301 and #484.  We give a resolution to #484 but is is specific to use of a UUID..

**Comment by jglosx3** [comment]
We do not recommend a unique person identifier as a mandatory element in the Subject Alternate Name field. The use of federation may address concerns identifying users across departments and agencies.
