### ISSUE TITLE
DoD remove or make optional requirement for User to not select various PIN combinations

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#240]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 4.3.1 Activation by Cardholder Line 2008
 
**Comment (Include rationale for comment)**: "This new requirement seems to expect the PIV card (and/or PIV issuance system) to ensure the user does not select various PIN combinations.  Meeting this mandate would require the development of a new on-card capability and FIPS 140 re-certification.  

Additionally, the current safeguards appear to be enough to mitigate this perceived risk for a credential used for UNCLASSIFIED/CUI material.  The knowledge about the PIN should be that of the PIV cardholder and the actual card.  There are a combination of factors (e.g., the length of the PIN, there is a three failed PIN counter, and physical hardware token) that go into meeting the FIPS 140 1:1M probability of an adversary selecting an accurate PIN.  As such, it is difficult to understand how this requirement (implement on the card or within the issuance system) would significantly change this equation and those layered security techniques.  "
 
**Suggested Change**: DoD recommends the requirement be removed or made optional.  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Duplicate to #589
