### ISSUE TITLE
Address the distinction between Federal department and agency PKIs that are cross-certified with the Federal PKI and those that are operated under the Common Policy itself

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#241]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 5.2.1 Line 2080
 
**Comment (Include rationale for comment)**: While DoD agrees with the removal of the term "legacy PKI" from FIPS-201, as currently written, FIPS-201 does not accurately address the distinction between Federal department and agency PKIs that are cross-certified with the Federal PKI and those that are operated under the Common Policy itself. Cross certification happens after the two PKIs are deemed comparable, but asserting a policy OID means that the certificate fully meets the requirements. DoD recommends incorporating language to support interoperability while maintaining the sovereignty of department and agency PKIs.
 
**Suggested Change**: DoD recommends replacing the first sentence with the following: "The required contents of X.509 certificates associated with PIV private keys are based on [PROF]. The relationship is described below for certificates issued under [COMMON], and is described in Section 5.4 for certificates issued by department and agency PKIs that operate under department and agency specific Certificate Policies."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion. See also #242

**Comment by jricher** [comment]
See text in 5.4 Line 2111 (from #242)

**Comment by regenscheid** [comment]
Review the proposed text for Sections 5.2.1 and 5.4 with FPKI.

**Comment by hferraio** [comment]
Per discussion with FPKI, this should be address in other ways than putting into the more restrictive standard. Options, for example are a PA policy memo, or possibly updating the certificate profiles to resolve the issue, and at the same time provide greater flexibility going forward.

Suggest to decline and close.

**Comment by jglosx3** [comment]
Hildy recommends change in resolution decision to partially accept

**Comment by jglosx3** [comment]
“Accepted cross-certified PKI with certificate mapping but this allowance is deprecated in this version of the Standard and subsequently removed in next version of Standard.

**Comment by jglosx3** [comment]
Partially Accept -  It is acceptable to cross-certify PKI with certificate mapping but this allowance is deprecated in this version of the Standard and subsequently removed in next version of Standard. 
Per discussion with FPKI, this should be address in other ways than putting into the more restrictive standard. Options, for example are a PA policy memo, or possibly updating the certificate profiles to resolve the issue, and at the same time provide greater flexibility going forward.
