### ISSUE TITLE
DoD recommends NIST codify the ICAMSC BAE 2.0 initiative 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#245]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: General Line 2461
 
**Comment (Include rationale for comment)**: Interoperability continues to be a major challenge for Federal Agencies.  DoD has a mission need to support interoperability with other Federal mission partners by exchanging attributes about individuals to assist in the account request/authorization, account provisioning, and account management processes within DoD IT assets.  Currently, there are no specific federal solutions to support that activity.  DoD plans to begin a production deployment of pilot Backend Attribute Exchange (BAE) implementation that mirrors the Federal ICAMSC BAE 2.0 documentation, but there are no other federal PIV issuers subscribers.
 
**Suggested Change**: 
DoD recommends NIST codify the ICAMSC BAE 2.0 initiative for federal PIV issuers   to share attributes.  Each Federal PIV   issuerer should be required to expose an Agency BAE broker so that other   federal PIV issuers can exchange identity attributes and PIV records, where   needed.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, this is out of scope of this publication.
