### ISSUE TITLE
DoD recommends adding a definition of Authenticator

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#246]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DoD

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Appendix C Line 2656
 
**Comment (Include rationale for comment)**: There is no definition of Authenticator in Appendix and the concept is referenced in various places throughout the document (e.g., Sections 2.10.1 (Line 1108) and 3.1.2 (Line 1261)).
 
**Suggested Change**: DoD recommends adding a definition of Authenticator to differentiate for the reader the difference between an authenticator and credential.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend accepting this comment. The definition can probably be adapted from that in SP 800-63 Appendix A.

**Comment by jimfenton** [comment]
Probably import the definition used in 800-63B.
