### ISSUE TITLE
Derived PIV requirements and Section 2.9

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#247]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.9
 
**Comment (Include rationale for comment)**: This section is mostly silent on derived PIV credentials (2.9.4, lines 1085 and 1086 is the exception).  If all derived PIV requirements are in 2.10, then there should be requirements that cover all of the Section 2.9 subsections.
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend partially accept. While some of the 2.9 subsections don't apply to non-PKI DPC (which do not contain attributes), they do apply to PKI-based DPC so there should be termination, name change, etc. procedures for them as well.

**Comment by regenscheid** [comment]
This is closely related to #248. Section 2.9.4 already addresses how Derived PIVs must be terminated when the PIV card is terminated.  Per #294, we will clarify that Derived PIVs do not need to be reissued when PIV cards. 

We may need to address Derived PIV for Post Issuance updates and name changes.
