### ISSUE TITLE
Requirements for derived PIV credentials when the PIV is re-issued

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#248]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.9.1 and 2.10
 
**Comment (Include rationale for comment)**: Neither of these sections address the requirements for derived PIV credentials when the PIV is re-issued. The minimum would be to say that the original issuance method shall be followed.
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See also #234 

Recommend to narrowly accept; non-pki DPC (at least) will not require reissuance when the PIV is reissued, but we should probably say that.
