### ISSUE TITLE
If the card has not been compromised, is collected and is destroyed, why is it necessary to revoke it?

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#249]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.9.1 Line 922
 
**Comment (Include rationale for comment)**: :  If the card has not been compromised, is collected and is destroyed, why is it necessary to revoke it (whatever it means to 'revoke' a card)?  In addition, if the private keys have not been compromised, why is it necessary to revoke the keys on that card?  [note:  in the case of loss, stolen or compromised cards, I agree revocation is the only course]
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Related to #233

**Comment by hferraio** [comment]
Procedure to revoke PIV Card is specified in line 924-934.  To preface, each card has unique **Card**  identifiers. that identifies the card.    By revoking the PIV card we mean to end association with the card  by removing its card  identifiers (i.e., FASC-N and Card UUID) from any databases (i.e., PACS/LACS application, IDAM).  Any keys associated with that card needs to be destroyed  ( by collecting and destroying the card itself  or by revoking the certificate if collection of card is not possible. 

Cardholder, in case of re-issuance will then get a new card with a new set of card identifiers (FASC-N and Card UUID). 

If this is not clear - maybe we should clarify.

**Comment by jricher** [comment]
duplicate of #466

**Comment by regenscheid** [comment]
This is effectively a duplicate of #466
