### ISSUE TITLE
Change 'card reader' to 'card reader/writer' in Figure 3-1

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#250]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Section 3.1.1, lines 1238-1241
 
**Comment (Include rationale for comment)**: It seems so strange to see a card writer in a section called 'PIV Front-End Subsystem'.  An end user is not classically using a card writer (printing/loading cards).  Change 'card reader' to 'card reader/writer' in Figure 3-1.  Change sentences 1 and 2 to: "Card writers may be used to perform remote PIV Card updates (see Section 2.9.2)."
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
See also #306

**Comment by jricher** [comment]
duplicate of #306
