### ISSUE TITLE
Asymmetric key set different than card authentication data

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#251]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Section 4.2, line 1726
 
**Comment (Include rationale for comment)**: How is this asymmetric key set different than either the card authentication data or the PIV authentication data?  Is there a use case that can't be handled by the 2 mandatory asymmetric key sets? 
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Recommend Decline. Example is to cover Secure message and Sec-Auth keys NOT associated with an email account.(lines 1718,1719)

**Comment by regenscheid** [comment]
Decline- These are keys used for Secure Messaging, which uses a particular ECDH protocol.
