### ISSUE TITLE
Define 'retired'

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#252]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Section 4.2.2, line 1798
 
**Comment (Include rationale for comment)**: Please define 'retired'.  Or replace it with 'expired and revoked' (because sadly revocation is required when replacing these keys). 
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Discussion needed.  this is the only place we reference a "retire" key. was that he intend because key management keys could have been changed before they "expired"

**Comment by hferraio** [comment]
SP 800-73 has the following definition:  _Retired key management private keys are private keys that
correspond to X.509 Certificates for Key Management that have expired, have been revoked, or have
otherwise been superseded._ 

Maybe add this in glossary of term or in section 4.2.2 after line 1799?

**Comment by regenscheid** [comment]
Accept- will define.
