### ISSUE TITLE
Recommend moving Requirements that dictate what needs to be in a certificate doesn't fit nicely into a section that discusses where CRLs and OCSP responder

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#253]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Section 5.5, lines 2125-2129
 
**Comment (Include rationale for comment)**: Requirements that dictate what needs to be in a certificate doesn't fit nicely into a section that discusses where CRLs and OCSP responders publish information.  Consider moving it to Section 5.2.1, where the subject is 'X.509 Certificate Contents'.
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion on moving language to new section.

**Comment by regenscheid** [comment]
Decline- Section 5.5 covers certificate status information, which is the natural place to cover this material that is specific to CRLs and OCSP responders.
