### ISSUE TITLE
Recommend moving statement about Depts and agencies reporting at CA when certificates need to be revoked

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#254]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Section 5.5, lines 2130
 
**Comment (Include rationale for comment)**: This statement about Depts and agencies reporting at CA when certificates need to be revoked also doesn't fit nicely into this section.  Consider moving this to Section 5.3, 'X.509 CRL Contents'.  
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion on moving line 2130.

**Comment by regenscheid** [comment]
Decline. Section 5.3 is not a more appropriate section.
