### ISSUE TITLE
Appendix C, Card Verifiable Certificate:  This is out of alphabetic order. 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#256]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Appendix C
 
**Comment (Include rationale for comment)**: Appendix C, Card Verifiable Certificate:  This is out of alphabetic order. 
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept
