### ISSUE TITLE
Add a definition of 'certificate', and/or 'public key certificate'.

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#257]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Appendix C
 
**Comment (Include rationale for comment)**: Add a definition of 'certificate', and/or 'public key certificate'.  Here is what is in CNSSI 4009:  'A digitally signed representation of information that 1) identifies the authority issuing it, 2) identifies the subscriber, 3) identifies its valid operational period (date issued / expiration date).'  It also has 'public key certificate' with a reference back to 'certificate'.  
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest reject, this seems to be a general enough term to not warrant definition herein.

**Comment by jricher** [comment]
Accept, will add definition of certificate (and italicize use in glossary pages).
