### ISSUE TITLE
NIST SP 800-63A specifications and guidance for SRIP

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#258]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Perspecta 

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 780
 
**Comment (Include rationale for comment)**: "...issuer-controlled station, remote location, trained operator at a central location" - SP 800-63-3/2.4 allows for CSP's to be comprised of multiple independently-operated and owned business entities.  Why should this not be extended to proofing?  Should also align with language in 2.7.1 line 788.
 
**Suggested Change**:  The issuer may subscribe to or contract independently for trained operator services provided they are compliant with the NIST SP 800-63A specifications and guidance for SRIP.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Closing comment as it is a   word-for-word duplicate of #548 .
