### ISSUE TITLE
Clarification to differentiate from required proofing resources

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#260]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Perspecta

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 797
 
**Comment (Include rationale for comment)**: The introduction of draft statements requiring monitoring by staff at the station location are antithesis to the benefits and intent of SRIP
 
**Suggested Change**: If the intent is security of persons/objects, the clarification must be made to differentiate from required proofing resources (i.e., trained operators).  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Discuss.  The presence of an local staff is more than security of person/station/objects. The staff could also help/assist as needed (placement of finger ect).

**Comment by regenscheid** [comment]
Decline per issue #580.  However, note that additional clarifications will be addressed in SP 800-79.
