### ISSUE TITLE
Language regarding permiting remote identity proofing

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#268]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 781
 
**Comment (Include rationale for comment)**: "..goal..is to permit identity proofing in remote locations where it is not practical for them to travel.."

 
**Suggested Change**: …Is to permit remote identity proofing at comparable levels of confidence and security to in-person events where it is not practical or safe (e.g., COVID) for them to travel to the agency for in-person identity proofing."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to note and leave out suggested text as policy already exist to issue alternate credentials in case of COVID.  Per [OPM policy memo](https://www.opm.gov/policy-data-oversight/covid-19/opm-memorandum-on-boarding-processes-for-new-employees-during-the-covid-19-emergency/), agencies are able to make risk-based decisions to issue alternative credentials in certain circumstances.

**Comment by jglosx3** [comment]
Decline. The suggested text as policy already exist to issue alternate credentials in case of COVID.  Per [OPM policy memo](https://www.opm.gov/policy-data-oversight/covid-19/opm-memorandum-on-boarding-processes-for-new-employees-during-the-covid-19-emergency/), agencies are able to make risk-based decisions to issue alternative credentials in certain circumstances.
