### ISSUE TITLE
Physical security and integrity Requirements

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#274]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: Line 796, 797, & footnote 9
 
**Comment (Include rationale for comment)**: Excludes requirements for physical security and integrity

 
**Suggested Change**: Add "Shall employ physical tamper detection and resistance features appropriate for the environment in which it is located. " matching the requirements in SP 800-63A

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
suggest to close as it is a duplicate of [555](https://github.com/usnistgov/FIPS201/issues/555)

**Comment by jglosx3** [comment]
Duplicate of #555
