### ISSUE TITLE
Sec 2.7.1 Line 796, 797, Footnote 9 Not required by 800-63A nor is it warranted as long as security and tamper detection is implemented

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#276]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 796, 797, Footnote 9
 
**Comment (Include rationale for comment)**: Not required by 800-63A nor is it warranted as long as security and tamper detection is implemented 
 
**Suggested Change**: Strike as not applicable, Specification is not needed at the superior document level as full specification exists in 800-63A
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
closing issue as it is a word-for-word duplicate of [557](https://github.com/usnistgov/FIPS201/issues/557).

**Comment by jglosx3** [comment]
Duplicate of #557
