### ISSUE TITLE
Language of proofing for a PIV identity 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#278]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NextgenID/STA

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 778-819
 
**Comment (Include rationale for comment)**: The language of proofing for a PIV identity is too restrictively focused on the issuer. The PIV program itself is built for federation, upon a common chain of trust for users issued PIV Identity. Proofing processes should not be considered an integral, mandatory role of the issuer. This role can optionally be fulfilled by a trusted 3rdparty 

 
**Suggested Change**: The language of proofing for a PIV identity is too restrictively focused on the issuer. The PIV program itself is built for federation, upon a common chain of trust for users issued PIV Identity. Proofing processes should not be considered an integral, mandatory role of the issuer. This role can optionally be fulfilled by a trusted 3rdparty   See comment above.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Duplicate of issue #559
