### ISSUE TITLE
 Replace SHOULD on line 594 with SHALL to make this a requirement rather than a recommendation.

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#281]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Dept. of Veteran Affairs

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.4 Line 594, 595
 
**Comment (Include rationale for comment)**: Imaging from same fingers imaged for off-card one-to-one comparison represents a security vulnerability that can be used to unlock the card.
 
**Suggested Change**: Replace SHOULD on line 594 with SHALL to make this a requirement rathen than a recommendation.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
related to issue [512](https://github.com/usnistgov/FIPS201/issues/512)

**Comment by jglosx3** [comment]
Duplicate to #289

**Comment by jricher** [comment]
duplicate of #512
