### ISSUE TITLE
Specify when the CHUID authentication mechanism will no longer be an accepted practice

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#282]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Dept. of Veteran Affairs

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.1 Line 1744 - 1778
 
**Comment (Include rationale for comment)**: NIST needs to specify when the CHUID authentication mechanism will no longer be an accepted practice so agencies can plan for this expensive an laborious transition of their PACS.
 
**Suggested Change**: Provide an implementation timeline as well as provisions for the agency to identify and accept the inherent risk of non-compliance.  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
duplicate of #493. Suggest to close.

**Comment by jglosx3** [comment]
Duplicate of #493
