### ISSUE TITLE
Develop Method for Relying Party to ensure proper assurance level (e.g., IAL1-3, AAL1-3 [PIV]) 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#284]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Treasury

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2468
 
**Comment (Include rationale for comment)**: Since Federation SAML assertion does not specifically specify PIV or assurance level, how can a Replying Party ensure PIV-PKI authentication method was used by the user at the Identity Provider.
 
**Suggested Change**: Identify a method so the Relying Party can ensure the proper assurance level (e.g., IAL1-3, AAL1-3 [PIV]) used meets their digital identity risk assesment requirements for that agency application. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, this is discussed explicitly in section 7.2.

**Comment by jglosx3** [comment]
Decline- this is discussed explicitly in section 7.2.
