### ISSUE TITLE
Two fingerprints for on-card comparison (OCC)

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#285]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Treasury 

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.4 Line 594
 
**Comment (Include rationale for comment)**: "With these updates, NIST is trying to clarify that the two fingerprints for off-card one-to-one comparison MAY be taken from the full set of fingerprints collected in Section 2.3 or collected independently. However, they left out the ""or collected independently"" phrase, which should be included for clarity.
In addition, NIST is trying to clarify that the two fingerprints for OCC SHOULD be imaged from fingers not imaged for off-card one-to-one comparison. However, if this is actually a security risk, NIST should make this mandatory (SHALL).
Note: USAccess does not currently support OCC."

 
**Suggested Change**: The requirement to collect "Two fingerprints for on-card comparison (OCC). These fingerprints MAY be taken from the full set of fingerprints collected in Section 2.3 and SHOULD be imaged from fingers not imaged for off-card one-to-one comparison." should be clarified to remove any ambiguity. If there is a security concern with using the same two fingerprints imaged from fingers imaged for off-card one-to-one comparison as the two fingerprints for OCC, the word "SHOULD" should be replaced with "SHALL".

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Duplicate to #289

**Comment by jricher** [comment]
duplicate of #512
