### ISSUE TITLE
PIV card security purposes, “Two fingerprints for On Card Comparison …MAY be taken from full set of fingerprints…

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#289]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Department of Energy

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 293
 
**Comment (Include rationale for comment)**: Section 2.4: Biometric Data Collection for PIV card states that “Two fingerprints for On Card Comparison …MAY be taken from full set of fingerprints… and SHOULD be imaged from fingers not imaged for off-card one-to-one comparison.”

 
**Suggested Change**: For PIV card security purposes, “Two fingerprints for On Card Comparison …MAY be taken from full set of fingerprints… and SHALL be imaged from fingers not imaged for off-card one-to-one comparison.”

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Agree with normative SHALL?

**Comment by jricher** [comment]
duplicate of #512
