### ISSUE TITLE
Allowances for remote issuance processes

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#294]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Health and Human Services (HHS)

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 779 - 819
 
**Comment (Include rationale for comment)**: "HHS requests language that codifies that Supervised Remote Identity Proofing stations may be used for the issuance of credentials (both PIV and Derived) in addition to identity proofing, registration and PIV Card Activation Reset.  

Rationale: With the controls required by this draft to complete remote identity proofing, we believe there should be allowances for remote issuance processes as well, as long as they follow similar, if not more stringent controls. Agencies would require FIPS guidance on how to properly perform these actions.

Additionally, in the current operating environment we face due to COVID-19 - we believe we should entertain all possibilities in order to assist remote user populations, and high-risk applicants across the government."

 
**Suggested Change**: "Departments and agencies MAY use a supervised remote identity proofing station for the processes involved in the issuance of PIV Cards and Derived PIV credentials. This involves the use of an issuer-controlled station at a
remote location that is connected to a trained operator at a central location. The goal of this arrangement is to permit identity proofing of individuals in remote locations where it is not practical for them to travel to the agency for in-person identity proofing and issuance of their PIV credential.""

The issuer SHALL have local trained staff to perform card custodian operations such as receiving and controlling centrally printed card stock when the station is used for the issuance of PIV Cards. 

C.1 Glossary of Terms

Card Custodian 
An individual who has been trained to support local Supervised Remote Identity Proofing processes and can monitor the station during operations, securely control card stock received from the central location, and generally assist users during the identity proofing and registration, card issuance, and lifecycle maintenance (e.g., PIN resets) processes."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
We've talked about this before.  With a local operator present, this is a possibility.

**Comment by regenscheid** [comment]
We intended to allow this.  We will revisit this section to see what additional clarifications may be necessary.

**Comment by jglosx3** [comment]
A new section was added to specify that supervised remote idenity proofing station can support PIV card issuance.
