### ISSUE TITLE
Biometric match against original 10 prints

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#295]
### All Fields Are Required
**Organization Name (N/A, if individual)**: SSA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.4 Line 600 - 604
 
**Comment (Include rationale for comment)**: For individuals who have a reciprocal background investigation on file, it would not be possible to perform a biometric match against original 10 prints.  Reciprocity means that some individuals do not need to be re-fingerprinted to send fingerprints to the FBI as recent favorable investigation occurred and is on file  They agency may not have access to the fingerprints since none are collected due to reciprocity, they may not be the originating agency who requested the on file investigation. 

 
**Suggested Change**: Add additional language to clarify this is not required for reciprocity cases.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to note or clarify.  It is not the intent to re-connect in this case.  See DoD-11 resolution  from [FIPS 201-2 comment](https://csrc.nist.gov/CSRC/media/Publications/fips/201/2/final/documents/fips201_2_2011_draft_comments_and_dispositions.pdf) resolution

**Comment by hferraio** [comment]
See also #364 on same subject.

**Comment by jglosx3** [comment]
Accept in Principle - See rationale #364 on same/similar subject.
