### ISSUE TITLE
Equivalent replacement for CHUID authentication

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#296]
### All Fields Are Required
**Organization Name (N/A, if individual)**: SSA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 6.2.5 Line 2342 - 2343
 
**Comment (Include rationale for comment)**: "CHUID Authentication, while insecure, is the only authentication mechanism with proven technologies in the market. CAK-based solutions require industry maturity and few SM-AUTH-based solutions are on the market.  Additionally it is unclear whether SM-AUTH solutions have gone through the FICAM Test Lab or per comment on A.5 have operational viablity. SM-AUTH may be  immature solutions that may be expensive and degrade physical security operations.

Removing the CHUID authentication mechanism due to insecurity, creates additional risks for agencies as there is no clear replacement that doesn't also introduce a wide variety of challenges to overcome given industry immaturity. "

 
**Suggested Change**: Acknowledge that there is not an equivalent replacement for CHUID authentication and that the market is required to mature to meet newer authentication standards. Clarify if SM-AUTH solutions completed FICAM Test Lab validation.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend not accepting. CHUID authentication was deprecated in the previous revision, and we would likely find ourselves in the same situation in the next revision if this is extended.

**Comment by jglosx3** [comment]
Decline - CHUID authentication was deprecated in the previous revision, and we would likely find ourselves in the same situation in the next revision if this is extended.
