### ISSUE TITLE
Expand the validation program to include feedback from the federal community

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#298]
### All Fields Are Required
**Organization Name (N/A, if individual)**: SSA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: A.5 Line 2581 - 2588
 
**Comment (Include rationale for comment)**: The FIPS 201 Validation program including the FICAM test lab should not be the only program that establishes whether products conform since these programs do not validate comprehensive operational viability nor accreditation of SP800-53 controls as a requirement.

 
**Suggested Change**: Expand the validation program to include feedback from the federal community.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion.

**Comment by regenscheid** [comment]
Decline- While we agree in principle, what is being described is out of scope for the FIPS 201 Evaluation Program.
