### ISSUE TITLE
PIV Card termination procedures must be in place for both normal circumstances as well as suspected card compromise

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#304]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 2.9.4 Line 1071
 
**Comment (Include rationale for comment)**: The phrase "Similar to the situation in which the PIV Card is compromised, normal termination procedures must be in place" suggests that the topic of PIV Card termination subsequent to card compromise has previously been addressed.  This is misleading.

 
**Suggested Change**: Replace   with "PIV Card termination procedures must be in place for both normal   circumstances as well as suspected card compromise"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion regarding "compromised".

See also #305

**Comment by regenscheid** [comment]
Decline- The proposed text appears to conflate termination (where eligibility for a PIV card is lost) and revocation for lost/stolen cards. Revocation is covered in Section 2.9.1.
