### ISSUE TITLE
Explicitly state the conditions that require and individual or agency to consider that a card or logical credential has been compromised

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#305]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: Line 901, 903, 928, 934, 988, 1071
 
**Comment (Include rationale for comment)**: The term "compromised" is used 6 time in FIPS 201-3 with regard to the PIV Card or one of its logical credentials, without ever explicitly stating what qualifies as a card or logical credential being compromised

 
**Suggested Change**: Explicitly state the conditions that require and individual or agency to consider that a card or logical credential has been compromised.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion regarding "compromised".

**Comment by regenscheid** [comment]
Decline- agencies/issuers should use their own discretion to determine conditions sufficient to deem a card compromised.
