### ISSUE TITLE
Find a way to lose the term "Card Writer"

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#306]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 3.1.1 Line 1238
 
**Comment (Include rationale for comment)**: "The sentence ""Card writers, which are similar to card readers, personalize and initialize the information
stored on PIV Cards."" is completely misleading.  Three reasons: 

1. For smart card technology, the ISO/IEC standard name for this equipment is ""Card Accepting Device"".  These are commonly (and informally) called ""Card Readers.""  They are never called ""Card Writers.""  
2. All the reading and writing is done by the card's chip itself, based on commands (and perhaps authorizations and authentication) received from the Card Accepting Device.  
3. There is no difference whatsoever in card accepting devices that perform read operations vs. those that perform write operations.   They merely pass the command on to the chip."

 
**Suggested Change**: Find a way to lose the term "Card Writer."  E.g., replace the sentence with "'Card Accepting Devices', commonly called 'card readers', transmit commands to PIV Cards for either reading data from, or writing data to, PIV Cards.  Card readers are  also used to personalize and initialize the information stored on PIV Cards"

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion regarding the use of the term "Card Writer".

**Comment by regenscheid** [comment]
Decline- we're using "card writer" as part of the functional description of the component in the PIV front-end subsystem.
