### ISSUE TITLE
Replace with "from generation and loading of asymmetric keys and PKI credentials"

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#307]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 3.1.2 Line 1268
 
**Comment (Include rationale for comment)**: The phrase "from generation and loading of authentication keys and PKI credentials" is unnecessarily narrow.  The exact same can be said for digital signing and key management keys.  What they have in common is that they are all asymmetric private/public key pairs.  (Also, if restricted to just authentication keys. the "and loading" piece does not apply.)

 
**Suggested Change**: Replace with "from generation and loading of asymmetric keys and PKI credentials"

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept, seems reasonable to target the requirement like this.
