### ISSUE TITLE
Two implied SHALLs  Consider rewording to remove the implied SHALLs

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#309]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 4.1.4.3 Line 1630-1632
 
**Comment (Include rationale for comment)**: The phrase "red SHALL be reserved for emergency response offcials, blue for foreign nationals, and green for contractors." has two implied SHALLs  Consider rewording to remove the implied SHALLs

 
**Suggested Change**: Replace with "the following color coding SHALL be used:  red for emergency response officials, blue for foreign nationals, and green for contractors."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept.

**Comment by jglosx3** [comment]
Accept.
