### ISSUE TITLE
Figures 4-3, 4-4, and 4-5, change either the issue date or expiration date of each example so that the PIV Card validity period is <= 6 years

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#310]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 4.1.5 Line 1700
 
**Comment (Include rationale for comment)**: Figures 4-3, 4-4 and 4-4 all show cards with an expiration date that is 6 years + 1 day after the issue date, giving the card an apparent validity period of 6 years and 2 days.  These appear to be examples of correctly formatted cards with invalid validity periods.

 
**Suggested Change**: For Figures 4-3, 4-4, and 4-5, change either the issue date or expiration date of each example so that the PIV Card validity period is <= 6 years

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Discuss rational for date we chose in last revision.

**Comment by regenscheid** [comment]
Will revise the dates on examples.

**Comment by jglosx3** [comment]
Accept in Principle - Will revise the dates on examples.

**Comment by jglosx3** [comment]
Accept in Principle - Dates on examples have been revised.
