### ISSUE TITLE
Difference between the "SHALL" and "SHALL only" constructs

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#311]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.1 to 4.2.2.7
 
**Comment (Include rationale for comment)**: There is a subtle difference between the "SHALL" and "SHALL only" constructs that seems to be overlooked in these sections.  E.g., in 4.2.2.2, the phrase "SHALL be available through the contact and contactless interfaces of the PIV Card." requires that the capability be present on each of the two stated interfaces.  In contrast, in 4.2.2.5, the phrase "SHALL only be accessible using the contact and virtual contact interfaces of the PIV Card." requires only that capability not be accessible on any other interface.  It is completely silent as to whether the capability must be accessible on the contact or virtual contact interfaces.  This seems contrary to the actual intent.  

 
**Suggested Change**: "Although tedious, it is perhaps best to specific, complete and consistent for all these subsections.  e.g. ""If this key is present, cryptographic operations using the PIV Card's digital signature key SHALL be available through the contact interface, SHALL be available through the virtual contact interface, and SHALL NOT be available through the contactless interface.""  

Be consistent with the use of ""available"", ""accessible"", or ""performed"".   Choose one.

Be consistent with the use of ""through"" or ""on.""  Choose one.

Section-specific recommendations follow."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, I think the text is clear as written.

**Comment by jglosx3** [comment]
Resolution changed to accept in principle or partial accept. wording in Section 4.2.2.5 has been updated.

**Comment by regenscheid** [comment]
Partial Accept- Changes to Section 4.2.2.1-4.2.2.7 clarified the cryptographic operations and keys that can be used over the contact, contactless, and virtual contact interfaces.  As part of these changes, we avoided "shall only" constructs to improve clarity and readability.
