### ISSUE TITLE
Update "SHALL" and "SHALL NOT" language Sec 4.2.2.1

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#312]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.1 Line 1832-1833
 
**Comment (Include rationale for comment)**: "The cryptographic operations that use the PIV authentication key SHALL be available only through the contact and virtual contact interfaces of the PIV Card." unnecessarily separates "SHALL" and "only".  Also, it does not require that the operations be available on either of the named interfaces.

 
**Suggested Change**: Replace with "The cryptographic operations that use the PIV Card's authentication key SHALL  be available through the contact interface, SHALL  be available through the  virtual contact interface, and SHALL NOT be available through the contactless interface."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Decline- the existing text is sufficiently clear

**Comment by jglosx3** [comment]
Reopen to discuss whether or not we should change adjudication to partially accept or accept in principle.

**Comment by regenscheid** [comment]
Addressed by #667 

Accept in Principle- Changes to Section 4.2.2.1-4.2.2.7 clarified the cryptographic operations and keys that can be used over the contact, contactless, and virtual contact interfaces.  As part of these changes, we avoided "shall only" constructs to improve clarity and readability.
