### ISSUE TITLE
Cryptographic operations that use the asymmetric card authentication key

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#313]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig 

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.2 Line 1852 - 1853
 
**Comment (Include rationale for comment)**: "The statement ""Cryptographic operations that use the card authentication key SHALL be available through the contact and contactless interfaces of the PIV Card."" is silent on the virtual contact interface"

 
**Suggested Change**: Replace with "Cryptographic operations that use the asymmetric card authentication key SHALL be available through the contact, virtual contact, and contactless interfaces of the PIV Card."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
discuss.   Leaning towards decline. By design, authentication with the Card Authentication key can be done over contactless interface - without secure messaging.   Not sure what would be gained by wanting to protecting the authentication via secure messaging/VCI.

**Comment by regenscheid** [comment]
Decline- The proposed text would result in text saying a required feature would need to be available over an optional interface.  The existing text does not prohibit the CAK from being used over VCI.
