### ISSUE TITLE
If this key is present, cryptographic operations that use the symmetric card authentication key SHALL..

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#314]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.3 Line 1874 - 1875
 
**Comment (Include rationale for comment)**: The statement "The cryptographic operations that use the card authentication key SHALL be available through the contact and contactless interfaces of the PIV Card." is silent on the virtual contact interface.

 
**Suggested Change**: Replace with "If this key is present, cryptographic operations that use the symmetric card authentication key SHALL be available through the contact, virtual contact, and contactless interfaces of the PIV Card."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Decline- The proposed text would result in text saying a feature would need to be available over an optional interface. The existing text does not prohibit the (now deprecated) symmetric card authentication key from being used over VCI.
