### ISSUE TITLE
If this key is present, cryptographic operations using the PIV Card's digital signature key SHALL be available through the contact interface

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#315]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.4 Line 1879-1881
 
**Comment (Include rationale for comment)**: "If this key is present, cryptographic operations using the digital signature key SHALL be performed using the contact and virtual contact interfaces of the PIV Card." does not require the key to be available on the contact or virtual contact interfaces.  This does not seem to be the intent.

 
**Suggested Change**: Replace with "If this key is present, cryptographic operations using the PIV Card's digital signature key SHALL be available through the contact interface, SHALL be available through the virtual contact interface, and SHALL NOT be available through the contactless interface."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Group discussion. similar to the comment in #314.   Recommended change explicitly defines use case when Digital Sig Key is not accessible. He also is explicitly states that the key SHALL be available on contact and virtual contact interfaces.

**Comment by regenscheid** [comment]
The existing text is potentially confusing and will be revised.
