### ISSUE TITLE
If this key is present, the cryptographic operations that use the PIV Card's key management key SHALL..

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#316]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.5 Line 1890-1892
 
**Comment (Include rationale for comment)**: "If present, the cryptographic operations that use the key management key SHALL only be accessible using the contact and virtual contact interfaces of the PIV Card." does not require the key to be available on the contact or virtual contact interfaces.  This does not seem to be the intent.
 
**Suggested Change**: Replace with "If this key is present, the cryptographic operations that use the PIV Card's key management key SHALL be available through the contact interface, SHALL be available through the virtual contact interface, and SHALL NOT be available on the contactless interface."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Discuss with group.  Recommended change explicitly defines use case when Key management key is not accessible

**Comment by regenscheid** [comment]
The existing text is potentially confusing, possibly suggesting both the contact and virtual contact interfaces must be used.  We will revise the text in the final version.

**Comment by jricher** [comment]
See also #318
