### ISSUE TITLE
The PIV Card application administration key SHALL be available through the contact interface..

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#317]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Rick Uhrig

**Organization Type (see below for codes)**: 4 - Self
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.6 Line 1900-1901
 
**Comment (Include rationale for comment)**: "If present, the cryptographic operations that use the PIV Card application administration key SHALL only be accessible using the contact interface of the PIV Card."

 
**Suggested Change**: Replace with "If present, the cryptographic operations that use the PIV Card application administration key SHALL be available through the contact interface, SHALL NOT be available through the virtual contact interface, and SHALL NOT be available on the contactless interface.""

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Group discussion. Recommended changes accomplish the same as the original text except commenter focus on when administrative action cannot be used rather then the condition when the condition it can be used.

**Comment by regenscheid** [comment]
Will will review the use of the language across all 4.2.2.X subsections.
