### ISSUE TITLE
Allowing derived credentials on additional authentication form factors

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#320]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Yubico

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.2 Line 235
 
**Comment (Include rationale for comment)**: "The PIV Card provides multiple capabilities in one form factor:
Logical Access to IT systems, physical Access for building access, flash pass badge as an identity document. While this convergence of the multiple capabilities provides a single authenticator, it does not lend itself to reduced complexity in a number of scenarios. "
 
**Suggested Change**:  Allowing derived credentials on additional authentication form factors that are purpose-built for streamlined strong authentication, such as security keys, allows for strong authentication without having to strictly conform to the physical PIV card form factor.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Reference is confusing because Section 4.2 starts at line 1701.

We might want to request clarification; the intent of course is that DPC can be different form factors, but would like to understand where the draft might imply otherwise.

**Comment by jglosx3** [comment]
Noted - Line number reference in the comment points toincorrect line(235)  Section 4.2 starts at line 1701.

Authentication methods described in section 6.3 have updated and clarified;  that DPC can be different form factors.
