### ISSUE TITLE
Expand the definition of derived  credential

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#321]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Yubico

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.1 Line 217
 
**Comment (Include rationale for comment)**: Expand the definition of derived  credential

 
**Suggested Change**: A modern hardware-based, single purpose security device is a sound approach that provides agencies and their users the option to store derived credentials in one place and to use them on many different computing devices. Benefits include reduced costs and complexity.  In addition, the credential can be stored on an inexpensive Government Furnished Equipment (GFE) like a security key. This enables the BYOD use case and ensures the credential is stored securely on the GFE.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Confusing reference; section 2.1 begins at line 506.

Suggest this be "noted"; FIPS 201-3 of course expands the notion of derived credentials to other form factors and to non-PKI authenticators. Hopefully this will be yet clearer with the publication of the update to SP 800-157.

**Comment by jglosx3** [comment]
Noted; FIPS 201-3 of course expands the notion of derived credentials to other form factors and to non-PKI authenticators. Hopefully this will be yet clearer with the publication of the update to SP 800-157.
COMMENT Should  reference section 2.1 beginning at line 506
