### ISSUE TITLE
Allow for a single Identity Proofing event to produce multiple credentials 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#322]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Yubico

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7 Line 704
 
**Comment (Include rationale for comment)**: Allow for a single Identity Proofing event to produce multiple credentials which can be held on different authentication devices (such as a PIV card and a Security Key).

 
**Suggested Change**: This enables maximum efficiency and security. Align Identity Proofing with IAL3 summarized in 800-63-3A to allow supervised remote presence. Further, when issuing derived credentials to new authenticators , allow existing credentials issued with strong (IAL3) identity proofing to be used as proof of identity.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to note.  FIPS 201 uses SP 800-63A's specification to binding additional credentials (Derived PIV Credentials) to the PIV Account.  FIPS 201 specifies SRIP, which is a tailored profile of SP 800-63A.

**Comment by regenscheid** [comment]
Noted- this is closely related to the concept of derived credentials.
