### ISSUE TITLE
Modern authentication technologies allow for secure remote issuance

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#323]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Yubico

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7 Line 207
 
**Comment (Include rationale for comment)**: Modern authentication technologies allow for secure remote issuance. 
 
**Suggested Change**: Technologies such as manufacturer Attestation Certificates and Secure Channel Protocol 03 (SCP03) can ensure that the Security Key presented is a known and trusted credential.  Modern Security Keys support this secure remote issuance for both the PIV and FIDO credentials.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to noted.

**Comment by regenscheid** [comment]
Such technologies will be considered for Derived PIV Credentials in the revision to SP 800-157.
