### ISSUE TITLE
Federation Assurance Level 3 is good for high security, but hard to implement

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#324]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Yubico

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 7.2 Line 272
 
**Comment (Include rationale for comment)**: Start with the fact that Federation Assurance Level 3 is good for high security, but hard to implement. Tap industry to find the solution.

 
**Suggested Change**: Strong hardware-based direct authentication is preferable to Federation. New technologies, such as FIDO WebAuthn or cloud services, such as Microsoft Azure, can be utilized in place of Federation without necessitating additional friction in the user experience. Federation flows should not just limit strong authentication on initial login but based on risk levels, perform 2nd factor authentication or re-authentication against the PIV credential.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest noted.
