### ISSUE TITLE
Yubico Additional Comments without Section or Line document references

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#325]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Yubico

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: N/A
 
**Comment (Include rationale for comment)**: See attached spreadsheet
 
**Suggested Change**: See attached spreadsheet

[fips201-3-Yubico_Additional_Comments_Without_Sec._&_Line_info..xlsx](https://github.com/usnistgov/FIPS201/files/5945880/fips201-3-Yubico_Additional_Comments_Without_Sec._._Line_info.xlsx) 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion to review comments w/o section references. Topics include: Credential Types, Derived Credentials, Mobile, ID Proofing, Federation.

**Comment by regenscheid** [comment]
Noted- these were general comments that did not seek specific changes in FIPS 201-3.
