### ISSUE TITLE
Derived Credential Binding to PIV Account

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#330]
### All Fields Are Required
**Organization Name (N/A, if individual)**: XTec., Inc

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.10.1 Line 1111-1113
 
**Comment (Include rationale for comment)**: "Derived Credential Binding to PIV Account: The draft states “Derived PIV credentials SHALL be bound to the cardholder’s PIV account only by the organization that manages that PIV account.”

The language seems to imply that Derived PIV credentials can only be issued by the PIV issuing organization. This would be contrary to SP800-157. As organizations look to leverage already issued PIV credentials and as more applications enable Derived PIV authentication many use cases that support federation and interoperability arise. Specifically, an organization’s desire to leverage the PIV identity proofing already performed and issue a Derived PIV for temporary/limited application use for their organization. For example, FEMA has detailees that support disasters and come from various agencies.  FEMA issues these federal employees smart phones to support the mission.  If a detailee is from GSA, FEMA should be able to leverage their GSA PIV card to issue a FEMA derived certificate to the FEMA device the GSA detailee is using.   "
 
**Suggested Change**: "1. Remove sentence because it conflicts with SP800-157. Alternately, clarify that a PIV Card Issuer and a Derived Issuer to do not have to be the same entity which is consistent with SP 800-157 and SP 800-63. Clarify that binding is not issuance. 
2. Clarify that an “Organization” is not necessarily a “PIV Card Issuer”.
Reference 800-157 language whereby there is guidance for separate issuing organizations in Section 2.4: “A Derived PIV Credential issuer shall only issue a Derived PIV Credential to an Applicant if it has access to information about the Applicant’s PIV Card from the issuer of the PIV Card. […] Additional methods must be employed for obtaining information about the PIV Card from the PIV Card issuer”. "
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend partially accept. Comment seems to have overlooked the need to disable non-PKI derived PIV credentials if the PIV is revoked, which is problematic if the derived PIV credential is bound by other than the PIV issuer.

However, section 2.10.1 seems to be imposing this requirement on current PKI-based DPCs, which is not necessary. The requirement that the DPC issuer be the PIV issuer should only apply to non-PKI.

**Comment by jimfenton** [comment]
In fact, it has to be the PIV issuer that issues a PKI DPC certificate, and also to bind a non-PKI DPC to the account. Not accepted.

**Comment by regenscheid** [comment]
This was discussed at length during the FIPS 201-3 drafting process.  In order to keep the status of Derived PIVs aligned with the status of the PIV card and the attributes in the PIV Account, Derived PIVs must be managed by the PIV Issuer.  

But, this would not prohibit organizations from issuing other (non-PIV) credentials based on possession of PIV.

**Comment by jglosx3** [comment]
Declined. This was discussed at length during the FIPS 201-3 drafting process.  In order to keep the status of Derived PIVs aligned with the status of the PIV card and the attributes in the PIV Account, Derived PIVs must be managed by the PIV Issuer.  

This requirement does not prohibit organizations from issuing other (non-PIV) credentials based on possession of PIV.
