### ISSUE TITLE
"Relying Party", "Relying System" and "Relying Subsystem"

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#331]
### All Fields Are Required
**Organization Name (N/A, if individual)**: XTec, Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: General
 
**Comment (Include rationale for comment)**: "Relying Party", "Relying System" and "Relying Subsystem": These terms are used for what appears to be the same thing.
 
**Suggested Change**: "1. If these terms are refering to the same entity, it is suggested that a single term be used throughout FIPS 201-3 for consistency and to avoid confusion. Note that SP 800-63-3/63A/63B/63C use the term ""relying party"".  
2. If these terms are meant to refer to different entities, add each term to ""Appendix C.1 Glossary of Terms"" so that any distinctions between each is clarified."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept part (2), there are slight differences in the scope of each term that we can define.

**Comment by jricher** [comment]
Will define "Relying System" and "Relying Subsystem" as the same term, will use "Relying Party" and "RP" in only federation contexts.
