### ISSUE TITLE
Other Types of Issued Derived PIV Credential Digital Certificates

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#332]
### All Fields Are Required
**Organization Name (N/A, if individual)**: XTec., Inc

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: General
 
**Comment (Include rationale for comment)**: Other Types of Issued Derived PIV Credential Digital Certificates: Agencies may deliver Digital Signing Certificate, Encryption Certificates and Encryption Key History Keys along with Derived Credential Authentication Certificates for derived credentials issued to mobile device.
 
**Suggested Change**: Review and address these additional certificates and keys where they may apply in the draft standard.   Also, take into consideration for the next version of SP 800-157.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Let's discuss; I'm leaning toward not accepting as out of scope for FIPS 201 but perhaps others on the team have more experience with these various certificates and keys.

**Comment by hferraio** [comment]
Suggest out of scope. Digital Signature, and encryption keys (both current and historic) are not authentication credentials - they way the PIV Card's  authentication credential are or the way derived PIV credentials are.  Digital Signature and encryption purpose is different and thus DPC  requirements do not apply.  Nevertheless,  both digital signature and encryption certificates are covered in SP 800-157 and will continue to be covered (updated) in the new version of SP 800-157.

**Comment by jglosx3** [comment]
Decline - This is out of scope for FIPS201. Digital Signature, and encryption keys (both current and historic) are not authentication credentials in the way the PIV Card's  authentication credentials or derived PIV credentials are.  Digital Signature and encryption keys  are used for a different purpose  and thus DPC  requirements do not apply.  Nevertheless,  both digital signature and encryption certificates are covered in SP 800-157 and will continue to be covered (updated) in the new version of SP 800-157.
