### ISSUE TITLE
Define "Continuous Vetting Program"

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#333]
### All Fields Are Required
**Organization Name (N/A, if individual)**: XTec., Inc

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.2 Line 568
 
**Comment (Include rationale for comment)**: "Continuous Vetting Program:  Section 2.2 (Credentialing Requirements)  states ""Once the investigation is completed, the authorized adjudicative entity SHALL adjudicate the investigation and report the final eligibility determination to the Central Verification System (or successor). This determination SHALL be recorded in the PIV enrollment record to reflect PIV eligibility for the PIV cardholder and, if applicable, their enrollment in the Continuous Vetting Program.""  
Continous Vetting Program is only mentioned once in the draft and not defined. "
 
**Suggested Change**: Define "Continous Vetting Program" within FIPS 201-3, expanding on its impact/significance to Credentialing Requirements and any other relevant requirements.  Also, add this term to "Appendix C.1 Glossary of Terms" 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
suggest to partially accept. 
- accept to add Term to C.1 (Glossary of Term)
- out-of-scope to define impact/significant in the FIPS

Also double-checking with OPM on this.

**Comment by regenscheid** [comment]
A larger discussion of the Continuous Vetting Program is out-of-scope for FIPS 201.  See OPM guidance.  

Modify paragraph starting on line:
For full guidance on PIV credentialing investigative and adjudicative requirements, to include continuous vetting,
issuers must work closely with their personnel security/suitability offices to ensure
adherence to the latest federal personnel vetting guidance as provided by the Executive
Agents.

Reference
EO 13467 as amended

**Comment by jimfenton** [comment]
Executive order 13764 gives a good definition of Continuous Vetting that we might use:

> ‘Continuous vetting' means reviewing the background of a covered individual at any time to determine whether that individual continues to meet applicable requirements.

**Comment by jglosx3** [comment]
Accept in Principle - We have refrerenced Executive order 13764 which provides a good definition of Continuous Vettiing

> ‘Continuous vetting' means reviewing the background of a covered individual at any time to determine whether that individual continues to meet applicable requirements.
