### ISSUE TITLE
Temporary Resident Card

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#334]
### All Fields Are Required
**Organization Name (N/A, if individual)**: XTec., Inc

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7
 
**Comment (Include rationale for comment)**: "Temporary Resident Card:  Temporary Resident Card has been removed from the list of Forms of Identification.  
Was this intentional? Was this document replaced by another?"
 
**Suggested Change**: Verify that this change/deletion was intentional.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
I-688 (temporary resident card) has been removed since it was retired by DHS and subsequently removed as an I-9 listed id document.

**Comment by jglosx3** [comment]
Noted - I-688 (temporary resident card) has been removed because it was retired by DHS and subsequently removed as an I-9 listed id document.
