### ISSUE TITLE
6.1 Special-Risk Security Provision

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#335]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 82-97
 
**Comment (Include rationale for comment)**: "6.1 Special-Risk Security Provision
Does this now mean an agency like DHS should look for PIV card vendors that support a high-assurance on/off switch for the contactless interface?  In so doing, may these cards now be used in high-side applications?"
 
**Suggested Change**: "If turning off ""wireless"" or the contactless interface is now required depending on deployment risk, this must be formally defined.  Most likely in §2.  Otherwise, PIV card vendors may not add the capability.

Formally define that biometrics are now optional.  If high risk facilities are to be recognized and biometrics are not to be placed on the card to mitigate risk, this must be specified precisely, enabling issuers NOT to place fingerprint templates, facial images, or OCC fingerprints on the card.  Otherwise, not including fingerprint templates is a non-compliant card and will not pass 800-79 audit."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
@hferraio to look for the original motivation for the special risk section.

**Comment by jricher** [comment]
This section is a description of exceptions to the requirements in the document, not making requirements optional for all cards.

**Comment by jglosx3** [comment]
Declined - This section is a description of exceptions to the requirements in the document, not making requirements optional for all cards.
