### ISSUE TITLE
Use of other risk-mitigating methods within PIV card

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#336]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 95-97
 
**Comment (Include rationale for comment)**: Could use of the physical PIV Smart Card be mitigated by other form factors and be applicable here?  Recommend adding language enabling derived PIV credentials as mitigation mechanisms.  Example given may be Fido.  This needs an industry discussion with card manufacturers and CMS vendors.
 
**Suggested Change**: Suggest: "Use of other risk-mitigating methods such as alternate credentials (e.g., Derived PIV, Fido), or technical means within the PIV card (e.g., high-assurance on/off switches for the wireless capability), or procedural mechanisms in such situations is preferable and, as such, is also explicitly permitted and encouraged."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend not accepting. While other authenticators like FIDO are likely non-PKI derived PIV credentials, it's not clear that they particularly mitigate any risks associated with the PIV Card. The use of on/off switches for the wireless capability is already discussed in section 6.1

**Comment by jimfenton** [comment]
Declined for reasons above.
