### ISSUE TITLE
6.1 Special-Risk Security Provision

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#337]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 = Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 135-137
 
**Comment (Include rationale for comment)**: Will SP800-73 now specify the secure wireless switch for high security applications ensuring NPIVP will test for that security feature?
 
**Suggested Change**: See comment on lines 82-97.  FIPS 201-3 must explicitly define the contactless switch and no fingerprints/facial over contactless.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Duplicate of #335
