### ISSUE TITLE
Incorporate ICAMSC PIV in E-PACS

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#338]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line147-144
 
**Comment (Include rationale for comment)**: None of the specifications listed here ensure that an E-PACS lock properly interoperates with a PIV card for security and interoperability.  The ICAMSC PIV in E-PACS provides those controls.
 
**Suggested Change**: Incorporate ICAMSC PIV in E-PACS as an authoritative document.  Or formally establish it within SP800-53.

Strengthen the APL's role to enforce these controls.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion regarding E-PACS.

**Comment by regenscheid** [comment]
Noted- this is out of scope for FIPS 201-3, but we will cover this issue in the next revision of SP 800-116.
