### ISSUE TITLE
Effective Date

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#339]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 147- 151
 
**Comment (Include rationale for comment)**: 9 Effective Date
This statement does not take into consideration product development cycles, issuance lifecycle, nor relying party application lifecycle.  It does not provide effective leadership for the infrastructure of the PIV system.
 
**Suggested Change**: Recommend something like the following:
1. NIST must update SP800 series (i.e. -73, -76, -78, -79, -157) and related within six months of FIPS 201-3 release.
2. Products (e.g., PIV cards, CMSs) must comply with mandatory features within 1 year of SP800-73 series update (largely due to long certification cycles).
3. Issuers shall initiate issuance of compliant PIV cards (mandatory features) as soon as Products are available.
4. Relying party systems shall be updated with mandatory features within six months of issuer test cards being available.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion regarding SP publication info.

**Comment by jglosx3** [comment]
Accept in Principle - Effective date language has been updated to reflect current guidance.
