### ISSUE TITLE
Incorporate ICAMSC/ISC PIV in E-PACS

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#340]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 165-174
 
**Comment (Include rationale for comment)**: 11 Qualifications
This is true enough.  The standard can not dictate how to build the relying party systems.  But in the case of E-PACS, there are no governing standards on how to build those systems (unlike the plethora of LACS standards). 

**Suggested Change**: Incorporate ICAMSC/ISC PIV in E-PACS as an authoritative document.  Or formally establish it within SP800-53.  Or make PIV in ICAMSC/ISC E-PACS a NIST SP800-xx document.  See comment to 147-151 on timelines.

Strengthen the APL's role to enforce these controls.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Closely related to #338

**Comment by currydm** [comment]
Propose team discussion regarding E-PACS.

**Comment by regenscheid** [comment]
Duplicate of #338
