### ISSUE TITLE
…in the use of Identity account

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#341]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 365-367
 
**Comment (Include rationale for comment)**: "…in the use of PIV accounts."
 
**Suggested Change**: Should be:
"…in the use of Identity account."
"accounts" is a relying party application term and not applicable to PIV in this context.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Quoted text is actually on line 376.

**Comment by currydm** [comment]
Propose team discussion.

**Comment by regenscheid** [comment]
Decline, although we will revise terminology to refer to the "PIV identity account" to better describe the concept.

**Comment by jricher** [comment]
Will address terminology per #613
