### ISSUE TITLE
 "new PIV Cards SHOULD NOT"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#342]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 417-422
 
**Comment (Include rationale for comment)**: "new PIV Cards SHOULD NOT" - this is not a statement of requirement - more of an opinion, not a normative statement.
 
**Suggested Change**: Revise sentence beginning with However - However, deprecated features shall not be incorporated into new PIV card stock.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Quoted text is at line 427.

**Comment by jricher** [comment]
Decline requested change.

Will change language to "card stock" where appropriate, see #609

**Comment by jglosx3** [comment]
Decline - Will change language to "card stock" where appropriate
