### ISSUE TITLE
Update the special publications in a fully coordinated way...

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#343]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 448-462
 
**Comment (Include rationale for comment)**: This is a long list of special publications that impact the success of the PIV system.  Is there a coherent release schedule of updates to these publications to aid in product development, issuance, and relying party applications?
 
**Suggested Change**: Update the special publications in a fully coordinated way to aid in product development, issuance, and relying party systems deployment.  See comment to lines 147-151.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See also #339

**Comment by currydm** [comment]
Propose team discussion regarding SP publication info.

**Comment by jglosx3** [comment]
Noted - Will pass on suggestion to teams updating Special Publications.
