### ISSUE TITLE
2.1 Control Objectives

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#344]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 540-542
 
**Comment (Include rationale for comment)**: 2.1 Control Objectives
This now states that "...expired … credentials are swiftly revoked."
 
**Suggested Change**: Expired credentials are not serviceable after expiration.  This should state "…invalidated credentials are swiftly revoked." removing the OR condition that adds expired. Requiring revocation of expired credentials bloats CRLs unnecessarily.

Define what "invalidate" means in the definitions, and provide the "shall" use cases, the "should" use cases, and the "do not" use cases for revocation / invalidation. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion.

**Comment by regenscheid** [comment]
Agree to revise to clarify this text, particularly in light of non-PKI derived credentials.

**Comment by jglosx3** [comment]
Accept in Principle - Will revise to clarify this text, particularly in light of non-PKI derived credentials.
