### ISSUE TITLE
Enterprise IDMS authoritative for adjudication of enrollment data

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#345]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 566-568
 
**Comment (Include rationale for comment)**: "This determination SHALL be recorded in the PIV enrollment record to reflect PIV eligibility for the PIV cardholder and, if applicable, their enrollment in the Continuous Vetting Program."

There is no concept of an enrollment record that is authoritative for an individual's identity.  The enrollment record is just that.  An enrollment record.  The Enterprise IDMS is authoritative for adjudication of enrollment data and the status of an identity within an agency.

New hires are not already enrolled and must be enrolled for the first time for continuous vetting.
 
**Suggested Change**: Should be "This determination SHALL be recorded in the Enterprise Identity Management System to reflect PIV eligibility for the individual and, if applicable, their enrollment or re-enrollment in the Continuous Vetting Program."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
discuss. We actually do state what DHS comments about in line 2599-2601.

**Comment by regenscheid** [comment]
Decline: PIV enrollment record is intended to be a broader term than the record in the Enterprise IDMS. 

Also, see how this section is rephrased in #227

**Comment by jglosx3** [comment]
Decline: PIV enrollment record is intended to be a broader term than the record in the Enterprise IDMS. 

Also, see how this section is rephrased in Issue #227
