### ISSUE TITLE
2.3 Biometric Data Collection for Background Investigations

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#346]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 -Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 587-588
 
**Comment (Include rationale for comment)**: "2.3 Biometric Data Collection for Background Investigations

sph: ""These fingerprints MAY be taken from the full set of fingerprints collected in Section 2.3."""

 
**Suggested Change**: """…MAY…"" should be ""…SHALL…"" to effectively maintain the chain of trust between background investigation and credentialing.

An exception should be allowed where ""Two fingerprints for off-card one-to-one comparison may be collected only after 1:1 biometric comparison of the applicant with the fingerprints collected in Section 2.3.""  This too maintains the chain of trust.

Recommend allowing authentication via priority order of authentication in SP800-76, based off of the original two biometrics set for authentication (i.e., primary and secondary). Authentication shall always take place, before changes can be made to biometric and biographic (e.g., name) information, via a system enforcement methodology. "

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline or clarify.  The reason it should be a MAY statement is that if 10 print is collected at the same time/place as the prints for enrollment, no 1:1 comparison is necessary.  It is required, however, with extended enrollment as per line 681-688.

**Comment by regenscheid** [comment]
Decline.  You may copy the fingerprints from those taken for the background investigation, but you don't need to.  But we require chaining to address the risk that is being alluded to here.
