### ISSUE TITLE
OCC MAY also be used for cardholder authentication (OCC-AUTH)

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#348]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 618-620
 
**Comment (Include rationale for comment)**: "OCC MAY be used to support card activation as described in Section 4.3.1. OCC MAY also be used for cardholder authentication (OCC-AUTH) as described in Section 6.2.2."

 
**Suggested Change**: These statements appear limiting in nature to cardholder authentication events.  Recommend OCC also be authorized for PIV issuance and maintenance processes (as are the Off-Card Comparison Fingerprints and Iris).

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Definitely can't use OCC for issuance since there isn't a card to OCC against. I don't see a problem with using it for card maintenance operations. Recommend partially accept.

**Comment by regenscheid** [comment]
We will clarify this. The "MAY" statements on lines 618-619 were not intended to the only acceptable uses for OCC in FIPS 201.  We will rephrase this section to either remove these references, or to use non-normative language that would not suggest they're the only uses.
