### ISSUE TITLE
'The image MAY be used for cardholder authentication...'

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#349]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 629-633
 
**Comment (Include rationale for comment)**: "The image MAY be used for cardholder authentication (BIO or BIO-A) as described in Section 6.2.1."
 
**Suggested Change**: This should make automated facial recognition for cardholder authentication legitimate.  Both at time of issuance and for card lifecycle maintenance.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
suggest Noting
