### ISSUE TITLE
Instead of operator-attended, why not specify BIO-A as required?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#350]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 632-633
 
**Comment (Include rationale for comment)**: """...authentication during operator-attended PIV issuance and maintenance
processes…"""

 
**Suggested Change**: Instead of operator-attended, why not specify BIO-A as required?  Is this actually a statement that Facial for BIO is insufficient when compared to fingerprint or iris?

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to Declined. Biometric comparison is broader than BIO-A as these processes also allow a biometric comparison against the biometric in the enrollment record.

**Comment by regenscheid** [comment]
Decline.   However, requirements will be rephrased per #514
