### ISSUE TITLE
Why is chaining of biometrics allowed?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#351]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 635-639
 
**Comment (Include rationale for comment)**: "...the applicant SHALL be linked through a positive biometric verification decision by comparing biometric characteristics captured at a previous session with biometric characteristics captured during the current session."

 
**Suggested Change**:  in this fashion?  Recommend requiring 1:1 biometric authentication against the original enrollment 10-print for all sessions until issuance is complete.  This strengthens chain-of-trust.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline.  This would be a new requirement imposed on department and agencies. FIPS 201-2 was not that stringent - nor does it need to be since biometric matching against previous biometrics collected achieves the same goal. It does not have to be against the 10-print in all cases.

**Comment by regenscheid** [comment]
Decline per above.
