### ISSUE TITLE
"The card issuer"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#352]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 642
 
**Comment (Include rationale for comment)**: should use The instead of A to designate a specific group.
 
**Suggested Change**: "The card issuer"

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept.
