### ISSUE TITLE
"…individual's identity account within the Enterprise IDMS."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#353]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 646
 
**Comment (Include rationale for comment)**: "...cardholder’s PIV account."
 
**Suggested Change**: This should be "…individual's identity account within the Enterprise IDMS."  It truly is not a "PIV account," as the identity account may receive a PIV, CIV, PIV-I, Derived PIV.  These are benefits of having the identity account and being vetted for an appropriate credential (the benefit) based on need.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See also #341

**Comment by currydm** [comment]
Propose team discussion.

**Comment by regenscheid** [comment]
Duplicate of #341
