### ISSUE TITLE
Electronic Privacy Information Center (EPIC) comments

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#355]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Electronic Privacy Information Center (EPIC)

**Organization Type (see below for codes)**: 3 - Academia 
 
**Reference (Include section/paragraph or pdf line number)**: See attachment
 
**Comment (Include rationale for comment)**: See attachment
 
**Suggested Change**: See attachment

[EPIC-NIST-PIV-FIPS-Feb-2021-Comments.pdf](https://github.com/usnistgov/FIPS201/files/5946787/EPIC-NIST-PIV-FIPS-Feb-2021-Comments.pdf)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Summary:

EPIC urges NIST to revise the draft PIV FIPS to adopt privacy-enhancing standards and technologies. NIST should:
1) require anonymous credentialing for identity verification
2) limit all collection and use of biometric data to 1:1 matching with a biometric profile encoded on the identity card, not stored in a virtual database
3) require regular privacy audits of PIV systems
4) provide employees with convenient personal access to identity verification logs.

**Comment by currydm** [comment]
Propose entire team discussion.

**Comment by hferraio** [comment]
//some resolutions thus far - which might be edits still:

1) require anonymous credentialing for identity verification
2) limit all collection and use of biometric data to 1:1 matching with a biometric profile encoded on the identity card, not stored in a virtual database

//The biometrics used for authentication are stored on-card to enhance privacy. This removes the need for central database access during authentication.  Note: Other forms of biometric collection is within the context and constraints of federal laws, regulations, and policies. For example,  collection of fingerprints is part of the federal hiring process as per OPM (e.g. federal employment and PIV eligibility determination).
 
3) require regular privacy audits of PIV systems
// Noted. FIPS 201-3 requires to “Conduct a comprehensive Privacy Impact Assessment (PIA), on systems containing PII for the purpose of implementing PIV consistent with the methodology of [E-Gov] and the requirements of [M-03-22] ." This assessments should be updated regularly. 

4) provide employees with convenient personal access to identity verification logs.
//As per line 1164-1168, access is provided through fair information practices as defined in Privacy Act of 1974

**Comment by regenscheid** [comment]
The commenter requested anonymous credentials suitable for direct, offline authentication.  FIPS 201 specifies a suite of credentials, including PKI credentials supporting direct, offline authentication without intermediaries. Device or anonymous authentication mechanisms would not support important use cases that require fine-grained access control or auditing.  While there may be unidentified use cases within the Federal enterprise that could benefit from such privacy-enhancing technologies, the lack of industry-supported standards and products would make such a major architectural change to federal identity management impractical at this time.  NIST will continue to consider technical, procedural and policy privacy controls as we develop additional standards and guidelines for PIV, including privacy protection of identity attributes as we develop guidelines on the use of federation.

**Comment by jglosx3** [comment]
Accept in Principle - 

1) The commenter requested anonymous credentials suitable for direct, offline authentication. FIPS 201 specifies a suite of credentials, including PKI credentials supporting direct, offline authentication without intermediaries. Device or anonymous authentication mechanisms would not support important use cases that require fine-grained access control or auditing. While there may be unidentified use cases within the Federal enterprise that could benefit from such privacy-enhancing technologies, the lack of industry-supported standards and products would make such a major architectural change to federal identity management impractical at this time. NIST will continue to consider technical, procedural and policy privacy controls as we develop additional standards and guidelines for PIV, including privacy protection of identity attributes as we develop guidelines on the use of federation.
2) limit all collection and use of biometric data to 1:1 matching with a biometric profile encoded on the identity card, not stored in a virtual database

//The biometrics used for authentication are stored on-card to enhance privacy. This removes the need for central database access during authentication.  Note: Other forms of biometric collection is within the context and constraints of federal laws, regulations, and policies. For example,  collection of fingerprints is part of the federal hiring process as per OPM (e.g. federal employment and PIV eligibility determination).
 
3) require regular privacy audits of PIV systems
// Noted. FIPS 201-3 requires to “Conduct a comprehensive Privacy Impact Assessment (PIA), on systems containing PII for the purpose of implementing PIV consistent with the methodology of [E-Government] and the requirements of [M-03-22] ." This assessments should be updated regularly. 

4) provide employees with convenient personal access to identity verification logs.
//As per line 1164-1168, access is provided through fair information practices as defined in Privacy Act of 1974
