### ISSUE TITLE
All imperatives utilize SHALL whereas recent guidance has indicated use of this word is discouraged in favor of MUST

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#357]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: General
 
**Comment (Include rationale for comment)**: All imperatives utilize SHALL whereas recent guidance has indicated use of this word is discouraged in favor of MUST.  Not saying I necessarily agree, just pointing it out.  https://www.plainlanguage.gov/guidelines/conversational/shall-and-must/
 
**Suggested Change**: Replace SHALL with an alternate imperative, for example MUST

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, we define our normative language in the appendix.

**Comment by jglosx3** [comment]
Decline - We define our normative language in the appendix.
