### ISSUE TITLE
Cardholder UUID should be renamed to Person UUID

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#358]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 662
 
**Comment (Include rationale for comment)**: "The record MAY contain historical unique identifiers."
 
**Suggested Change**: "This should be ""The record MAY the contain the Cardholder UUID and historical unique identifiers.""

The Cardholder UUID is an important new artifact, as it pairs with the PI value, as does the Card UUID with the FASC-N Identifier, both found within the FASC-N.

The Cardholder UUID should be renamed to Person UUID, as it never changes over time and should not be confused with CHUID."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, this bullet isn't about the cardholder UUID, and FIPS201 does not name the field.

Question: should cardholder UUID be in a separate bullet here?

**Comment by jricher** [comment]
Decline to rename "Cardholder UUID" to "Person UUID".

Accept in principle to add language to suggest inclusion of Cardholder UUID in PIV Enrollment Record.

**Comment by jglosx3** [comment]
Accept in Principle - Will add language to suggest inclusion of Cardholder UUID in PIV Enrollment Record.
