### ISSUE TITLE
Suggest ""appropriately vetted"" deserves some explanation

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#359]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.1 Line 520-522
 
**Comment (Include rationale for comment)**: "A proper authority authorizing issuance happens before the identity vetting process. Suggest ""appropriately vetted"" deserves some explanation.  This is the first time it is used and it doesn't appear in the glossary."
 
**Suggested Change**: Reorder the sentence as follows:  A credential is issued to an individual only after a proper authority has authorized issuance of the credential, the individual's identity has been verified, and the individual has been appropriately vetted.  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
suggest to approve

**Comment by regenscheid** [comment]
Reword as: 
A credential is issued to an individual only after a proper authority has authorized issuance of the credential, the individual's identity has been verified, and the individual has been vetted per section 2.2.

**Comment by jglosx3** [comment]
Accept in Principle - Will re-word as: 
A credential is issued to an individual only after a proper authority has authorized issuance of the credential, the individual's identity has been verified, and the individual has been vetted per section 2.2.
