### ISSUE TITLE
Replace 'eligibility' with 'suitability'

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#360]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.1 Line 523-529
 
**Comment (Include rationale for comment)**: The use of the word 'eligibility' seems out of place here.  Eligibility for a credential depends on things like being a federal employee or contractor.  The background investigation speaks to suitability. An individual may be eligible but not suitable.
 
**Suggested Change**: Replace 'eligibility' with 'suitability' here and in other appropriate locations.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
suggest to decline. Wording is coordinated with OPM and aligned with OPM's credentialing eligibility standards

**Comment by regenscheid** [comment]
Decline.  "Eligibility" is the correct term, as covering both "suitability" and "fitness."
