### ISSUE TITLE
"... issuer SHOULD include the evidence of a formal name change."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#361]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 669-670
 
**Comment (Include rationale for comment)**: 
 
**Suggested Change**: "This should be ""...the issuer SHALL include the evidence of a formal name change.""

Without evidence, the chain-of-trust for the identity record is broken.  Changing to SHALL is consistent with §2.7 lines 723-724."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion.

**Comment by regenscheid** [comment]
Per #368, we did not intent to specify normative requirements for data elements in the PIV enrollment records.  The use of "SHOULD" in this bullet is thus potentially confusing, and it will be revised accordingly.
