### ISSUE TITLE
Flow would be improved if this paragraph preceded the paragraph above

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#362]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.2 Line 557-559
 
**Comment (Include rationale for comment)**: Flow would be improved if this paragraph preceded the paragraph above (beginning on line 550)
 
**Suggested Change**: Move paragraph.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline.

**Comment by jglosx3** [comment]
Declined - second paragraph contains the main point, third is additional.
