### ISSUE TITLE
Reword Sentence

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#363]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.2 Line 560-563
 
**Comment (Include rationale for comment)**: This sentence is awkward
 
**Suggested Change**: "Reword as follows:
For individuals for whom no prior investigation exists, the appropriate required investigation MUST be initiated with the authorized federal investigative service provider and the FBI NCHC portion of the background investigation MUST be completed and favorably adjudicated prior to PIV Card issuance."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline.

**Comment by jricher** [comment]
Accept in principle to rework sentence.

**Comment by regenscheid** [comment]
Continue to rework starting from:

"For individuals for whom no prior investigation exists, the appropriate required investigation SHALL be initiated with the authorized federal investigative service provider and the FBI NCHC portion of the background investigation SHALL be completed and favorably adjudicated prior to PIV Card issuance."

**Comment by jglosx3** [comment]
Accept in Principle - Sentence will be re-worded as follows:

"For individuals for whom no prior investigation exists, the appropriate required investigation SHALL be initiated with the authorized federal investigative service provider and the FBI NCHC portion of the background investigation SHALL be completed and favorably adjudicated prior to PIV Card issuance."
