### ISSUE TITLE
Revise this paragraph to accurately reflect later requirements

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#364]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.3 Line 580-582
 
**Comment (Include rationale for comment)**: This statement runs afoul of subsequent statements that require comparison of two fingers to 10 fingers throughout certificate life cycle.  (See lines 600-604 and footnote 6 for example).  This should state that the 10 fingerprints must be retrievable from this prior clearance.  There is also later reference to the investigation not being more than 12 years old which is not captured here.  
 
**Suggested Change**: Revise this paragraph to accurately reflect later requirements, particularly the need to retrieve the 10 prints from the original documentation and that the investigation can't be more than 12 years old.  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to relocate the paragraph to the top of the section.  See also #295 and prior resolution  wrt  re-connecting to 10 print in case where there is an adjudication on record  ( It is not the intent to re-connect in this case  per DoD-11 resolution from FIPS 201-2 comment resolution.

The 12 year refers to biometrics to be stored on-card and stored in enrollment record.  There is no statement on investigation expiration date. OPM guidelines apply in this case.

**Comment by jglosx3** [comment]
Accept in Principle -  Will add introduction paragraph at top of section 2.3.  See also #295 and prior resolution  wrt  re-connecting to 10 print in case where there is an adjudication on record  ( It is not the intent to re-connect in this case  per DoD-11 resolution from FIPS 201-2 comment resolution.

The 12 year refers to biometrics to be stored on-card and stored in enrollment record.  There is no statement on investigation expiration date. OPM guidelines apply in this case.
