### ISSUE TITLE
Revise language to ""if applicable"" or some other language for clarification

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#365]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.4 Line 587-588
 
**Comment (Include rationale for comment)**: "Should there be an 'if applicable' here?  2.3 references not collecting fingerprints in a Tier 1 or higher investigation is on record.  This could suggest it is appropriate to pull these fingerprints from that older record.
In later sections there is reference to 'no usable prints' but perhaps that should be discussed here.  From personal experience, I know that people with perfectly good fingers are sometimes physically unable to provide usable templates."
 
**Suggested Change**: "Revise this bullet to add ""if applicable"" or some other language that clarifies the two print collection.
Consider adding some discussion here of the unavailability of usable prints even when the actual fingers are present and accounted for."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Decline- the text being commented on says that you **may** take them from the fingerprints taken for the background investigation.  Other sections expand on the requirements for biometric data.
