### ISSUE TITLE
"...maximum of 12 years."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#366]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 672
 
**Comment (Include rationale for comment)**: "...maximum of 12 years."
 
**Suggested Change**: suggest defining what a year is as being 365 days or in the case of 12 years 365 days plus applicable days for leap years.  This may need to be specified explicitly in SP 800-79 and should be added to SP 800-76.  This also affects long term certificates within FPKI Common Policy.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, a few days isn't going to materially affect this time limit enough for us to have an internal definition.

**Comment by jglosx3** [comment]
Decline - A few days isn't going to materially affect this time limit enough for us to have an internal definition.
