### ISSUE TITLE
Clarify the meaning of "biometric verification attempt"

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#367]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.4 Line 596-599
 
**Comment (Include rationale for comment)**: Is this limited to electronic biometric verification attempts?  Back to the fingerprint issue.  If usable fingerprints cannot be collected, is a visual comparison of facial image acceptable.  
 
**Suggested Change**: Clarify the meaning of "biometric verification attempt"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
We will clarify this language.

**Comment by jglosx3** [comment]
Accept - Updated text will clarify "biometric verification attempt"
