### ISSUE TITLE
ID proofing, registration and biometric enrollment artifacts must be maintained as part of the cardholder's PIV account

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#368]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.6 Line 645
 
**Comment (Include rationale for comment)**: Why does this state "are generally".  Isn't PIV account interoperability across agencies enhanced by mandating the minimum data set that must be collected and maintained?
 
**Suggested Change**: Consider revising this paragraph to indicate the id proofing, registration and biometric enrollment artifacts must be maintained as part of the cardholder's PIV account.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Assigning to Hildy, Andy, and Greg as comment mentions both Enrollment and Biometric.

**Comment by regenscheid** [comment]
Decline.  This issue was considered during previous FIPS 201 revision cycles. Individuals agencies and issuers can determine what data elements are maintained in the the PIV enrollment records.

**Comment by jglosx3** [comment]
Decline - This issue was considered during previous FIPS 201 revision cycles. Individuals agencies and issuers can determine what data elements are maintained in the  PIV enrollment records.
