### ISSUE TITLE
"biometric data ... SHALL be valid for a maximum of 12 years."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#369]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 671-672
 
**Comment (Include rationale for comment)**: "The biometric data records in the PIV enrollment records SHALL be valid for a maximum of 12 years…."
 
**Suggested Change**: "This should state ""The biometric data records in the PIV enrollment records and on PIV cards SHALL be valid for a maximum of 12 years.""

As written, it is not clear that operational use of biometrics on a PIV card can not use bio that is older than 12 years."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Decline- the 12-year timeframe on biometric data on the PIV card is covered in Section 2.9.1.

**Comment by jglosx3** [comment]
Decline - The 12-year timeframe on biometric data on the PIV card is covered in Section 2.9.1.
