### ISSUE TITLE
Capitalize the F of foreign

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#370]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7 Line 729
 
**Comment (Include rationale for comment)**: The F of foreign is lower case, even though the rest of the bullets start with a capital letter
 
**Suggested Change**: Capitalize the F of foreign

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, other bullets start with proper nouns (except for drivers license, which is also lowercase.

**Comment by jglosx3** [comment]
Decline - other bullets start with proper nouns (except for drivers license, which is also lowercase.
