### ISSUE TITLE
PIV cardholder loses their card

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#372]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 690-695
 
**Comment (Include rationale for comment)**: "A PIV cardholder loses their card." Although reissuance is described further down in the document, a reader could read this and think that reissuance only applies to a lost PIV credential. 
 
**Suggested Change**: "Recommend new language be:

""Reissuance has multiple use cases; for example, a PIV cardholder loses their card."" "
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
suggest to accept in principal

**Comment by regenscheid** [comment]
Will emphasis that this is merely an example.  e.g., "A PIV cardholder, for example, loses their card."

**Comment by jglosx3** [comment]
Accept in Principle - Will emphasize that this is merely an example.  e.g., "A PIV cardholder, for example, loses their card."
