### ISSUE TITLE
Adjust language to create two sentences 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#373]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.9.3 Line 993-994
 
**Comment (Include rationale for comment)**: "A maximum of 10 consecutive PIN retries SHALL be permitted unless a lower limit is stipulated by the department or agency." should be two sentences.
 
**Suggested Change**: Revise to state: "A maximum of 10 consecutive PIN retries is permitted. Individual departments and agencies may stipulate lower maximum retry limits."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline. Note that if split, this could be two separate normative statements.

**Comment by jricher** [comment]
Accept in principle.
