### ISSUE TITLE
Identity Assurance Level (IAL) 3

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#375]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 705-707
 
**Comment (Include rationale for comment)**: "Identity proofing and registration requirements for the issuance of PIV Cards meet Identity Assurance Level (IAL) 3 since they follow a tailored process based on [SP 800-63A] IAL3 requirements."
 
**Suggested Change**: "It is generally understood that IAL3 requires verification of ID documents against the original issuer.  For the ""tailored process,"" is this required?

Verification against the issuer, especially considering the state of driver's licensing across the states and territories, means that it may not be technically feasible.  DHS recommends either clarify the requirement, or not require verification against the issuer.

Is the language in lines 760-764 be sufficient to cover this requirement? That is because ""....a federal background investigation is considered a compensating control for identity proofing at IAL3.""?"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to note. Yes, Federal background investigation is considered a sufficient compensating control for IAL-3.

**Comment by regenscheid** [comment]
Revisit the justification for IAL3, particularly related to document and attribute validation.

**Comment by jimfenton** [comment]
The control being compensated for doesn't have to do with the verification [actually validation] of ID documents against the original issuer. Rather, it is the reduction from 2 pieces of Strong evidence to 1. The background investigation easily compensates for this reduction in evidence.

The wording about compensating controls was improved by #642. I think this is sufficient.

**Comment by jglosx3** [comment]
Address by PR #642

**Comment by jglosx3** [comment]
Accept in Principle - A footnote was added to describe how compensating controls (in the form of federal background investigations) are used to achieve IAL3.
