### ISSUE TITLE
Compliance with REAL-ID

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#376]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 731
 
**Comment (Include rationale for comment)**: "...driver’s license or ID card that is compliant with [REAL-ID]…"
 
**Suggested Change**:  will be difficult.  Per DHS press release on 2020-01-24, "The states now report to DHS that they have collectively issued more than 95 million REAL ID-compliant driver’s licenses and ID cards (34%) out of 276 million total cards."  REAL ID is not at 80% deployment yet and may effectively remove the ability to use a driver's license as form of ID for PIV enrollment.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Several variation of REAL ID issue for Line 731 (primary source document):

1) 2nd vote from DoD [#232](https://github.com/usnistgov/FIPS201/issues/232)  to remove compliance to REAL ID Act
2) STA [#594](https://github.com/usnistgov/FIPS201/issues/594)  want explicit inclusion of" state or jurisdictionally identity credentials" but in compliance of REAL ID
3) topic of mobile driver license is another issue (separate)

**Comment by regenscheid** [comment]
We will clarify that the intent is to require Real ID in alignment with DHS's timeline for requiring Real ID.

**Comment by jglosx3** [comment]
Accept in Principle - We will clarify that the intent is to require Real ID in alignment with DHS's timeline for requiring Real ID.
