### ISSUE TITLE
Consider adding signature and confidentiality to the reasons the cardholder uses the card in this introductory statement

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#378]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 3.1 Line 1206
 
**Comment (Include rationale for comment)**: In addition to physical and logical access, cards and credentials can be used for signature and key management, should that be mentioned here?
 
**Suggested Change**: Consider adding signature and confidentiality to the reasons the cardholder uses the card in this introductory statement
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion.

**Comment by regenscheid** [comment]
Decline.  While we agree in principle, other section of FIPS 201 address this topic.

**Comment by jglosx3** [comment]
Decline - Other sections of FIPS 201 address this topic.
