### ISSUE TITLE
Replace Certificate with Certification 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#380]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 3.1 Figure 3.1
 
**Comment (Include rationale for comment)**: Certificate Authority should be Certification Authority
 
**Suggested Change**: Replace Certificate with Certification 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept, "Certification Authority" is used within the document elsewhere (and is in the glossary).

**Comment by jglosx3** [comment]
Accept - "Certification Authority" is used within the document elsewhere (and is in the glossary).
