### ISSUE TITLE
Replace "will be" with "is"

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#381]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 3.1.1 Line 1223
 
**Comment (Include rationale for comment)**: In other locations future tense has been replaced with present tense.  Should that be the case here?
 
**Suggested Change**: Replace "will be" with "is"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept.
