### ISSUE TITLE
"...a mutually authenticated protected channel using FIPS approved encryption algorithms."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#382]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 811-812
 
**Comment (Include rationale for comment)**: "...a mutually authenticated protected channel."
 
**Suggested Change**: "...a mutually authenticated protected channel using FIPS approved encryption algorithms."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to note. The requirement is covered in line 2568-2570.

**Comment by regenscheid** [comment]
Noted-  FIPS 201 already includes a general requirement to use FIPS validated cryptography.
