### ISSUE TITLE
Replace "might" with "may"

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#383]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: Line 1225
 
**Comment (Include rationale for comment)**: "might"?
 
**Suggested Change**: Replace "might" with "may"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, "may" sounds too close to a normative MAY.

**Comment by jglosx3** [comment]
Decline - "recommended" is the intended direction and strength.
