### ISSUE TITLE
Reword Additionally for "alternatively" 

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#384]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: Line 1230-1232
 
**Comment (Include rationale for comment)**: "Alternatively" suggests DPIV credentials can replace PIV cards.
 
**Suggested Change**: "Reword as follows:
""Additionally, derived PIV credentials  play an increasingly important role as authenticators, especially in environments where use of the PIV Card is not easily supported."""

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend accept.
