### ISSUE TITLE
Remove the 'recommendation' language here and talk about direct and federation in equal terms

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#385]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 3.3 Line 1342-1350
 
**Comment (Include rationale for comment)**: Why is the federation protocol "recommended".  Use of the strongest credentials on a PIV card do not require federation.  This is Federal organizations accepting PIV for access, which means the need for 'assertions' about identity is largely moot.  While there is certainly value to a federation approach, there are also drawbacks (single point of failure, MITM attack).   Use of the term recommended has the potential to be misinterpreted.
 
**Suggested Change**: Remove the 'recommendation' language here and talk about direct and federation in equal terms.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, "recommended" is the intended direction and strength.

**Comment by jglosx3** [comment]
Decline - "recommended" is the intended direction and strength.
