### ISSUE TITLE
Update Table 4.1

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#386]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.1.4.1 Table 4.1
 
**Comment (Include rationale for comment)**: It does not appear that examples (note none are included) would fit well into the table's third column.  As it stands, this is not as helpful as the original table.
 
**Suggested Change**: "Remove the third column and show how the name would be displayed on the card in the first (Name) column. Strange artifact in the footer should be removed."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Confirmed formatting issue, duplicate of #218 (part 5).

**Comment by jglosx3** [comment]
Duplicate of issue #218 (part 5)
