### ISSUE TITLE
Revise language throughout where a practice or item is being deprecated

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#387]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.1.4.3 Line 1595
 
**Comment (Include rationale for comment)**: Here and in other locations:  If deprecated, there should be some advice about ceasing or limiting use.  As it stands now, it sounds like deprecated doesn't have any particular expectations for behavior associated with it.  This coupled with statements like "it may be removed from future versions" doesn't convey the notion that organizations should move away or limit use. 
 
**Suggested Change**: Revise   language throughout where a practice or item is being deprecated to explain   what actions agencies should be taking regarding use of the deprecated   practice or item.  Alternatively,   include some language in the introductory section concerning deprecated   practices/items that can be referenced.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion regarding the use of "deprecated."

**Comment by hferraio** [comment]
See issue #495 also with proposed resolution.

**Comment by regenscheid** [comment]
Decline- Deprecated does not mean disallowed, nor does it necessarily mean there is a security issue.

**Comment by jglosx3** [comment]
Decline - Deprecated does not mean disallowed, nor does it necessarily mean there is a security issue.
