### ISSUE TITLE
"Adjudicative entity" not defined. 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#388]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 825 and throughout
 
**Comment (Include rationale for comment)**: "PIV Cards SHALL be issued only after the adjudicative entity…."

"Adjudicative entity"" is not defined. "
 
**Suggested Change**: Recommend "adjudicative entity" be defined, and to also go a step further and associate the term "Registrar" with this (e.g., personnel security entities, etc.)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See also #371

**Comment by hferraio** [comment]
see also issue# 371 (mentioned above).  OPM is weighing in if definition is needed.

**Comment by regenscheid** [comment]
Accept to add definition of "Adjudicative Entity."  Decline to add "Registrar", per issue #428

**Comment by jglosx3** [comment]
Accept - Add definition of "Adjudicative Entity."  Decline to add "Registrar", per issue #428
