### ISSUE TITLE
Recommend same IAL3 process against documents listed in Sec 2.7

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#390]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 842-845
 
**Comment (Include rationale for comment)**: "If the biometric verification decision is negative, or if no biometric data records are available, the cardholder SHALL provide two identity source documents (as specified in Section 2.7), and an attending operator SHALL inspect these and compare the cardholder with the photograph printed on the PIV Card."

**Suggested Change**: In the modern era of document forgeries, this may no longer be sufficient.  Humans do not do a good job of facial recognition.  Recommend the same IAL3 process against documents listed in §2.7 to improve the reliability of this decision to release the PIV card to the applicant.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline.  This process in in place for 508 compliance.  See DoT-11 from FIPS 201 Revision 2 [comments](https://csrc.nist.gov/CSRC/media/Publications/fips/201/2/final/documents/fips201_2_2011_draft_comments_and_dispositions.pdf).

**Comment by regenscheid** [comment]
Decline. We need a fall-back option if biometric verification fails. We are encouraging automated facial recognition algorithms by considering them a form of a biometric comparison.

**Comment by jglosx3** [comment]
Decline - We need a fallback option if biometric verification fails. We are encouraging automated facial recognition algorithms by considering them a form of a biometric comparison.
