### ISSUE TITLE
"...and thus incur a short employment lapse period,…"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#391]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 864-868
 
**Comment (Include rationale for comment)**: "...and thus incur a short employment lapse period,…"
 
**Suggested Change**: "There are a lot of scenarios or examples, but recommend listing the grace period for a Federal Contractor who becomes a Federal Employee (or vice versa).  Fairly common, and their may be a gap of employment. 

Recommend that a timeframe be given. At some point in time, large employment lapses are no longer acceptable. ""Short"" needs to defined. Each agency background investigation entity (adjudicative entity? Registrar?) may have different requirements for this, making interoperability difficult. Recommend a timeframe be added in for all to follow at a minimum (i.e., six months). "
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline.  Draft FIPS 201-2 had 60 days in its public commenting draft. We received [comments](https://csrc.nist.gov/CSRC/media/Publications/fips/201/2/final/documents/fips201_2_2011_draft_comments_and_dispositions.pdf) (DHS-3 and DoD-20) that OPM does not specify a time period and to please remove a specific time period. As a result, we removed the time. This time around (R3), still no specific time period is set by OPM.
