### ISSUE TITLE
Recommend ID document verification in accord with SP800-63A IAL3

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#392]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 880-885
 
**Comment (Include rationale for comment)**: "If the biometric verification decision is negative, or if no biometric data records are available, the cardholder SHALL provide two identity source documents (as specified in Section 2.7), and an attending operator SHALL inspect these and compare the cardholder with the electronic facial image retrieved from the enrollment data record and the photograph printed on the new PIV Card."
 
**Suggested Change**: §2.7 requirements, those of 842-845, and here, should line up.  Recommend ID document verification in accord with SP800-63A IAL3, not just specifying the document types to use.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
This comment serves as representative of issue #402, #405, #396.  

All comments " _Recommend ID document verification in accord with SP800-63A IAL3, not just specifying the document types to use_." Note while it is the same comment, they refer to different sections of the document. 

Suggest to decline comment as the incorporation of I-9 listed documents (with some exceptions) was specifically requested by Department and Agencies for the last revision of FIPS 201 (e.g. revision 2). See [FRN](https://www.federalregister.gov/documents/2011/03/08/2011-5259/announcing-draft-federal-information-processing-standard-fips-201-2-personal-identity-verification)

**Comment by regenscheid** [comment]
To align these sections, we will add "electronic facial image retrieved from the enrollment data record" to the bullets in 2.8.

Note that facial recognition algorithms could be considered a biometric comparison.

**Comment by gfiumara** [comment]
@regenscheid's comment _may_ be reflected in PR #639, but this PR does nothing regarding 800-63 IAL3 for document review.
