### ISSUE TITLE
Expiration date of the new PIV Card

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#394]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 907-909
 
**Comment (Include rationale for comment)**: "If the expiration date of the new PIV Card is later than the expiration date of the old card, or if any data about the cardholder is being changed, the card issuer SHALL ensure that an adjudicative entity has authorized the issuance of the new PIV Card."
 
**Suggested Change**: "Essentially, any time you re-issue a card, by definition, its expiration date will be later than the prior card.

Recommend clarifying this.  Tier 1 is a 5 year decision.  What is really the desired outcome here? Confirm the individual is still PIV eligible in the identity record?  Does the Tier 1 or Continuous Evaluation force re-adjudication updates within the identity record?  Does the re-issued card have a shorter expiration date?"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Decline: Eligibility needs to be verified by the adjudicative entity, which could be an automated process.
