### ISSUE TITLE
Is OCC allowed here?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#395]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 913-914
 
**Comment (Include rationale for comment)**: "The issuer SHALL perform a biometric verification…"
 
**Suggested Change**: "  E.g., card nearing expiration and re-issuance occurs.

What modalities?"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Accept-clarify that OCC is allowed
