### ISSUE TITLE
What happens if you reset the PIN and the biometric match fails?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#399]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 999-1000
 
**Comment (Include rationale for comment)**: "...before providing the reset PIV Card back to the cardholder..."
 
**Suggested Change**: "What happens if you reset the PIN and the biometric match fails?

Recommend reducing risk.  Recommend new language ""…before resetting the PIV Card's PIN…""  You really should know who is sitting with you prior to enabling the card for operational use again.

Recommended change is consistent with 1016-1018."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Accept- will clarify as recommended.

**Comment by hferraio** [comment]
Decline.  The suggestion would invalidate current implementation and there are safeguards in place (will be provided ONLY after successful match)
