### ISSUE TITLE
"...no later than 12 years…"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#400]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 942
 
**Comment (Include rationale for comment)**: "...no later than 12 years…"
 
**Suggested Change**: See comment to line 672.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See also #366

**Comment by regenscheid** [comment]
Decline- studies show that biometrics remain matchable for >12 years, which aligns with PIV card lifecycles.
