### ISSUE TITLE
Is OCC allowed here?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#401]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1001-1003
 
**Comment (Include rationale for comment)**: "...positive biometric verification decision when compared to biometric data records stored either on the PIV Card or in the PIV enrollment record."
 
**Suggested Change**: "Is OCC allowed here?

What modalities/authentication modes are allowed here?"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
See also #395

**Comment by hferraio** [comment]
Suggest to clarify, if needed.  OCC is  used in the Remote General computing platform case - line 1042.

**Comment by currydm** [comment]
Accept - clarify that OCC is allowed.

**Comment by jglosx3** [comment]
Accept - clarify that OCC is allowed.
