### ISSUE TITLE
Role of CVS or any successor play in PIV issuance?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#406]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1075
 
**Comment (Include rationale for comment)**: CVS or successor shall be updated to reflect the change in status.  What role does CVS or any successor play in PIV issuance? 
 
**Suggested Change**: There is no mention of CVS (or successor) prior to this bullet.  CVS's role is not understood.  Recommend a discussion with OPM occur to determine what role CVS would/could play?  Determine if this is about adjudication status or issuance status.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Discuss. 

In general, CVS ( and more importantly its role) is mentioned throughout the document. 
Section 2.2  "credentialing requirements" where final eligibility determination is required to be reported to the CVS
Section 2.9.1 "PIV Card Reissuance" to make sure prior to re-issuance, the adjudicative entity has verified eligibility in authorities record such as CVS or IDMS
Section 2.9.4 "PIV Card Termination"  where change of status needs to be reflected in CVS.  (We might want to be more clear here what _change of status_ means). 

All the above  been coordinated with OPM. Issue is coordinated as well.

**Comment by regenscheid** [comment]
We will refer to Section 2.2.

**Comment by jglosx3** [comment]
Accept in Principle - We have updated document to reflect latest OPM guidance on reporting eligibility status to  CVS and to support enrollment into Continuous Vetting Program
