### ISSUE TITLE
Timeline should be in sync with PKI CRL lifetimes of the Agency 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#407]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1087-1088
 
**Comment (Include rationale for comment)**: This timeline should be in sync with PKI CRL lifetimes of the Agency 
 
**Suggested Change**: "If the card cannot be collected, normal termination procedures SHALL be completed within the CRL validity period of the  Agencies PIV issuance CA." This is to account for not all agencies use 18 hours as the CRL validity period. DHS uses 24 hours. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline. The Common Policy specifies requirements for how quickly a CA needs to process a revocation request, but does not impose specific requirements for how quickly a revocation request must be submitted. This is addressed in FIPS 201-2 by including the informing of the CA as part of the normal termination procedures.

**Comment by hferraio** [comment]
Revisiting this - normal termination procedures are more than report/issue CRL (see line 1074-1092) - including removing FASC-N from any databases, which should be possible to do within 18 hours.  CRL issuance is covered in section 5.3 line 2108 and it does state to follow COMMON for issuance of CRL.

**Comment by jglosx3** [comment]
Decline - Normal termination procedures are more than report/issue CRL (see line 1074-1092) - including removing FASC-N from any databases, which should be possible to do within 18 hours.  CRL issuance is covered in section 5.3 line 2108 and it does state to follow COMMON for issuance of CRL.
