### ISSUE TITLE
Update "account" to be "identity account.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#409]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1111-1113
 
**Comment (Include rationale for comment)**: "Derived PIV credentials SHALL be bound to the cardholder’s PIV account only by the organization that manages that PIV account."
 
**Suggested Change**: Update "account" to be "identity account."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend not accepting. PIV Account is a term used extensively in the document and is defined at lined 2860-2864.

**Comment by regenscheid** [comment]
Will rephrase as PIV identity account, per #613
