### ISSUE TITLE
 "Derived PIV credentials SHALL be bound to the cardholder’s PIV account..."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#410]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 
 
**Comment (Include rationale for comment)**: "Derived PIV credentials SHALL be bound to the cardholder’s PIV account only by the organization that manages that PIV account."
 
**Suggested Change**: "1. There may be a need for a detailee from one agency to receive a Derived PIV from another agency (e.g., DoD detailed to DHS) when they receive a managed mobile device from the detailed assignment agency (DHS).

As written, if I am detailed from one agency to another, if I need a Derived PIV in the new agency, the new agency must issue a second PIV to the detailee.  Is that the desired affect here?  For those striving for one identity/one PIV, this may not work well.

Should this restriction apply only to the managed mobile device receiving a credential being managed by the same agency that issued the derived PIV?

2. Concur, clarification is needed. Is the intent to trust the PIV issued from an outside agency (e.g., detailee coming from DOJ to DHS), and be able to issue a derived PIV off of the original issued PIV? Or, is the requirement for the agency being detailed to, will issue a second PIV card (e.g., have a DOJ PIV and a DHS PIV) and then bind the derived credential to the detailed agency PIV? "
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Comment does not consider the use of federation between the detailee's home agency and the agency to which they have been detailed. This is the preferred solution to the problem of needing an additional account.

However, in the specific example given (involving mobile devices and probably PKI-based DPC), the restriction is not required. See #330 

Recommend narrowly accepting to exempt PKI-based DPC from the issuing agency requirement.

**Comment by jimfenton** [comment]
Basically the same comment as #330
