### ISSUE TITLE
Define "invalidated" in the glossary

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#411]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1115 and throughout
 
**Comment (Include rationale for comment)**: "Derived PIV credentials SHALL be invalidated in any….."
 
**Suggested Change**: Define "invalidated" in the glossary. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend accepting. This term is used several times in FIPS 201.

Also need to look at usage in SP 800-63B. It tends to use the phrase 'revoke or suspend' and _invalidate_ might be a better choice there.
