### ISSUE TITLE
Derived should expand to all future use cases, such as Fido, DigSig, KMK.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#412]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS
**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1124-1125
 
**Comment (Include rationale for comment)**: "...contains a derived PIV authentication certificate..."
 
**Suggested Change**: Concerns of invalidation/revocation must be expanded to include all derived PIV credentials.  Derived PIV Authentication is just one of them.  Derived should expand to all future use cases, such as Fido, DigSig, KMK.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend declining. The full sentence begins, "If the derived PIV credential contains a derived PIV authentication certificate..." so this is a conditional requirement. Other types of derived PIV credentials are supported, but this requirement only applies to PKI-based DPC.

**Comment by jimfenton** [comment]
Digital signature and key management keys are not part of derived PIV, and non-PKI DPCs such as FIDO would be invalidated by removing the linkage to the PIV account.
