### ISSUE TITLE
When invalidation occurs, the issuer SHALL notify the cardholder of the change

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#413]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1129-1130
 
**Comment (Include rationale for comment)**: "When invalidation occurs, the issuer SHALL notify the cardholder of the change."
 
**Suggested Change**: IAW SP800-53, when you revoke/lock an IT system account/etc., you do not inform the person the action has been taken.  When it fails to work, they call in and are managed through a secure process.

See comment to 1115.

Recommend delete.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Not aware of any prohibition in 800-53, and FIPS 201 can require this notification.
