### ISSUE TITLE
MAY choose to deploy PIV Cards with electromagnetically opaque holders or other technology…"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#414]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1182-1183
 
**Comment (Include rationale for comment)**: "MAY choose to deploy PIV Cards with electromagnetically opaque holders or other technology…"
 
**Suggested Change**: At this point in time, MAY ought to be SHALL.  This change would go a long way toward protecting the VCI for issuers who choose not to use the pairing code.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline.  This is addressed in SP 800-73.    As described in SP 800-73, implementing VCI without pairing code is a risk-based decision each agency has to take based on risk assessment.  It states:  **

_A DAA’s decision to approve the issuance of PIV Cards that implement the VCI without requiring the pairing code shall be based on a risk assessment that weighs the perceived benefit against the risk of unauthorized disclosure of cardholder data exposing previously contact-restricted X.509 certificates to skimming. The previously contact-restricted X.509 certificates include information about the cardholder such as name and email address. Compensating controls shall be captured in the
appropriate system security plan._

**Comment by hferraio** [comment]
Declined for reasons mentioned above.
