### ISSUE TITLE
Recommend adding, "...This subsystem depends on the PIV Front-End Subsystem"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#416]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1212
 
**Comment (Include rationale for comment)**: "...directories and certificate status servers. This subsystem also..."
 
**Suggested Change**: Recommend adding "...directories and certificate status servers. This subsystem depends on the PIV Front-End Subsystem to interact with the PIV card during issuance and management activities.  This subsystem also…"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion. 

See also #417 for related PIV Issuance and Management Subsystem

**Comment by regenscheid** [comment]
Decline- The text that was commented on was not intended to describe the relationship between the different subsystems.
