### ISSUE TITLE
"…the binding and termination…"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#417]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1212-1213
 
**Comment (Include rationale for comment)**: "…the binding and termination…"
 
**Suggested Change**: Other parts of this draft use "…the binding, issuance, and termination…".  Recommend adding issuance for consistency.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion.

**Comment by regenscheid** [comment]
Accept- while derived PIV credentials are not necessarily issued (e.g., in the case of non-PKI derived PIV credentials), they would be in the case of PKI-based DPCs.  We can add "issuance" to cover the PKI case.
