### ISSUE TITLE
Physical and logical access control systems

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#418]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1215-1216
 
**Comment (Include rationale for comment)**: "The physical and logical access control systems, protected resources, and authorization data."
 
**Suggested Change**: Recommend "The physical and logical access control systems, and their authorization data, that interact with the PIV Front-End Subsystem components to protect federal facilities, networks, and systems."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion. 

See also #420 #419 regarding PIV Relying Subsytem

**Comment by regenscheid** [comment]
Declined- this text wasn't intended to describe the interconnection of components.
