### ISSUE TITLE
PIV Relying Subsystem is not properly defined here

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#419]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1220-1221
 
**Comment (Include rationale for comment)**: Figure 3-1 is hugely improved.  PIV Relying Subsystem is not properly defined here.
 
**Suggested Change**: PIV Relying Subsystem needs to be structured around access control systems/authorization data, not around devices.  Both LACS and PACS rely on PIV Front-End Subsystem components to let someone gain access to a resource.

Replace LACS bullet list with * Directory Services; *Privileged Access Services; *VPN Services.

Replace PACS bullets with * PACS Host Servers; * PACS Door Controller Panels. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion. 

See #420 also mention figure 3-1

**Comment by regenscheid** [comment]
Decline- the existing text already addresses authorization data, but was not intended to address specific technologies or product classes.
