### ISSUE TITLE
PIV Front-End Subsystem

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#420]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1222-1223
 
**Comment (Include rationale for comment)**: "The PIV Front-End Subsystem in Figure 3-1 consists of credentials and devices that are used during authentication."
 
**Suggested Change**: Recommend "The PIV Front-End Subsystem in Figure 3-1 consists of credentials and devices that are used during card issuance, authentication, and card lifecycle management."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion.

**Comment by regenscheid** [comment]
While the PIV Front-end subsystem is not used for management, we will relocate discussion of PIV card lifecycle management from Section 3.1.1 to 3.1.2.
