### ISSUE TITLE
Biometric capture devices

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#423]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1251-1252
 
**Comment (Include rationale for comment)**: "Biometric capture devices may be located at secure locations where a cardholder may want to gain access."

They are also used as part of the ID Proofing and Registration process for card lifecycle management, not just access control.
 
**Suggested Change**: Recommend the following...

"Biometric capture devices are part of the identity proofing and registration process that supports the PIV Issuance and Management Subsystem.   They are also located at secure portals of entry where a cardholder may want to gain access."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The following sentence (not quoted) says this is using biometric data stored on the card. That's not the case for issuance, and may or may not be true for maintenance. But the quoted text seems a bit narrow. Suggest accepting in principle to broaden the statement as appropriate.

**Comment by regenscheid** [comment]
Section 3.1.1 is intended to be the subsystem used for authentication, after credentials are issued. Some of the proposed text would fit better in Section 3.1.2.  

As part of that update, we should review other parts of 3.1.1 to ensure other issuance and registration activities are in 3.1.2.
