### ISSUE TITLE
More than logical credentials are put on the card

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#424]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1262-1263
 
**Comment (Include rationale for comment)**: "...physical (visual surface) and logical (contents of the ICC)…"

More than logical credentials are put on the card.  Also includes printed surface, person identifiers, PACS credentials, facial image, etc.

**Suggested Change**: Recommend "...physical (visual surface) and electrical (contents of the ICC)…"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
similar to #429 (duplicate?)

**Comment by hferraio** [comment]
Declined. Logical content is more than what is listed in the suggested change.  It includes anything in the ICC.
