### ISSUE TITLE
PIV account

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#425]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1276-1278
 
**Comment (Include rationale for comment)**: "It is where the relevant cardholder attributes are maintained. The IDMS creates the PIV account and associates the cardholder’s PIV Card and derived PIV credentials with the account. The account…"

The word account really does not work here, per previous comments.  This is not an account you login to and use. Rather, an identity record is established and maintained with PIV/Derived PIV information via Enterprise IDMS.
 
**Suggested Change**: Recommend…

"It is where the relevant cardholder attributes are maintained. The IDMS creates the identity account and associates the cardholder’s PIV Card and derived PIV credentials with the identity record. The identity record..."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
related to (and same resolution as) #341 - note: comment is for different location (line number) than 341.

**Comment by regenscheid** [comment]
Decline, however will make changes that address issues related to this. Per #492, we use the term IDMS to refer to the collection of records, which may be split across multiple components.  And per #613, we will rephrase the term PIV Account to PIV Identity Account to distinguish it from application/system accounts.
