### ISSUE TITLE
Recommend adding PACS

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#426]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1296-1297
 
**Comment (Include rationale for comment)**: "...associated with a file on a computer system."

This is LACS only. Recommend adding PACS.
 
**Suggested Change**: Recommend "...associated with a file on a computer system, or a secure portal (E-PACS controlled) within a facility."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend accepting, seems reasonable to include PACS here.

**Comment by hferraio** [comment]
Accepting to add the additional text.

**Comment by jglosx3** [comment]
Accept - Will add the additional text recommended.
