### ISSUE TITLE
Recommend adding PIV Card Destruction

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#427]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1309-1337
 
**Comment (Include rationale for comment)**: Seven card lifecycle activities listed - PIV Card Destruction not in the list.
 
**Suggested Change**: Recommend adding an additional lifecycle activity for PIV Card Destruction and update Figure 3-2
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Decline. It is already covered in line 1345.
