### ISSUE TITLE
PIV Card Request authorization

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#428]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1315-1317
 
**Comment (Include rationale for comment)**: "PIV Card Request: The initiation of a request for the issuance of a PIV Card to an applicant and the validation of this request."

As it stands, it does not explain who is authorized to fulfill this request. 
 
**Suggested Change**: Recommend explicitly stating that the "Registrar" is the authorized entity required to approve a "PIV Card Request," and validate the requirement (e.g., authorized adjudicative entity, personnel security entity). 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline.  The term registrar was used in prior version of  the  FIPS 201 and has been removed in revision 2 given comments that the term is confusing and given agency have different name/title for the role.

**Comment by jglosx3** [comment]
Decline - The term registrar was used in prior version of  the  FIPS 201 and has been removed in revision 2 given comments that the term is confusing and given agency have different name/title for the role.
