### ISSUE TITLE
"Generation of logical credentials…"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#430]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1326
 
**Comment (Include rationale for comment)**: "Generation of logical credentials…"
 
**Suggested Change**: Recommend for consistency with line 1333 "Generation of PKI credentials…" 

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
agree.

**Comment by hferraio** [comment]
Accept

**Comment by jglosx3** [comment]
Accept - Will make recommended change
