### ISSUE TITLE
Physical access systems

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#431]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1352-1353
 
**Comment (Include rationale for comment)**: "For example, physical access systems are not usually well-suited for a federation protocol."
 
**Suggested Change**: The market/technology for PACS is changing and this statement may no longer be true.  It is not a necessary statement, so recommend deleting it. It is limiting on how PACS may be implemented.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, this is a comment on the current state and is not universal.

**Comment by jricher** [comment]
Accept in principle, reword to something like "For example, physical access systems tend not to use federation protocols."

**Comment by jglosx3** [comment]
Accept in Principle - Will re-word to  " physical access systems tend not to use federation protocols and instead rely on direct authentication"
