### ISSUE TITLE
Recommend being explicit about dual-interface, not dual-chip

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#432]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1369-1371
 
**Comment (Include rationale for comment)**: "The PIV Card SHALL comply with the physical characteristics described in [ISO 7810], [ISO 10373], and [ISO 7816] for contact cards in addition to [ISO 14443] for contactless cards."
 
**Suggested Change**: Recommend now being explicit about dual-interface, not dual-chip.  The market truly has decided this issue regarding certified PIV card stock.  Also, ISO 10373 applies equally to contact and contactless, not just contact.

ISO14443 Type A vs Type B should also be recognized.  This dramatically impacts reliability in the field.  The market has clearly determined Type A.

Recommend...
"The PIV Card SHALL be a dual-interface card.  It SHALL comply with the physical characteristics described in [ISO 7810], and [ISO 7816] for contact cards, and [ISO 14443] Type A for contactless cards.  It shall comply with [ISO 10373] test methods for both contact and contactless interfaces."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Discuss - suggest to decline as this can be addressed in SP 800-96 as needed.  Note: FIPS 201 is inclusive of both dual and single chip implementations and should not further restrict possibly legitimate card chip configuration.  Changes to chip type/communication is addressed in SP 800-96.

**Comment by hferraio** [comment]
Note: FIPS 201 is inclusive of both dual and single chip implementations and should not further restrict possibly legitimate card chip configuration. Changes to chip type/communication is addressed in SP 800-96. See also #438 for line 1466-1467

**Comment by jglosx3** [comment]
Decline -  FIPS 201 is inclusive of both dual and single chip implementations and should not further restrict possibly legitimate card chip configuration. Changes to chip type/communication is addressed in SP 800-96. See also #438 for line 1466-1467
