### ISSUE TITLE
The PIV Card SHALL contain a contact and a contactless ICC interface.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#433]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1397
 
**Comment (Include rationale for comment)**: "The PIV Card SHALL contain a contact and a contactless ICC interface."
 
**Suggested Change**: Per prior comment on 1369-1371, recommend being explicit:

"The PIV Card SHALL be a dual-interface card with a single chip, a contact and a contactless ICC interface."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Duplicate to #423

**Comment by jimfenton** [comment]
I don't see how this is a duplicate to #432. Wonder if the issue number had been mistyped.

**Comment by jglosx3** [comment]
Consider duplicate of 432
