### ISSUE TITLE
Manufacturers guarantee their cards, including the laundry test.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#434]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1421-1422
 
**Comment (Include rationale for comment)**: "Cards SHALL NOT malfunction or delaminate after hand cleaning with a mild soap and water mixture."
 
**Suggested Change**: This is the only requirement that was tested as part of the NVLAP supported GSA APL test program.  Manufacturers guarantee their cards, including the laundry test.  This requirement adds no value to the actual PIV card.

The manufacturer's card body (subject of the requirement) is not the real problem here. More likely it will be issues with things like color fading and peeling laminate, not the card body itself.

Recommend deleting this requirement.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Noted

**Comment by hferraio** [comment]
Decline. It is important to keep it in the Standard - as described. The test is being done by manufacturer. Good!

**Comment by jglosx3** [comment]
Decline - It is important to keep it in the Standard - as described. The test is being done by manufacturer.
