### ISSUE TITLE
Punching a card to use a lanyard is strongly discouraged by manufacturers

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#435]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1442-1443
 
**Comment (Include rationale for comment)**: Departments and agencies MAY choose to punch an opening in the card body to enable the card to be oriented by touch or to be worn on a lanyard.
 
**Suggested Change**: Punching a card to use a lanyard or for tactile card orientation is strongly discouraged by manufacturers and most issuers do not do it.  This language does not match current practices within the PIV card domain.

If you do punch a PIV card, and the hole avoids the contactless antenna, you will punch part of the security elements that are printed for an individual on their PIV card (e.g., goes through facial image).

Recommend deleting this language.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to note.  This was requested by US Access Board on FIPS 201-2 revision ([comment](https://csrc.nist.gov/CSRC/media/Publications/fips/201/2/final/documents/fips201_2_2011_draft_comments_and_dispositions.pdf) keyword USAB-4) Punching a hole is at agencies discretion - other method for 508 are also a possibility in FIPS 201.

**Comment by hferraio** [comment]
Declined. This was requested by US Access Board on FIPS 201-2 revision (comment keyword USAB-4) Punching a hole is at agencies discretion - other method for 508 are also a possibility in FIPS 201.
