### ISSUE TITLE
"The PIV Card MAY be subjected to additional testing."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#436]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS
**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1458
 
**Comment (Include rationale for comment)**: "The PIV Card MAY be subjected to additional testing."

This is is an open ended requirement that can not be met by manufacturers/issuers alike.
 
**Suggested Change**: What is the intent of the statement?  That FIPS 140 applies?  NPIVP? Anything else?  FPKIPA or APL testing?  None of these have anything to do with the manufacture of the card or specifications on interaction with the ICC.

Not clear why this is needed in FIPS 201.  Recommend delete.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Discussion needed.  We we want to expand on testing requirements?
