### ISSUE TITLE
Recommend "Electrically stored…" for specific reference to the ICC.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#437]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1463
 
**Comment (Include rationale for comment)**: "Logically stored..." is no longer accurate
 
**Suggested Change**: Recommend "Electrically stored…" for specific reference to the ICC.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
similar to #429

**Comment by regenscheid** [comment]
Declined. Logical content is more than what is listed in the suggested change. It includes anything in the ICC.

Similar to #424
