### ISSUE TITLE
Recommend use of an agency seal is REQUIRED - not a CONSIDERATION

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#440]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1- Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1601-1604
 
**Comment (Include rationale for comment)**: Agency Seal; if used 
 
**Suggested Change**: Recommend use of an agency seal is REQUIRED - not a CONSIDERATION
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
This has not been a change request prior to publication of the draft.  In order to require it, section 1.3 change management principles apply - that is introduce it as option (which it is) in our version of the FIPS and make it normative in the next (R4).

**Comment by jimfenton** [comment]
Suggest adding something like: Note: Inclusion of the agency seal may be required by future editions of this specification.

**Comment by jglosx3** [comment]
Accept in Principle: Language will be updated to indicate inclusion of the agency seal may be required by future editions of this specification.
