### ISSUE TITLE
‘…Logical Characteristics’ is actually ‘Electrical Characteristics’

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#441]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1701
 
**Comment (Include rationale for comment)**: "…Logical Characteristics"
 
**Suggested Change**: Is actually "…Electrical Characteristics"

Actually, for consistency, this should line up with SP800-73 which calls this the ""PIV Card Data Model"" as stated at line 1710."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Reject use of "Electrical Characteristics".  Discussion need on whether or not to change to PIV Card Data Model. We define in second paragraph that he data elements are part of eh Data model for PIV chard Logical Characteristics.

**Comment by regenscheid** [comment]
Declined. Logical content is more than what is listed in the suggested change. It includes anything in the ICC.

Similar to #424
