### ISSUE TITLE
"The FASC-N, card UUID, and expiration date SHALL NOT be modified post-issuance."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#443]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1765
 
**Comment (Include rationale for comment)**: "The FASC-N, card UUID, and expiration date SHALL NOT be modified post-issuance."
 
**Suggested Change**: This is missing a key data element.  Just like the PI within the FASC-N, the Cardholder (Person) UUID shall not be modified post issuance.  

"The FASC-N, Card UUID, Cardholder UUID, and expiration date SHALL NOT be modified post-issuance."

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
NOTED-Cardholder UUID is in current version of PIV 201-3

**Comment by regenscheid** [comment]
Accept.  Add "...expiration date, and, if present, the cardholder UUID, SHALL not be modified post-issuance"
