### ISSUE TITLE
Symmetric card authentication key

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#444]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1789
 
**Comment (Include rationale for comment)**: "Symmetric card authentication key"
 
**Suggested Change**: This is a requirement to the benefit of a single vendor in the E-PACS marketplace.  It is not cross-agency interoperable. It is not tested by the GSA APL because key management is unknown and a testing harness is not feasible.  This method is not widely used.  Asymmetric performance on PIV cards with E-PACS is similar to that of symmetric authentication.  This mechanism should be DEPRECATED in this version of the standard.  This will further enhance interoperability across all agencies for use of the PIV card.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Noted? The quoted text says exactly what is being requested, that the key is deprecated.

**Comment by regenscheid** [comment]
Related to #207
