### ISSUE TITLE
Symmetric cryptographic operations

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#445]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1826-1827
 
**Comment (Include rationale for comment)**: "Symmetric cryptographic operations are not mandated for the contactless interface, but departments and agencies MAY choose to supplement the basic functionality with storage for a symmetric card authentication key and support for a corresponding set of cryptographic operations. For example, if a department or agency wants to utilize an Advanced Encryption Standard (AES) based challenge/response for physical access, the PIV Card SHALL contain storage for the AES key and support AES operations through the contactless interface."
 
**Suggested Change**: See comment on line 1789.  This language should be deprecated or removed.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Se #444

**Comment by jimfenton** [comment]
Comment doesn't quite line up with the line numbers. But we are deprecating the symmetric card authentication key. Suggest "noted".

**Comment by jimfenton** [comment]
Cited text is no longer in the draft specification; it was in section 4.2.2 of FIPS 201-2
