### ISSUE TITLE
PIV authentication certificate background investigation indicator

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#447]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1843-1848
 
**Comment (Include rationale for comment)**: "The PIV authentication certificate MAY include a PIV background investigation indicator (previously known as the NACI indicator) extension (see Appendix B.2). This non-critical extension indicates the status of the cardholder’s background investigation at the time of card issuance."
 
**Suggested Change**: "This non-critical extension is never evaluated by relying party systems. To date, no issuance system does a post-issuance update when the status flips from partial to full investigation complete.

This extension is outdated and should be removed from the standard."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to Note.  The NACI indicator is being deprecated (see line 2957).  We might want to add a footnote here that it is deprecated.

**Comment by jglosx3** [comment]
Noted - The NACI indicator is being deprecated (see line 2957).
