### ISSUE TITLE
Revise language so that it is clear that when a card needs to indicate Federal Emergency Response Official

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#448]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.1.4.3 Line 1605-1619
 
**Comment (Include rationale for comment)**: Revised language makes placement of the Federal Emergency Response Official banner ambiguous.  Note opening sentence "If used as the federal emergency response official identification label. . ."  Assuming consistency in placement of this label is still expected, this section should start with a statement to that effect and then provide the additional language for situations where this designator is not required.  Also, isn't it time to mandate white on red?    
 
**Suggested Change**: Recommend revising language so that it is clear that when a card needs to indicate Federal Emergency Response Official, it is in Zone 12F.  Also, consider requiring white on red except for extenuating circumstances (if there are any).
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Declined?  Discussion under Zone 12F fo0ter clearly denotes that it SHALL be in zone 12 F.  No other option is provided to designate Emergency responder status. If Zone 12F is not used to denote emergency response it can be used to designate counter of citizenship.  Color choices are not mandated.

**Comment by regenscheid** [comment]
Clarify that if a card is intended to identify an emergency response official, then 12F is the intended location.  Need to discuss the situation where an agency may want to identify both emergency response officials and country of citizenship for foreign national cardholders.
