### ISSUE TITLE
Typo: mechanism is misspelled

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#449]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.1 Line 1745
 
**Comment (Include rationale for comment)**: Typo: mechanism is misspelled
 
**Suggested Change**: Correct spelling of mechanism.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept.

**Comment by jglosx3** [comment]
Accept - Typo in text wil be updated
