### ISSUE TITLE
Consider revising the statement concerning the SYM-CAK

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#451]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2 Line 1790
 
**Comment (Include rationale for comment)**: If deprecated, is it still optional?
 
**Suggested Change**: Consider revising the statement concerning the SYM-CAK
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Suggest not accepting. Key was optional in FIPS 201-2, deprecated and optional seems like the right next step before making it go away entirely.

**Comment by jglosx3** [comment]
Decline - Key was optional in FIPS 201-2, deprecated and optional seems like the right next step before making it go away entirely.
