### ISSUE TITLE
Revise to include digsig certificate

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#453]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 5.2.1 Line 2100
 
**Comment (Include rationale for comment)**: This statement should include the digsig certificate, since this should be generated on card, never exported and would therefore die with the card. 
 
**Suggested Change**: Revise to include digsig certificate.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
recommend decline comment.  Was our intend was to tie card expiration only to authentication keys?

**Comment by regenscheid** [comment]
Decline.  This is out of scope for FIPS 201 and is more of an issue for the certificate policy.
