### ISSUE TITLE
Reconsider removal of Section 6.1.1

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#455]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 6.1.1 Line 2179-2181
 
**Comment (Include rationale for comment)**: It would seem more correct to reference HSPD-12 and M-19-17 here, since those two documents are Federal Identity Policy and do provide the justification for the existence and continuing existence of FIPS 201
 
**Suggested Change**: Reconsider removal of Section 6.1.1

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion.

**Comment by regenscheid** [comment]
Accept- we're expand on the relationship between FIPS 201, M-19-17 and HSPD-12.
