### ISSUE TITLE
Consider revising this bullet to remove "previously issued"

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#456]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 6.2.3.1 Line 2268
 
**Comment (Include rationale for comment)**: This is a list of steps in authenticating using PIV-AUTH.  As such, use of "previously issued" in the bullet starting on line 2268 is unnecessary
 
**Suggested Change**: Consider revising this bullet to remove "previously issued"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Suggest accepting; minor editorial cleanup.
