### ISSUE TITLE
Discuss federation as a viable alternative to direct trust but not the 'preferred' method

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#457]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CertiPath Inc.

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 7.3 Line 2496-2498
 
**Comment (Include rationale for comment)**: See previous comment.  Use of the term 'recommended' here may provide a false sense of necessity to agency readers.  There are certainly times when the federated approach is warranted, but there are also times when the direct use of the PIV credential makes more sense.  This section speaks to the Benefits of Federation but fails to discuss any of the drawbacks or vulnerabilities.  In addition there is no parallel discussion of the Benefits of directly trusting PIV credentials.  
 
**Suggested Change**: Revise this section to remove the term 'recommended' and discuss federation as a viable alternative to direct trust but not the 'preferred' method.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Duplicate of #385
