### ISSUE TITLE
Symmetric Card Authentication Key

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#459]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1865-1868
 
**Comment (Include rationale for comment)**: Symmetric Card Authentication Key
 
**Suggested Change**: Should be deprecated.  See comment to 1789.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Duplicate of #444?

**Comment by jimfenton** [comment]
Yes, and it clearly says that it is deprecated.
