### ISSUE TITLE
Recommend requiring use of the content signing key in the CHUID

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#460]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1950-1953
 
**Comment (Include rationale for comment)**: "If the signature on the biometric data record was generated with a different key than the signature on the CHUID, the certificates field of the CMS external digital signature SHALL include the content signing certificate required to verify the signature on the biometric data record. Otherwise, the certificates field SHALL be omitted."
 
**Suggested Change**: "To our knowledge, there are no issuers that use a separate biometric content signing key from the content signing key in the CHUID.

Recommend deprecating this language and requiring use of the content signing key in the CHUID."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Discussion needed. The current language allows the option of using a signing key other than the one used to sign the CHUID. Is there a reason to prohibit use of another signing key?

**Comment by regenscheid** [comment]
While we can't prohibit use of a different key in this revision, we can include stronger language and indicate it may be required in subsequent revisions.
