### ISSUE TITLE
Missing identifier for the card itself

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#461]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1972-1974
 
**Comment (Include rationale for comment)**: "The two types of identifiers that serve as identification (of the cardholder) for authentication and authorization purposes are as follows:"

The sentence is missing identifier for the card itself.
 
**Suggested Change**: "The two types of identifiers that serve as 1) identification (of the person), and 2) identification (of the card), for authentication and authorization purposes are as follows:"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by regenscheid** [comment]
Decline.  The ultimate goal is to identify the cardholder.  The card identifiers are intended to indirectly identify the cardholder.
