### ISSUE TITLE
Missing the Person UUID and FASC-N OI/PI values.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#462]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1997-1999
 
**Comment (Include rationale for comment)**: "Examples include the cardholder UUID that may appear in the CHUID or the subject names that may appear in the subjectAltName extension in the PIV authentication certificate."

Missing the Person UUID and FASC-N OI/PI values.
 
**Suggested Change**: "Examples include the cardholder UUID that may appear in the CHUID or the subject names that may appear in the subjectAltName extension in the PIV authentication certificate."

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Discussion should we add their recommendation to include person UUID and FASC-N as examples .  The comment  actually references lines 1987- 1989

**Comment by regenscheid** [comment]
Decline.  SP 800-73 specifies which values are recognized in the FASC-N (which does not include the OI/PI values).  And the cardholder UUID is already referenced as a cardholder identifier.
