### ISSUE TITLE
Contactless Reader Requirements

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#464]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2032-2039
 
**Comment (Include rationale for comment)**: Contactless Reader Requirements
 
**Suggested Change**: Recommend adding "Contactless Readers may conform to Near-Field Communications (NFC) standards."

This will greatly expand usage of Derived PIV in the mobile device market.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend not accepting. To be sure of the security characteristics and to facilitate interoperability, FIPS 201 should cite specific standards. It is my understanding that ISO 14443 already covers the vast majority of NFC devices in use; if that is not the case, it should cite specific standards and not an umbrella term like NFC.

**Comment by regenscheid** [comment]
Decline per above.  As indicated above, Section 4.4.2 already references ISO 14443 and ISO 7816.
