### ISSUE TITLE
Clarify: "...input device SHALL be integrated with the PIV Card reader."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#465]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2046-2047
 
**Comment (Include rationale for comment)**: "When the PIV Card is used with a PIN or OCC data for physical access, the input device SHALL be integrated with the PIV Card reader."

It is not clear what is sought by this statement.  A) the fingerprint reader is an integral part of a reader housing the contact/contactless reader; B) a separate fingerprint reader is cabled to a contact/contactless reader.  Equally true is replace ""fingerprint reader"" with ""PIN pad"".  The market has both environments.  They can be very modular in nature.

 
**Suggested Change**: Clarify the intent, or remove the requirement.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion.

**Comment by regenscheid** [comment]
Accept in principle- We will clarify the intent of the requirement for input devices to be integral to readers.  Add to Paragraph 3, Section 4.4.4.
