### ISSUE TITLE
Is "revoking the PIV card" any different from "invalidating the PIV card"?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#466]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2103-2106
 
**Comment (Include rationale for comment)**: "However, a PIV authentication or card authentication certificate MAY be revoked and subsequently replaced without revoking the PIV Card."

This is confusing.  I think it is trying to say you can revoke a PIV card certificates for an individual, but their Enterprise IDMS (or maybe CMS) record is still in good standing and the individual is still eligible for new PIV/CAK auth certificates or a new PIV card.
 
**Suggested Change**: Is "revoking the PIV card" any different from "invalidating the PIV card"?  This may best be discussing PIV card eligibility at the Enterprise IDMS because that directly affects Derived PIV.

Please clarify.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion.

**Comment by regenscheid** [comment]
Accept in principle- we will review the use of "revocation" in the context of the PIV card itself, as opposed to the certificates.

**Comment by regenscheid** [comment]
Section 2.6: Used in Reissuance example: "Instead, the card issuer revokes the lost card and
706 proceeds to issue a new card as described in Section 2.9.1."

Section 2.9.1:  The old PIV Card SHALL be revoked when the new PIV Card is issued. The revocation process SHALL include the following:

Section 2.9.4: Similar to the situation in which the PIV Card is compromised, normal termination procedures must be in place. The PIV Card SHALL be revoked through the following procedure:

Section 5.2.1:
If the card is revoked, the PIV authentication and card authentication certificates SHALL be revoked in cases where the card cannot be collected and destroyed.

**Comment by regenscheid** [comment]
We reviewed the use of of the term "revoke" in regards to the PIV card itself (as opposed to the certificates).  In all cases, the required procedures are clear.  In particular, the sentenced referenced by this comment is clear by including a forward pointer to Section 2.9.1, which describes the revocation process for reissued cards.
