### ISSUE TITLE
Recommend saying "…in accordance with Department/Agency Certification Practices Statement."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#467]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2130
 
**Comment (Include rationale for comment)**: [No comment]
 
**Suggested Change**: Recommend saying "…in accordance with Department/Agency Certification Practices Statement."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion

**Comment by regenscheid** [comment]
Decline- revocation procedures may be specified multiple places- we don't need to call out any single document.
