### ISSUE TITLE
Recommend: "...SHALL NOT be distributed over the public internet ..."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#468]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2135-2136
 
**Comment (Include rationale for comment)**: "...SHALL NOT be distributed publicly (e.g., via HTTP accessible from the public internet)."

Is really open to interpretation for the intent of the requirement.  Is it OK for a department/agency to publish PIV Auth/Card Auth on a public directory that is only accessible within the department/agency?  If one considers APT, this may be leaking information.
 
**Suggested Change**: Recommend strengthening the language.

"...SHALL NOT be distributed over the public internet nor throughout an agency/department (e.g., via HTTP accessible directory)."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion

**Comment by regenscheid** [comment]
Decline- the proposed text is quite broad, and would preclude legitimate use cases involving certificate directories.
