### ISSUE TITLE
PIV Card Authentication Mechanisms

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#469]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2187
 
**Comment (Include rationale for comment)**: PIV Card Authentication Mechanisms
 
**Suggested Change**: This section is missing the use of Secure Messaging as a valid authentication method.  It is cryptographically secure and provides the Card UUID within the CVC for authorization decisions.  Recommend adding Secure Messaging as an authentication method within FIPS 201-3.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Decline. Section 6.2.3.3 allows Authentication Using Secure Messaging Key (SM-AUTH)
