### ISSUE TITLE
Use of OCC for the CTC to activate the card

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#470]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2196
 
**Comment (Include rationale for comment)**: "...following CTC authentication using a PIN supplied by the cardholder."

Prior language in the standard enables use of OCC for the CTC to activate the card, enabling access to all three biometric modalities for off-card comparison.
 
**Suggested Change**: Recommend "...following CTC authentication using OCC or a PIN supplied by the cardholder."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Same type of comment as #471. See proposed resolution there.
