### ISSUE TITLE
As written, this method does not confirm if the card is revoked.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#472]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2216-2217
 
**Comment (Include rationale for comment)**: As written, this method does not confirm if the card is revoked.
 
**Suggested Change**: Add new bullet:

"The PIV Auth cert is read from the card.  Confirm this certificate is not revoked or expired."

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Correct.  Some Authentication mechanism do not protect against revoked cards and has been taken into accounts.  We highlight capability of the authentication mechanism in the standard.  For BIO/BIO/A, it is highlighted in  lines 2200- 2210.  Line 2208 specifically states:  "does not protect against revoked cards. "


Suggest to note.   This requiring revocation check would also not be backwards-compatible  with install base and readers available on the GSA approved products list.

**Comment by jimfenton** [comment]
A specific change was requested, so it sounds like the proposed resolution should be to not accept.

**Comment by jglosx3** [comment]
Declined: Requiring revocation check would  not be backward-compatible (section 1.3.2) with install base and readers available on the GSA approved products list.
