### ISSUE TITLE
Destruction of a PIV card. 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#474]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Section 2 and 3
 
**Comment (Include rationale for comment)**: Destruction of a PIV card.   Nothing stated about recording the destruction act to the CMS, to support cradle to grave issuance activities.
 
**Suggested Change**: Recommend establishing controls requiring the destruction act/event be reported/recorded as part the issuance activities to maintain accounting of all issuance processes.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Should we records card destruction in PIV enrollment record? cards should be returned to issuer when they expire or subject is no longer eligible for PIV card.

**Comment by hferraio** [comment]
Section 2.9.4 seems the appropriate place to talk about this.

**Comment by regenscheid** [comment]
We could add language recommending this practice to Section 2.9.4.

**Comment by jglosx3** [comment]
Accept in Principle:  Will add updated text to reflect requirement to update CMS with information on card termination and method of termination.
