### ISSUE TITLE
SYM-CAK

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#475]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2316-2340
 
**Comment (Include rationale for comment)**: SYM-CAK
 
**Suggested Change**: SYM-CAK should be deprecated.  See comment to 1789.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Yes, it has been deprecated as noted at line 2327.
