### ISSUE TITLE
Does not discuss interoperability.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#477]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2335-2340
 
**Comment (Include rationale for comment)**: Does not discuss interoperability.
 
**Suggested Change**: Recommend adding a bullet

"Is not cross agency interoperable and generally will not work with PIV cards issued by another agency.

 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Discuss to confirm non-interoperability. Could add this, but one would hope that the deprecation would inhibit new deployments.

**Comment by regenscheid** [comment]
Decline- that is out-of-scope for the characteristic bullets, but is a major part of the reason we are deprecated SYM-CAK in FIPS 201-3.
