### ISSUE TITLE
Introducing PAL is inconsistent with the model offered by SP800-63B.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#478]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2430-2440
 
**Comment (Include rationale for comment)**: Introducing PAL is inconsistent with the model offered by SP800-63B.
 
**Suggested Change**: Recommend only using AAL from SP800-63B in this context.  It maps very well for Physical Access.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend not accepting. Physical access is explicitly out of scope for SP 800-63B, so it is necessary to define something here, even if it looks familiar.

**Comment by regenscheid** [comment]
Decline- The definitions and associated requirements for AALs in SP 800-63B can not be directly applied to physical access.
