### ISSUE TITLE
Why is PAL being introduced?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#479]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2430-2440
 
**Comment (Include rationale for comment)**: Why is PAL being introduced? 800-63 addresses this 
 
**Suggested Change**: See comments to line 2430-2440.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Duplicate of #478
