### ISSUE TITLE
Table 6-1 does not conform with SP800-63 AALs using multi-factor authentication

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#481]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2449-2450
 
**Comment (Include rationale for comment)**: Table 6-1 does not conform with SP800-63 AALs using multi-factor authentication (something you know, something you have, something you are)
 
**Suggested Change**: Industry does not follow the paradigm listed in this table.  Recommend aligning with industry and using multi-factor authentication paradigm defined in SP800-63B.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend not accepting. Table 6-1 deals with physical access and that is explicitly out of scope for SP 800-63B.

**Comment by regenscheid** [comment]
Decline.  The properties and requirements for physical access do not naturally align with logical access control.  The PAL concept is based on the concept of the number of "factors" required to authenticate.  Roughly speaking, PAL1 uses one factor, while PAL3 uses three factors.  We will expand on this in the next revision of SP 800-116.

**Comment by jglosx3** [comment]
We need to re-confirm the decline on this given we have eliminated the PAL concept.   The reason on for declining may need to change.

**Comment by regenscheid** [comment]
Decline. The properties and requirements for physical access do not naturally align with logical access control.  However, the final version of FIPS 201-3 does not define Physical Assurance Levels and instead merely describes the assurance characteristics of the applicable PIV authentication mechanisms for physical access use cases.  Further guidance will be developed in a revision to NIST SP 800-116.
