### ISSUE TITLE
Table 6-2 does not conform with SP800-63 AALs using MFA

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#482]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2460-2461
 
**Comment (Include rationale for comment)**: Table 6-2 does not conform with SP800-63 AALs using multi-factor authentication (something you know, something you have, something you are)
 
**Suggested Change**: Industry does not follow the paradigm listed in this table.  Recommend aligning with industry and using multi-factor authentication paradigm defined in SP800-63B.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend not accepting. Only authentication over a network is in scope for SP 800-63B, and both PKI-CAK (single-factor cryptographic device) and PKI-AUTH (multi-factor cryptographic device) are appropriate for AAL1 and AAL3 respectively.

**Comment by regenscheid** [comment]
Revisit this after addressing #536

**Comment by regenscheid** [comment]
Per #536, we will be revising Table 6-2.

**Comment by jimfenton** [comment]
BIO-A is no longer listed as AAL3 (changed by #642) so this issue is moot.
