### ISSUE TITLE
"The IdP SHALL associate this login with the PIV account of the cardholder and SHALL create an assertion..."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#483]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2472-2474
 
**Comment (Include rationale for comment)**: "The IdP SHALL associate this login with the PIV account of the cardholder and SHALL create an assertion representing the cardholder to be sent to the RP, including attributes of the cardholder stored in the PIV account."
 
**Suggested Change**: See comment on lines 1332-1334.

The IdP is likely not the Enterprise IDMS that issued the credential.  The IdP will have an attribute store associated with an identity.  The PIV cardholder is not "logging in" per se to the IdP, they are authenticating their identity using their PIV card for access to the resource controlled by the RP.

This should be clarified.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept in principle: the text is correct as is because the user is logging in to the IdP to perform its function, which happens to be logging in to a downstream RP. However, this terminology could be aligned better with the rest of the document.

**Comment by jglosx3** [comment]
Accept in Principle - Updated text uses clearer terminology when referring to authentication actions.
