### ISSUE TITLE
Stable Identifier

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#484]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2504-2506
 
**Comment (Include rationale for comment)**: Stable Identifier
 
**Suggested Change**: While it is true an IdP can establish its own unique identifier for a given identity, this may not be to the advantage of the federal enterprise.  A PIV card has both OI/PI from the FASC-N, as well as the Cardholder (Person) UUID.  The Person UUID is uniquely suited to this task, as it spans any issuer, any IdP, and any RP evironment, with no risk of collision.

Recommend adding language about using the PIV Person UUID as a stable identifier within any federation model serving the PIV market.

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, this is the purview of the federation SP. Plus, I'm not convinced it's actually a good idea, given the need/suggestion for per-provider identifiers.

**Comment by jricher** [comment]
Cardholder UUID is not a required element that the IDP can depend on.
