### ISSUE TITLE
Recommend this only refer to the IdP, even though the CSP may be the IdP.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#485]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2509
 
**Comment (Include rationale for comment)**: "...tasked to the credential issuer/IdP."
 
**Suggested Change**: Recommend this only refer to the IdP, even though the CSP may be the IdP.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Current language seems fine, but this is more of a federation issue so retagging. Attn: @jricher

**Comment by jglosx3** [comment]
Accept in Principle.  We will updated text to fundtion of he process allocated to IdP.
