### ISSUE TITLE
PAL not consistent with SP800-63B.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#486]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 3063-3064
 
**Comment (Include rationale for comment)**: PAL not consistent with SP800-63B.
 
**Suggested Change**: Recommend delete in favor of AAL from SP800-63B.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Duplicate of #478
