### ISSUE TITLE
Secure Messaging should be added as a new authentication method ...

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#487]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: [none given]
 
**Comment (Include rationale for comment)**: Secure Messaging should be added as a new authentication method for high performance cryptographic single factor.
 
**Suggested Change**: [blank]
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Suggest "noted". See section 6.2.3.3, lines 2304-2315, for details on the SM-AUTH authentication method.
