### ISSUE TITLE
Clarify that 1:1 biometric verification is the generic concept. 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#488]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: [blank]
 
**Comment (Include rationale for comment)**: Clarify that 1:1 biometric verification is the generic concept.  This would enable defining Fingerprint, Facial, and Iris, as the modalities, no matter if on or off card, that comply with the requirement for biometric verification.
 
**Suggested Change**: [blank]
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Need to discuss. Generic concept for what?

**Comment by hferraio** [comment]
Noted. 1:1 biometric comparison in the various modality is well covered in the standard.
