### ISSUE TITLE
Recommend consideration of Secure Identity data exchange from the Secure Identity Alliance

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#489]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: [blank]
 
**Comment (Include rationale for comment)**: 800-156 defines the Enrollment Record and a structure used to transfer enrollment information between agencies.  Recommend consideration of Secure Identity data exchange from the Secure Identity Alliance (https://secureidentityalliance.org/). This would extend SP800-156 which would include credential information, attribute information, and related.  This expansion would greatly improve vendor uptake, and inter-agency transfers and reciprocity.
 
**Suggested Change**: [blank]
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Similar to #245.  Suggest to decline as it  is out of scope. Any desired harmonization that department/agencies would want to undertake should be a addressed in SP 800-156 revision.

**Comment by regenscheid** [comment]
Decline.  Out of scope for FIPS 201, but could reconsider for SP 800-156.
