### ISSUE TITLE
Promote ... discussion about Person Identifiers for credentialing, authentication, and in particular, federation.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#490]
### All Fields Are Required
**Organization Name (N/A, if individual)**: DHS

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: [blank]
 
**Comment (Include rationale for comment)**: Promote and sponsor a discussion about Person Identifiers for credentialing, authentication, and in particular, federation.  Specifically FASC-N OI/PI, Cardholder (Person) UUID, attributes about what type of person (contractor, foreign national, employee, state/local, federal, etc.)
 
**Suggested Change**: [blank]
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion

**Comment by jglosx3** [comment]
Noted.  Discussion proposed is outside the scope of FIPS201 document.  Use of Person identifiers will be addressed in Federation SP.
