### ISSUE TITLE
Footnote note referencing dependencies outlined in Section 6.3 is in order.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#491]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 1 pg 1, LIne 324

**Comment (Include rationale for comment)**: Provide reader with reference to related content within document
 
**Suggested Change**: A footnote note here referencing the dependencies that are outlined in Section 6.3 is in order. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline.

**Comment by jglosx3** [comment]
Decline: Footnote is note appropriate
