### ISSUE TITLE
Add line, "This IDMS interfaces with other Agency Identity and Access Management services ..."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#492]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 1.2 +F5:I19pg 2: Line 364
 
**Comment (Include rationale for comment)**: the assumption here that the Agency IDMS responsible for card issuance is the Agency “operational” Identity Management system is usually not correct.
 
**Suggested Change**: Add line "This IDMS interfaces with other Agency Identity and Access Management services that enable the management of identity information throughout the lifecycle of the Identity."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
related to #516 - but different line #

**Comment by regenscheid** [comment]
Decline.  How agencies organize and implement their architectures is up to individual agencies- the records in the PIV Identity Account may be split across multiple components, but collectively, those components act as an IDMS.
