### ISSUE TITLE
No date specified for use of CHUID authentication 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#493]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 1.3.4 pg 4: Line 420
 
**Comment (Include rationale for comment)**: No date specified for use of CHUID authentication 
 
**Suggested Change**: Specify a specific date after which CHUID authentication will be discontinued.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to note.  This is covered in section 1.3 Effective Date - line 147-151.  It states that deprecated or removed features are effective upon final publication of the supporting document where the feature is further defined. In this case, SP 800-116 revision 2.

**Comment by regenscheid** [comment]
This is also related to #339 on the effective date of FIPS 201-3 in general.  We will clarify when the requirements on new, optional and removed features/mechanisms will go into effect.
