### ISSUE TITLE
None of the other forms of authentication enable VIS as an input.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#494]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 1.3.5 pg: Line 422
 
**Comment (Include rationale for comment)**: None of the other forms of authentication enable VIS as an input.
 
**Suggested Change**: [blank]
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest noting. Since line  line 2353 states that future revision may remove VIS, it is not ideal to highlight VIS further.

**Comment by jglosx3** [comment]
Noted. Line 2353 states that future revision may remove VIS, it is not ideal to highlight VIS further.

**Comment by jglosx3** [comment]
Noted - The current text states that future revisions may remove VIS, it is not ideal to highlight VIS further.
