### ISSUE TITLE
Magnetic stripe deprecation

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#496]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 1.3.4 pg. 4: Line 425
 
**Comment (Include rationale for comment)**: Is the magnetic stripe deprecated or is the encoding of the magnetic stripe with information deprecated?
 
**Suggested Change**: Clarify or give forward reference to where the document clarifies.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Decline.  Lien 425 provides reference to section that deprecates magnetic stripe

**Comment by regenscheid** [comment]
Magnetic stripe is just being referenced as an example. Section 4.1.4.4 is clear that the magnetic stripe is deprecrated.
