### ISSUE TITLE
Rapid electronic authentication

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#497]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.1 pg. 7: para 2: Line 515
 
**Comment (Include rationale for comment)**: Item c. Does the FPKI practice of issuing CRLs every 18 hours and next Update of 48 hours satisfy (c) for rapid electronic authentication?
 
**Suggested Change**: Define "rapid" in this context.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion. #498

**Comment by hferraio** [comment]
This is a direct quote out of  HSPD-12.  It should cover more than PKI-based credentials - apply broadly and is subject to techn. advancement.  Suggest to decline.

**Comment by regenscheid** [comment]
Decline- Section 2.9 in FIPS 201, as well as the FPKI Common Policy Framework, specify the detailed requirements for revocation.
