### ISSUE TITLE
Sec 2.1 List does not address c & d.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#498]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.1 pg. 7, para 2: Line 518

**Comment (Include rationale for comment)**: The list in lines 520 to 546 only relates to a & b. c & d are not addressed.
 
**Suggested Change**: Address c & d or note that list only addresses a & b.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion

**Comment by regenscheid** [comment]
Will clarify that the PIV implementation bullets expand on the control objectives in HSDP-12, but there was not intended to be a strict mapping to control objectives.
