### ISSUE TITLE
Consider adding a Trust Assurance Level (TAL) 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#499]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.2 pg. 8, para 2: Line 550-556
 
**Comment (Include rationale for comment)**: How is it expected that the variations in the investigative requirement as required by the designation of position guidance be reflected in interagency federation protocols? 
 
**Suggested Change**: Consider adding a Trust Assurance Level (TAL) to accommodate the variation. TAL may be crucial element in Federation. Alternatively, eliminate this discussion in favor of specifying just Tier 1 as minimum trust for PIV  holder.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline. This is out of scope for this document and essential aspects of this request are covered in 7.2.
