### ISSUE TITLE
Clarify what assumptions a relying party may assume in federations

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#500]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.2 pg. 8, para 3: Line 557-559
 
**Comment (Include rationale for comment)**: Since minimum requirements for PIV investigations is Tier 1 in federation assurance scenarios, should the relying party only consider that the individual asserting a FAL has been adjudicated?
 
**Suggested Change**: Clarify what assumptions a relying party may assume in federations
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline. This seems to be out of scope for this document as it pertains to trust of attributes.
