### ISSUE TITLE
PIV credentialing investigative and adjudicative requirements

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#501]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: 2.2 pg. 9, last para: Line 569
 
**Comment (Include rationale for comment)**: If PIV credentialing investigative and adjudicative requirements are determined by Executive Agents what is the common expectations that can be expected without having access to the individual expectations.
 
**Suggested Change**: Clarify. See previous two comments.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, see also #500 and #499

**Comment by regenscheid** [comment]
Suggest decline.  The referenced text is intended to serve as a general warning that PIV issuers must stay up-to-date on policy guidance provided by OPM and OMB.
