### ISSUE TITLE
Are Departments and agencies synonymous with "organization"?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#502]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec.   2.7, Pg. 13, Para. 1: Line 705-711
 
**Comment (Include rationale for comment)**: Is Departments and agencies synonymous with "organization". What is the process relationship of 800-63A or 800-79 or both. 
 
**Suggested Change**: If the expectation is that this meets both, state both on the same line.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept.

**Comment by jricher** [comment]
Both are meant here. Will also check other portions of the document for similar issues.

**Comment by jglosx3** [comment]
Accept in Principle. Will update text to indicate the department or agency are to be inferred in relevant section of the document.

**Comment by jglosx3** [comment]
Accept in Principle - Text updates indicate the department or agency are to be inferred in relevant section of the document.
