### ISSUE TITLE
If need for evaluation of trust, there should be a topic on that subject

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#504]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 2.7, Pg. 13, Para. 3: Line 712
 
**Comment (Include rationale for comment)**: Identity Proofing has no requirements for investigations. They are related but orthogonal. If there deems to be a need for evaluation of trust there should be a topic on that subject, the rationale for it and the measurement implications of that in the same manner that Identity Assurance is different than Federation Assurance, Trust Assurance (my words here) should be different than Identity Assurance. The attributes regarding the asserted trust could then be sent along with assertions about Identity, Authentication or Federation such that a relying party would be able to discern the entire realm of assurances that are being conveyed on part of the issuing party.
 
**Suggested Change**: If there is a need for evaluation of trust, there should be a topic on that subject, the rationale for it and the measurement implications of that in the same manner that Identity Assurance is different than Federation Assurance, "Trust Assurance" should be different than Identity Assurance. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Identity Proofing and investigation are tightly coupled (see OPM policy)  Background investigation is a pre-requisite for PIV eligibility as it requires a  1:1 biometric match to the fingerprints for background investigation during identity proofing - to ensure who is identity proof is the person with the fingerprint check (no substitution occurs).

Conveying level of trust  in assertions, on the other hand, is a topic that we might covered in the PIV Federation Special Publication as needed.

**Comment by regenscheid** [comment]
Decline.  The topic of investigative requirements is the purview of OPM and OMB, not NIST.  The investigation requirements, however, are a prerequisite to PIV issuance, which is why it is mentioned here.
