### ISSUE TITLE
"Trained staff" is too ambiguous for a standards document. 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#505]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 2.7, Pg. 13, Para. 6: Line 719-720
 
**Comment (Include rationale for comment)**: "Trained staff" is too ambiguous for a standards document. 
 
**Suggested Change**: State precisely how one is to be trained or reference the Special Publication that specifies a training process practice statement that covers these other documents.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
discuss - SP 800-79 would be the place to add more details - although more in the context of describing capability, rather than hard requirements.

**Comment by regenscheid** [comment]
Decline. SP 800-79 will provide additional details.
