### ISSUE TITLE
 Specify what is meant by term, "bound", and how that is evidenced.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#506]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 2.7, Pg. 13, Para. 6: Line 721-723
 
**Comment (Include rationale for comment)**: In what manner is the term “bound” used here?
 
**Suggested Change**:  Specify what is meant and how that is evidenced.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to clarify by adding a footnote of 800-63-A definition (if it exists).

**Comment by regenscheid** [comment]
Will clarify.  Split this sentence into two.  Replace "bound" with language indicating evidence documents shall correspond to the applicant.
