### ISSUE TITLE
 "… SHALL NOT be expired or cancelled.” 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#507]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 2.7, Pg. 13, Para. 6: Line 721-723
 
**Comment (Include rationale for comment)**: "… SHALL NOT be expired or cancelled.”
 
**Suggested Change**: Replace with “SHALL neither be used past their displayed expiration date nor be marked as “cancelled”.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline.

**Comment by jricher** [comment]
Decline, existing text is more broad than proposed text.
