### ISSUE TITLE
Allow use of IAL3 or modify 800-63 to allow the use of Trust (Tier 1) to compensate

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#508]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 2.7, Pg. 15  last Para.: Line 760
 
**Comment (Include rationale for comment)**: The introduction of a “compensating control” via a background investigation conflates the term IAL with another vector (background investigation) that is not referenced in that Special Publication. The source publication, SP 800-63, should be the document that indicates how compensating controls can be applied in order to elevate lack of evidence from less than IAL3 to IAL3. It is NOT the case that ONLY PIV card issuance will have this delta and unless there is a way to convey the existence of said compensating control (say by the addition of a “trust” assurance level attribute), the replying party cannot reasonably be expected to accept that an IAL3 is truly as the guidance states.
 
**Suggested Change**: Allow use of IAL3 (as defined in SP 800-63) or modify 800-63 to allow the use of Trust (Tier 1) to compensate .
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline.  PIV id proofing is a specific profile of SP 800-63 that also has additional requirements (such as background investigation) that is not applicable in general for SP 800-63.  

Note: SP 800-63 allows for compensating controls, which  FIPS 201-3 applies it in its profile as described in line 760.

**Comment by regenscheid** [comment]
Decline.  Per the discussions at the Business Requirements Meeting, we believe the current issuance process for PIV provides a sufficient level of assurance. We believe the on-boarding process and the background investigation mitigate the risks from not meeting all of the documentary evidence requirements from-63A.
