### ISSUE TITLE
Redundant statement - need to clarify

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#509]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 2.7, Pg. 15, Para. 2: Line 768
 
**Comment (Include rationale for comment)**: Is this an elaboration on the SHALL statement of line 707-709 and 710-711 or is this a redundant statement?
 
**Suggested Change**: Clarify
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, this seems to be a separate requirement.
