### ISSUE TITLE
Make language  more definitive

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#510]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.3 Line 581/582
 
**Comment (Include rationale for comment)**: Make language  more definitive
 
**Suggested Change**: "This collection is not necessary for applicants who have a completed
 and favorably adjudicated Tier 1 or higher federal background 
investigation on record that can be located and biometrically matched to original referenced biometric used to conduct this investigation."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, this seems to be requiring an additional step.

**Comment by jricher** [comment]
Requirement already in Section 2.8.2 (line 875 in current document).
