### ISSUE TITLE
Identity Proofing "Registration": Remove term or clarify

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#511]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 2.7, Pg. 15, Para. 3: Line 772
 
**Comment (Include rationale for comment)**: Identity Proofing requirements are specified in NIST SP 800-63-3. The meaning of the term “registration” is unclear in this section where Identity Proofing is the sole activity occurring.
 
**Suggested Change**: Remove term or clarify
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
suggest to decline as title and content is of the section is "Identity Proofing and Registration".  Pointing to SP 800-63A instead is a not possible PIV ID proofing and registration is a tailored process (line 706) of SP 800-63A.

**Comment by hferraio** [comment]
Declined. The term is defined in glossary.
