### ISSUE TITLE
Make language more definitive

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#512]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.4 Line 593-595
 
**Comment (Include rationale for comment)**: Make language more definitive
 
**Suggested Change**: Two fingerprints for on-card comparison (OCC). These fingerprints MAY be taken from the full set of fingerprints collected in Section 2.3 and SHOULD be imaged from fingers. The fingerprint templates stored on the PIV for off-card one-to-one comparison can not be used for on-card comparison.   Clarify that two different fingers are required. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline.

**Comment by jricher** [comment]
Decline, SP800-76 Section 5.4 defines requirements for fingerprints used.
