### ISSUE TITLE
Conditions when AAL2 is appropriate are vague.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#513]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 2.10.1, Pg. 24, Para. 2: Line 1106
 
**Comment (Include rationale for comment)**: Conditions when AAL2 is appropriate are vague.
 
**Suggested Change**: Recommend adding more elaboration regarding “depending on the security characteristics of the authenticator."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend accepting. Although we cite SP 800-63B in the previous paragraph, it's in a somewhat different context and should probably be cited here for AAL requirements.

**Comment by regenscheid** [comment]
@hferraio to follow-up with CISA to find out if the merged changes addressed the comment.

**Comment by hferraio** [comment]
CISA said that the merged changes address the comment. We can close this one.

**Comment by jglosx3** [comment]
Accept in Principle.  Text will be updated to specify use of Derived PIV credentials that meet AAL2 or AAL3 requirements.
