### ISSUE TITLE
Further technical details in upcoming SP 800 documentation

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#514]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.5 Line 631-633
 
**Comment (Include rationale for comment)**: "With latest NIST facial recognition test surpassing  both Iris and finger, it should be an alternate not secondary"

**Suggested Change**: The electronic facial image is a alternate means of authentication during operator-attended PIV issuance and maintenance processes.  Further technical details in upcoming SP 800 documentation

---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
accept in principle

**Comment by regenscheid** [comment]
Tangentially related- in line 836, we specify that fingerprints are preferred over other biometrics.  While making these changes, we could consider changing that line to remove "if unavailable."
