### ISSUE TITLE
Clarify how PIV Card IDMS integrates with FICAM and Agency IDMSs.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#516]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 3, Pg. 27, Para. 1: Line 1186
 
**Comment (Include rationale for comment)**: Even while informative it should not be misleading. The Federal ICAM office has specified a Identity Credential and Access Management Architecture in which the PIV Card issuance, validation, and card lifecycle management can exist. Those ICAM systems are dependent on integration with the PIV Card IDMS system but the PIV Card IDMS is not sufficient for performing Federal ICAM service functions. In no cases has this commenter seen that the PIV IDMS interacts directly in the issuance of sub-accounts that are dependent on the PIV card, nor the authorizations required to use the PIV card for logical or physical access control.
 
**Suggested Change**: Clarify how PIV Card IDMS integrates with FICAM and Agency IDMSs.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion

**Comment by regenscheid** [comment]
We did not intend to specify a new IDMS- merely to acknowledge that the card management and issuance systems are part of the agency's broader identity management system.  We will look for places to clarify these core concepts.

**Comment by jglosx3** [comment]
Accept in Principle - The intent was not  to specify a new IDMS- merely to acknowledge that the card management and issuance systems are part of the agency's broader identity management system.  The updates to the text clarify these core concepts.
