### ISSUE TITLE
Diagram neglects to show interposing relying system of Agency Identity and Access Management systems...

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#518]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. Figure 3-1, Pg. 28: Line 1220
 
**Comment (Include rationale for comment)**: This diagram neglects to show the interposing relying system of the Agency Identity and Access Management systems which allows the PIV card to be provisioned for use on related accounts and that manages the permissions and entitlements that the account holder has upon which the PIV card or the derived PIV credential can be utilized. The PIV Relying Subsystem is substantial, and includes important not represented by the showing of the endpoints alone. Each of these PIV Relying Subsystem endpoints depend on an Agency Identity and Access Management system in order to properly maintain the accounts associated with each PIV card holder and the entitlements and privileges that are required to properly operate an Agency ICAM environment. This reliance on the ICAM architecture to carry out the mission assigned to the PIV and derived PIV responsibility needs to be clearly shown here. 
 
**Suggested Change**: Show an Agency Identity, Credential and Access Management system as a supersystem on the PIV-related systems, the PIV IDMS and the PIV Front-end Subsystems being directly connected to that system. The section that shows Logical and Physical Access is in a superposition to the PIV system as there are other means of performing both logical and physical access that do not involve the PIV system and this should be reflected in the diagram where these components are part of the larger ICAM services but that the PIV card system supports with those unique credentials
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, this seems to be asking for more detail and breadth than the diagram is meant to convey.
