### ISSUE TITLE
Clarify that account is NOT the sole account in the Agency environment.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#522]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 3.1.2, page 30, Para. 1: Line 1275
 
**Comment (Include rationale for comment)**: This statement presumes that the enterprise IDMS that is responsible for issuing a created PIV Card and the Agency Identity and Access Management systems which allows the PIV card to be provisioned for use on related accounts and that manages the permissions and entitlements that the account holder has upon which the PIV card or the derived PIV credential are one in the same. It is true that the PIV account is maintained throughout the cardholder’s employment but it is not true that that account is the sole account in the Agency environment. 
 
**Suggested Change**: Clarify that account is NOT the sole account in the Agency environment.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
related to (and same resolution as) #341. See also #353  - note: comment is for different location (line number) than 341.

**Comment by hferraio** [comment]
Declined for reasons mentioned above.

**Comment by regenscheid** [comment]
See issue #613 - will clarify the PIV Identity Account term.

**Comment by jglosx3** [comment]
Accept in Principle - The document updates clarify the PIV Identity Account term.
