### ISSUE TITLE
Expand statement to indicate the dependency on Agency Identity and Access Management system

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#527]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 3.1.3, page 30, Para. 2: Line 1294
 
**Comment (Include rationale for comment)**: This statement needs to be expanded in order to indicate the dependency on that Agency Identity and Access Management system to be able to determine the proper use of the PIV card for Logical and Physical Access controls which are the only entities that can provide proper authorization mechanisms. The PIV system is a subsystem of the ICAM system, and the PIV is utilized within that system to provide high-assurance identity and authentication, not the other way around.
 
**Suggested Change**: Expand statement.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, this is not the relationship the diagram is trying to explain.

**Comment by jricher** [comment]
Decline, this section describes systems from the perspective of the PIV components. There may be many other components in an overall deployment.
