### ISSUE TITLE
Recommend providing a reference to the Federal PKI 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#530]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 5.1, page 66, Para. 1: Line 2068
 
**Comment (Include rationale for comment)**: Vague reference to Common Policy 
 
**Suggested Change**: Recommend providing a reference to the Federal PKI and adding it to the glossary.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Accept in principle: Line 2069 provides reference to Federal PKI policy authority [PROF]. We may want to clarify sentence on 2068.  The Federal PKI is also referenced again under [COMMON]
