### ISSUE TITLE
Include compensating controls.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#533]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 6.1, Para. 1: Line 2167-2168
 
**Comment (Include rationale for comment)**: Earlier you stated that the PIV did IDP requirements did not necessarily meet those of SP 800-63A but that you were utilizing compensating controls in the form of the background checks to achieve IAL3. This should be explicit here as it is VERY important in federated exchanges in that the relying party will need to understand that a compensating control is in place and not the normative guidance.
 
**Suggested Change**: Include compensating controls.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
This is really an enrollment issue, so retagging.

**Comment by jglosx3** [comment]
Accept in Principle. A footnote was added to describe how compensating controls (in the form of federal background investigations) are used to achieve IAL3.
