### ISSUE TITLE
Re: BIO-A at AAL3 - indicate that this is a supervised operation, or remove.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#536]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Table 6-2, page 79: Line 2460
 
**Comment (Include rationale for comment)**: Re: BIO-A at AAL3. Since there is no way for the validation infrastructure to verify that this is a supervised event this would only be done in portions if the PIV lifecycle (issuance or reissuance), where, by policy, one could assume supervision was available because it is specified.
 
**Suggested Change**: Recommend removing or providing an asterisk and footnote to indicate that this is a supervised operation. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Assigning Jim as Table 6-2 relates to PIV Authentication

**Comment by jimfenton** [comment]
Recommend not accepting. There is no requirement that authentication at AAL3 be supervised, unlike identity proofing at IAL3.

**Comment by regenscheid** [comment]
Further discussion is needed to analyze both BIO and BIO-A against the requirements in SP 800-63B.

**Comment by regenscheid** [comment]
We will need to revise Table 6-2 after analyzing BIO and BIO-A against the requirements for the authenticator assurance levels specified in SP 800-63B.

**Comment by jglosx3** [comment]
Addressed by PR #642
