### ISSUE TITLE
Define: “Local Workstation Environment” and “Remote/Network System Environment”

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#537]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Table 6-2, page 79: Line 2460
 
**Comment (Include rationale for comment)**: The terms “Local Workstation Environment” and “Remote/Network System Environment” need definition. PKI is an inherently “network” infrastructure. It is not possible for the Local Workstation to perform the certificate path validation specified in RFC 5280 without being able to utilize a network. This then makes the workstation a network device and not a local workstation. This then reduces the only valid AAL3 authentication to OCC-AUTH for local workstation, all the rest are network authentications.
 
**Suggested Change**: Define terms “Local Workstation Environment” and “Remote/Network System Environment.”
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Suggest accepting in principle. Remote/network should be expressed in the same terms as 800-63-3 section 2, "digital authentication of subjects to federal systems over a network". The issue is whether the subject is connected to the thing they're authenticating to over a network, not whether there is a network involved in the authentication.

**Comment by regenscheid** [comment]
Consider renaming these to "local authentication" and "remote" or "network" authentication.

**Comment by jglosx3** [comment]
Accept in Principle - Table 6.2 has been revised with column headings updated
