### ISSUE TITLE
Delete AAL3 PKI-AUTH entry in local WS column.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#538]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Table 6-2, page 79: Line 2460
 
**Comment (Include rationale for comment)**: Re: Remote/Network System Environment AAL3 PKI-AUTH.  This is the only valid category for PKI-AUTH. This Authentication is a point in time and all subsequent uses on the network are by a derivative assertion form (see Federation). For instance, once an individual authenticates with the PIV card there is generally a network assertion provided upon which all subsequent activity is performed. One is not forced to “reauthenticate” at every interaction. To do so would be a severe barrier to operations.
 
**Suggested Change**: Delete AAL3 PKI-AUTH entry in local WS column.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The act of authenticating to a local workstation is logging into or unlocking that workstation, not every interaction with it. As with the session secret used by an authenticated session over a network, the workstation keeps state information that determines whether it is logged in/unlocked. This shouldn't interfere with the use of PKI-AUTH. Recommend not accepting comment.

**Comment by regenscheid** [comment]
Decline.

**Comment by jglosx3** [comment]
Decline - The act of authenticating to a local workstation is logging into or unlocking that workstation, not every interaction with it. As with the session secret used by an authenticated session over a network, the workstation keeps state information that determines whether it is logged in/unlocked. This shouldn't interfere with the use of PKI-AUTH.
