### ISSUE TITLE
Section severely understates importance of assertions in the operations of computing systems.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#539]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 7, page 80, Para. 2: Line 2464
 
**Comment (Include rationale for comment)**: This section severely understates the importance of assertions in the operations of computing systems. After the initial authentication (which could well involve PIV) virtually all interactions are performed through some means of assertion (either a hash function of the authenticator or a device or system-issued token) that represents the person that performed the authentication. 
 
**Suggested Change**: Recommend providing guidance on minimum security requirements for the assertion in addition to those of 800-63-3 (base and C). For example, the assertion should include attributes that make clear to the RP that the authentication was derived from a PIV authentication and who performed the authentication and when. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
The term _assertion_ is being used much more narrowly than in some prior publications, that for example considered browser cookies to be assertions. Assertions are now targeted, signed data that are used when conveying authentication information from an identity provider to a relying party in a federated situation.

800-63B Section 7.1 contains requirements on session bindings that apply to FIPS 201 as well. Absent clear definition of what should be added, these are considered sufficient. Suggest "noted".

**Comment by regenscheid** [comment]
Decline.  More information on federation will be covered by a new special publication.
