### ISSUE TITLE
Describe additional assertion contents needed beyond that required in 800-63-3 ...

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#540]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Sec. 7.1, page 80, first sentence: Line 2469
 
**Comment (Include rationale for comment)**: When discussing federation protocols and the manner in which a PIV authentication can be transition to a federation assurance needs to be described (protocol transition). PIV authentication is one protocol, likely that will be transitioned into a assertion not generated by a user but generated by a system that acts on behalf of the user. This is commonly described as a delegation of authority where the system becomes the authority on behalf of the user and generates the assertion (constrained delegation). Use a diagram. It should be noted that the federation protocols are the PREDOMINATE mechanism upon which computing systems operate within a network, not as some simple aside.

Consideration should be given to whether the resulting assertion should include information beyond that required in 800-63-3 (and C supplement) to inform the RP that the assertion is founded on a recent, prior PIV authentication. The information would include the identification of PIV (and holder) and the entity that performed that authentication, and the date and time of the authentication. Note that Line 2601 states that "Status of the investigation can be communicated as needed using federation protocols.”
 
**Suggested Change**: When discussing federation protocols and the manner in which a PIV authentication can be transition to a federation, assurance needs to be described. Describe any additional assertion contents needed beyond that required in 800-63-3 (and C supplement) to inform the RP that the assertion is founded on a recent, prior PIV authentication.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline, this is the purview of a federation-focused SP. Diagram 3-3 describes the process mentioned here.
