### ISSUE TITLE
Single Sign-on (SSO): Add “Ease of use"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#541]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 2495
 
**Comment (Include rationale for comment)**: Federation protocols often support Single Sign-on (SSO) that allows a user to operate on a network without having to reauthenticate with every new action that a user takes. This frees the user from continuously entering a PIN and yet still securely perform their assigned work functions.
 
**Suggested Change**: Add “Ease of use"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest accept in principle to add usability benefits.
