### ISSUE TITLE
Additional explanation/description of Derived PIV Credential

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#542]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Glossary, p 91: Line 2738
 
**Comment (Include rationale for comment)**: Additional explanation/description of Derived PIV Credential
 
**Suggested Change**: Derived PIV Credential. Explain that a Derived PIV Credential has many of the cryptographic characteristics of the PIV Credential and inherits the Identity Proofing of the PIV Credential.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend not accepting. This is in the glossary, and it's not appropriate to include a detailed description here.
