### ISSUE TITLE
FICAM missing

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#543]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Glossary, p 91: Line 2746
 
**Comment (Include rationale for comment)**: FICAM missing
 
**Suggested Change**: Add description “Federal Identity, Credentials and Access Management (FICAM)” as it is referenced as an abbreviation.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Assigning to Hildy, Andy, and Greg as comment mentions both Enrollment and Biometric.

**Comment by hferraio** [comment]
I am fine with including FICAM: How about: 

The Federal Identity, Credential and Access Management (FICAM) initiative is an effort of the Federal Chief Information Officers (CIO) Council to consolidate all government-wide identity, credential, and access management activities.

**Comment by regenscheid** [comment]
FICAM is listed in Appendix C.2. Suggest decline.
