### ISSUE TITLE
Add PIV Credential and explain its unique characteristics as a “credential”

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#544]
### All Fields Are Required
**Organization Name (N/A, if individual)**: CISA

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Glossary, p 95: Line 2865
 
**Comment (Include rationale for comment)**: PIV credential not included
 
**Suggested Change**: Add “Personal Identity Verification (PIV) Credential” and explain its unique characteristics as a “credential”
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
recommend accept

**Comment by regenscheid** [comment]
Note that Credential and Derived PIV Credential are defined terms, but not PIV Credential.
