### ISSUE TITLE
Section 2.7.1 of the FIPS 201-3 draft is both redundant and discordant in specifying operational parameters ...

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#545]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, ALL Line 789-812
 
**Comment (Include rationale for comment)**: We suggest that section 2.7.1 of the FIPS 201-3 draft is both redundant and discordant in specifying operational parameters (e.g., see the precedent delineation of proofing requirements and guidance (i.e., local, remote, IALs, etc.) already defined in the Special Pubs Digital Identity Guidelines (NIST SP 800-63A, 800-63-3, et. al)  thereby obviating the inclusion in FIPS 201-3)
 
**Suggested Change**: The use of SRIP and requirements for SRIP SHALL adhere to the guidelines and requirements set forth in SP 800-63-3 and SP 800-63A for Supervised Remote _in-Person Proofing.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Closing this issue as it is represented in #580.
