### ISSUE TITLE
Supervised Remote In-Person Proofing SHALL meet the requirements and criteria in NIST SP 800-63A.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#546]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, para. 4 Line 795-819
 
**Comment (Include rationale for comment)**: SRIP is simply a special use case (remote operator v. local operator) of the already established IAL3 In-Person Identity Proofing as meticulously defined in SP 800 63-3 and SP 800-63A (5.3.3.2) Supervised Remote In-Person Proofing, wherein all informative and normative compliance specifications are detailed.
 
**Suggested Change**: Supervised Remote In-Person Proofing SHALL meet the requirements and criteria in NIST SP 800-63A.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Closing this issue as it is represented in #546.
