### ISSUE TITLE
Process non-specified, implicit attribution to 800-63 undefined

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#547]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, para. 1 Line 779
 
**Comment (Include rationale for comment)**: Process non-specified, implicit attribution to 800-63 undefined
 
**Suggested Change**: …MAY use the Supervised Remote In-Person Proofing process per the guidelines specified in NIST SP 800-63A for the issuance of PIV Cards.    Suggest creating a high-level section that combines items in Sect 2.7.1 line 779 -819  and reference SP 800- 63 and 63A for specific details.  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline but add a general reference to SP 800-63 (there is non currently) stating that the PIV SIRP is a tailored approach to SP 800-63 and that specific control need to be in place to satisfy HSPD-12 control objectives.

**Comment by hferraio** [comment]
decline for reasons above.
