### ISSUE TITLE
"...issuer-controlled station, ..." Why should this not be extended to proofing? 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#548]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, para. 1 Line 780/781
 
**Comment (Include rationale for comment)**: "...issuer-controlled station, remote location, trained operator at a central location" - SP 800-63-3/2.4 allows for CSP's to be componentized and comprised of multiple independently-operated and owned business entities.  Why should this not be extended to proofing?  Should also align with language in 2.7.1 line 788.
 
**Suggested Change**: …a station in a controlled-access environment that is connected to a remote location for remote operation by a trained trusted-provider.  The issuer may subscribe to or contract independently for trained operator services provided they are compliant with the NIST SP 800-63A specifications and guidance for SRIP.  See comment on line 25
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
comment in line 25 == issue [549](https://github.com/usnistgov/FIPS201/issues/549).  To discuss.  "A third party"  as a possibility is mentioned just a few lines down at line 788.

**Comment by regenscheid** [comment]
This is similar to issue #559. We will clarify that third-parties may act on behalf of the issuer.
