### ISSUE TITLE
"..goal..is to permit identity proofing in remote locations where it is not practical for them to travel.."

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#549]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, para. 1 Line 781-783
 
**Comment (Include rationale for comment)**:  "..goal..is to permit identity proofing in remote locations where it is not practical for them to travel.."

**Suggested Change**: [blank]
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
this comment is referenced in comment [548] (https://github.com/usnistgov/FIPS201/issues/548)

**Comment by jglosx3** [comment]
Duplicate of issue #598
