### ISSUE TITLE
Should match verbiage from NIST SP 800-63A 5.3.3.2

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#550]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, para. 2 Line 786
 
**Comment (Include rationale for comment)**: Should match verbiage from NIST SP 800-63A 5.3.3.2
 
**Suggested Change**: …to achieve comparable levels of confidence and security to in-person events." The draft attribution of "closely duplicate" is superfluous and erroneous as the use of SRIP technology can enhance and improve standard in-person proofing practices.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest do decline. SP 800-63A 5.3.3.2 does not use language such as "enhance" or "improve" in person proofing. The current text in FIPS 201 'as is' is better aligned.

**Comment by regenscheid** [comment]
Decline per above. The goal of SRIP is to provide an equivalent level of assurance as the existing in-person proces.
