### ISSUE TITLE
Obviated by delineated requirements specified in NIST SP 800-63A 5.3.3.2

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#551]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, para. 3 Line 789-794
 
**Comment (Include rationale for comment)**: Obviated by delineated requirements specified in NIST SP 800-63A 5.3.3.2
 
**Suggested Change**: Contend that the draft content be deprecated as it is superseded by NIST SP 800-63A 5.3.3 describing attributes exceeding the confidence and security attained by local operators/staff. Remove from FIPS 201-3.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion

**Comment by hferraio** [comment]
Closing the issue as it is represented in #580.
