### ISSUE TITLE
If the intent is security of persons/objects, needs clarification.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#553]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, para 4 & footnote 9 Line 797
 
**Comment (Include rationale for comment)**: The introduction of draft statements requiring monitoring by staff at the station location are antithesis to the benefits and intent of SRIP
 
**Suggested Change**: If the intent is security of persons/objects, the clarification must be made to differentiate from required proofing resources (i.e., trained operators).  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion. #560 #557 #556 #555 #554

**Comment by jricher** [comment]
duplicate of #580
