### ISSUE TITLE
What is meant by "monitored" and "staff" and for what purpose?  

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#554]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, para 4 & footnote 9 Line 796/797 & footnote 9
 
**Comment (Include rationale for comment)**: The introduction of draft statements requiring monitoring by staff at the station location are antithesis to the benefits and intent of SRIP
 
**Suggested Change**: What is meant by "monitored" and "staff" and for what purpose?  Contend that the draft content be deprecated as it is superseded by NIST SP 800-63A 5.3.3.2 describing attributes exceeding the confidence and security attained by local operators/staff.  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion #560 #557 #556 #555

**Comment by hferraio** [comment]
Suggest to close this issue as it is covered under issue 580](https://github.com/usnistgov/FIPS201/issues/580) .

**Comment by hferraio** [comment]
Closing issue as it is represented in issue #580.
