### ISSUE TITLE
Excludes requirements for physical security and integrity

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#555]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, para 4 & footnote 9 Line 796/797 & footnote 9
 
**Comment (Include rationale for comment)**: Excludes requirements for physical security and integrity
 
**Suggested Change**: Add "Shall employ physical tamper detection and resistance features appropriate for the environment in which it is located. " Matching the requirements in SP 800-63A.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion #560 #557 #556

**Comment by regenscheid** [comment]
We did intend that there tamper resistance features appropriate to the environment would be used. There is some existing text that indicates this (line 792), but we could try to add clarifying text.

**Comment by DTemo** [comment]
- ensuring that the physical integrity of the station (e.g., door locks, restricted access) and its sensor devices (i.e., sensor devices are an integrated component of the workstation or secured in a protective case or locked box} is maintained at all times to protect against tampering, removal, or replacement;
