### ISSUE TITLE
SRIP is to be completed in complete alignment with 800-63A specifications/practices for SRIP. 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#556]
### All Fields Are Required
**Organization Name (N/A, if individual)**: 2 - Industry

**Organization Type (see below for codes)**: 2.7.1, para 4 Line 798/799
 
**Reference (Include section/paragraph or pdf line number)**: SRIP is to be completed in complete alignment with 800-63A specifications/practices for SRIP.  By explicitly stating rules within FIPS-201-3, this runs high risk of diverging from the authority and preferred specification of 800-63A for SRIP.
 
**Comment (Include rationale for comment)**: Strike as not applicable.  This level of specification is not needed at the superior document level.
 
**Suggested Change**: 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion #560 #557

**Comment by jglosx3** [comment]
Similar to #557

Commenter suggest Supervised Remoted identity  proofing should only be specified in 800-63A, Recommend rejecting.  focus of FIPS201-3 I to describe SPIP in context of PIV card enrollment

**Comment by hferraio** [comment]
Closing this issue as it is represented in issue #580.
