### ISSUE TITLE
Specification is not needed … as full specification exists in 800-63A.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#557]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, para 4 & footnote 9 Line 796/797 & footnote 9
 
**Comment (Include rationale for comment)**: Not required by 800-63A; nor is it warranted as long as security and tamper detection is implemented 
 
**Suggested Change**: Strike as not applicable. Specification is not needed at the superior document level as full specification exists in 800-63A.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion. See also #560

**Comment by currydm** [comment]
Propose team discussion

**Comment by hferraio** [comment]
Closing this issue as it is represented in issue #580
