### ISSUE TITLE
Language implies a single session. Different from a segmented process.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#558]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1,  para 4 Line 798-799
 
**Comment (Include rationale for comment)**: Contrary to the notion of segmented enrollments
 
**Suggested Change**: Language implies a single session. This is different from a segmented process. Need clarification of the language. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Discuss - whether single or multi session, each session needs to be observed in its entirety.  We  could write "entire session/sessions", to clarify.

**Comment by regenscheid** [comment]
Decline.  We believe the language is clear that "session" does not imply that a single session needs to cover the whole proofing process.
