### ISSUE TITLE
The language of proofing for a PIV identity is too restrictively focused on the issuer.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#559]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, all Line 778-819
 
**Comment (Include rationale for comment)**: The language of proofing for a PIV identity is too restrictively focused on the issuer. The PIV program itself is built for federation, upon a common chain of trust for users issued PIV Identity. Proofing processes should not be considered an integral, mandatory role of the issuer. This role can optionally be fulfilled by a trusted 3rd party 
 
**Suggested Change**: The language of proofing for a PIV identity is too restrictively focused on the issuer. The PIV program itself is built for federation, upon a common chain of trust for users issued PIV Identity. Proofing processes should not be considered an integral, mandatory role of the issuer. This role can optionally be fulfilled by a trusted 3rd party   See comment above.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
May want to incorporate the clarifications we have in SP 800-79 (or reference it).  In SP 800-79, we state: "issuer" processes being:
central, geographically dispersed or outsourced in varying degrees to another organization or service provider.   Maybe add it to definition in line 2812 (Issuer definition).
