### ISSUE TITLE
Full specification already exists in 800-63A Sec 5.3.3.1 and 5.3.3.2.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#560]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1,  footnote 9 Line footnote 9
 
**Comment (Include rationale for comment)**: Not required by 800-63A, nor is it warranted as long as video surveillance, security and tamper detection are implemented 
 
**Suggested Change**: Strike as not applicable.  Specification is not needed at the superior document level as full specification already exists in 800-63A  Sec 5.3.3.1 and 5.3.3.2.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion

**Comment by currydm** [comment]
See also #557

**Comment by jglosx3** [comment]
Duplicate to #557 

Reference (Include section/paragraph or pdf line number): 2.7.1, footnote 9 Line footnote 9

Comment (Include rationale for comment): Not required by 800-63A, nor is it warranted as long as video surveillance, security and tamper detection are implemented
