### ISSUE TITLE
Include reference to 800-63A 5.3.3.1

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#561]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1, para 5 Line 813-819
 
**Comment (Include rationale for comment)**: Include reference to 800-63A 5.3.3.1
 
**Suggested Change**: "..per the criteria defined in [SP 800-76] and [SP 800-63A 5.3.3.1 and ]..Sec 5.3.3.1 and 5.3.3.2.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Assigning to Hildy and Andy as Sec 2.7.1 references Identity Proofing/Enrollment.

**Comment by hferraio** [comment]
Suggest do decline as PIV SRIP is a specific profile of SP 800-63 that also has additional PIV specific requirements.

**Comment by hferraio** [comment]
Decline. Criteria are discussed and covered in the relevant sections.
