### ISSUE TITLE
The PIV Card takes the physical form of the [ISO 7816] ID-1 is incorrect. 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#562]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 3.1.1. PIV Front-End Subsystem  Line 1226
 
**Comment (Include rationale for comment)**: The PIV Card
takes the physical form of the [ISO 7816] ID-1 is incorrect. 
 
**Suggested Change**: The PIV Card takes the physical form of the [ISO 7810] ID-1
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Discussion needed; I am included to decline. We need to confirm that iso 7816 is the correct specification.

**Comment by regenscheid** [comment]
Decline.  ISO 7816 incorporates ISO 7810.
