### ISSUE TITLE
Contact & Contactless Requirements

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#563]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: Section 4.4.1 - 4.4.4  Contact Reader Requirements Line 2025 -2039
 
**Comment (Include rationale for comment)**: Contact & Contactless Requirements. These sections miss the case when a reader is not connected to a laptop or desktop that is performing certificate validation. The missing point is the PACS where readers are located throughout a site where the certificate validation system is away from the reader. This requires bi-directional communication to the back-end system such as a certificate validation system near, or inside  the local PACS component.  SP 800-116 R1, S Sect E2 Pg. 46.  Preferably, the bidirectional communication is an industry standard such as OSDP.  
 
**Suggested Change**: Suggest adding language stating:  A reader used for physical access establishes a bi-directional communication path between the card's appropriate certificate and the certificate validation system.                                                                                                                               Contact card readers SHALL conform to [ISO 7816] for the card-to-reader interface, contactless readers shall transmit the ISO 7816 commands over a ISO 14443 link to/from the card.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Assigning to Jonathan - PIV Card

**Comment by hferraio** [comment]
Suggest to decline and out-of-scope.  Card-to-Reader interface is defined for all readers in section 4.4.1 and 4.4.2 as well as in [SP 800-96](https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-96.pdf).  It is the Reader-to-host that is not defined for non-general purpose desktop computing systems. (It is defined for general purpose desktop computing systems). SP 800-96 should address OSDP if it is a candidate interface to build to.

**Comment by regenscheid** [comment]
Declined as described above.
