### ISSUE TITLE
 Change to allow FASC-N, UUID or both in a PIV Credential

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#564]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 5.5.1 Line 2134
 
**Comment (Include rationale for comment)**: Editorial change to allow FASC-N, UUID or both in a PIV Credential
 
**Suggested Change**: 2134 Certificates that contain either the FASC-N or card UUID in the SAN extension, …
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Suggest decline. this doesn't clarify the sentence in question.

**Comment by jricher** [comment]
Decline, existing language is not exclusive.
