### ISSUE TITLE
Remove "PKI-Auth" from PAL 3 area. Add "PKI-Auth +BIO"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#565]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: Table 6-1  Line 2449
 
**Comment (Include rationale for comment)**: PAL 3  includes PKI-Auth as an authentication mechanism to enter a PAL 3 Area. PKI-Auth is a 2FA. To keep consistency with SP 800-116 and 116 R1, (Table 4-3, pg  15), this should be relocated to the PAL2 line.
 
**Suggested Change**: Remove "PKI-Auth" from PAL 3 area. Add "PKI-Auth +BIO" to this area. For clarification, add  Uncontrolled, Controlled, Limited and Exclusion area color codes as used in SP 800-116 R1.  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline . There is no required number of factors associated with  each PALs in FIPS 201-3.  

SP 800-116 takes these factors into consideration. The reason SP 800-116 shows 3-factor of PKI-AUTH in table 4-3 is that it takes authentication in context into consideration.  That is:  prior authentication done before entering into exclusion area (PAL-3) counts as a factor.  Hence another authentication mechanism happened before PKI-AUTH.

**Comment by regenscheid** [comment]
We should discuss further the relationship between the assurance levels in FIPS 201-3 and the guidelines in SP 800-116.

**Comment by regenscheid** [comment]
Resolved by #642.  We no longer establish physical assurance levels in FIPS 201, and instead simply refer to the general assurance provided by the individual PIV authentication mechanisms. SP 800-116 will continue to be the primary reference for PACS levels.
