### ISSUE TITLE
Add: Conveys SOME confidence in the asserted identity's validity.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#566]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: Glossary of Terms, Line 2885 - 2887
 
**Comment (Include rationale for comment)**:  Add : Conveys SOME confidence in  the asserted identity's validity. Consistent with SP 800-116 and SP 800-116 R1 (Sec 5.4.1 Pg 24. A3, pg 34)
 
**Suggested Change**: A PIV authentication mechanism that is implemented by an asymmetric key challenge/response protocol using the card authentication key of the PIV Card and a contact or contactless reader. "Convey SOME confidence in the asserted identity's validity."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Suggest not accepting. We are moving away from the "SOME confidence", etc. terminology.

**Comment by regenscheid** [comment]
Decline per above.

**Comment by jglosx3** [comment]
This should be changed to accept in principle given we have gone back to this concept of Some Medium and High confidence in the updated tables.

**Comment by jglosx3** [comment]
This should be changed to accept in principle given we have gone back to this concept of Some Medium and High confidence in the updated tables.

**Comment by jricher** [comment]
We shouldn't add that to the glossary though, as it's in the tables. And the applicability is dependent on the context of its use. Suggest this remains decline.

**Comment by regenscheid** [comment]
I agree with @jricher.  While the reason has changed, this should remain declined.  The proposed addition is a description of the properties of the authentication mechanism, not part of its definition.  As such, it is better suited for Section 6 than the glossary.
