### ISSUE TITLE
Add: Conveys HIGH confidence in the asserted identity validity.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#567]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2- Industry
 
**Reference (Include section/paragraph or pdf line number)**:  Glossary of Terms Line 2889 - 2891 
 
**Comment (Include rationale for comment)**: Add: Conveys HIGH confidence in the asserted identity validity.  Consistent with SP 800-116 and SP 800-116 R1
 
**Suggested Change**: A PIV authentication mechanism that is implemented by an asymmetric key challenge/response protocol using the PIV authentication key of the PIV Card and a CardHolder PIN using  contact reader or a contactless card reader that supports the virtual contact interface.  Conveys HIGH confidence in the asserted identity validity.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Suggest not accepting. We are moving away from this "confidence" terminology.

**Comment by regenscheid** [comment]
Decline per above.

**Comment by jglosx3** [comment]
This should be changed to accept in principle given we have gone back to this concept of Some Medium and High confidence in the updated tables.

**Comment by jglosx3** [comment]
This should be changed to accept in principle given we have gone back to this concept of Some Medium and High confidence in the updated tables

**Comment by jricher** [comment]
We shouldn't add that to the glossary though, as it's in the tables.

**Comment by jglosx3** [comment]
I agree with not added to glossary but the only rationale we gave for declining was that we were moving away from “confidence terminology”. Do we need an updated rationale.

**Comment by regenscheid** [comment]
Decline. The proposed addition is a description of the properties of the authentication mechanism, not part of its definition. As such, it is better suited for Section 6 than the glossary.
