### ISSUE TITLE
Suggest adding the "PKI-Auth + BIO" as a 3FA authentication mechanism.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#568]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 _ Industry
 
**Reference (Include section/paragraph or pdf line number)**: Glossary of Terms
 
**Comment (Include rationale for comment)**:  Suggest adding the "PKI-Auth + BIO" as a 3FA authentication mechanism. Convey VERY HIGH confidence in the asserted identity. This is a well- established 3FA authentication mechanism that is consistent with SP 800-116 and -116 R1. In addition, there are several readers on the GSA FIPS 201 EP Approved Products List. This continues to be deployed while a multitude of reader manufacturers offer competition. 
 
**Suggested Change**: In the Logical Access tables, there is no reference to this 3FA mechanism that is so important in the deployment and implementation of Physical Access Control Policies for access to the most high consequence areas. In SP 800-116 referred to as Exclusion Areas.    Suggest adding the following case. A PIV authentication mechanism that is implemented by an asymmetric key challenge/response protocol using the PIV authentication key of the PIV Card and a CardHolder PIN using contact reader and Card Holder Biometric using  contact interface.  Convey VERY HIGH confidence in the asserted identity validity.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to decline.  FIPS 201 does not list combinations of its authentication mechanisms.  Combinations are defined as needed in associated Special Publications (e.g., SP 800-116).  Note also, terms such as High, Very High have been deprecated in favor of PALs.

**Comment by currydm** [comment]
Agree to decline, this will be specified in SP 800-116.

**Comment by jglosx3** [comment]
Given the change in Tables for PACS in section 6.3 this issue needs to be reopened

**Comment by jricher** [comment]
I don't think this should be changed as the root request is about 3FA, and 800-116 will define any combinations and levels, not FIPS201.

**Comment by regenscheid** [comment]
Decline.  The proposed addition is not in scope for FIPS 201- it is instead addressed by SP 800-116.
