### ISSUE TITLE
Change titles of Section 6.3.1 & 6.3.2

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#569]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 _ Industry
 
**Reference (Include section/paragraph or pdf line number)**: 3, 3.1.3, 3.3, 6.3.1, 6.3.2: Line 1195, 1298, 1338
 
**Comment (Include rationale for comment)**: Derived PIV Credentials for Physical Access: OMB 19-17 states "[Federal agencies are to] develop guidance to facilitate use ... of derived credentials for logical AND PHYSICAL access".  The referenced sections and page no.'s imply that a PIV card and a derived credential can be used for physical access -- for example, Section 3.1.3, Line 1298, states "The PIV relying subsystem becomes relevant when the PIV Card or derived PIV credential is used to authenticate a cardholder who is seeking access to a physical or logical resource."
 
**Suggested Change**: 1. The referenced sections imply that derived PIV credentials may be used for physical access as well as logical access, which is a good thing. 
If that is the intent of the draft (i.e., leaving the option open),  the references should remain as is/are, and should not be modified by any comments that NIST might receive to the contrary. Some agencies are showing interest in derived credentials for physical access, and it follows that some agencies will eventually want to use mobile devices for physical access in some form within the next 2-3 years.
2. Change title of Section 6.3.1 to ""PIV Card Physical Access"". Change title of Section 6.3.2 to ""PIV Card Logical Access"". The PAL auth mechanisms are PIV-card specific, and the implication is that FIPS 201-3 is only addressing PIV physical access at this time. It would be nice to have DPC considerations for physical access in this draft, but it may be convenient be vague on it within this version, with the option that  derived credentials for physical access can be addressed in other standards updates, e.g., SP 800-157.
3. This all aligns with an answer received during the FIPS 201-3 Virtual Workshop when the question was proposed -- Answer: ""Based on business requirement meeting with federal stakeholder, we did not hear uptake to use DPC for physical access. Hence, the PIV card is still status quo for PACS. We welcome further comment.""  Perhaps this subject can be readdressed by NIST with agencies that were involved in discussions leading up to the draft.  
4. In addition, we refer you to the following AFCEA article: (https://www.afcea.org/content/mobile-devices-offer-promise-identity-solutions) which provides several good points for using derived credentials for physical access in the federal space. 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Recommend to narrowly accept. Sections 6.3.1 and 6.3.2 begin, "The PIV Card can be used..." which makes it fairly clear that the PIV Card is being specifically referred to here, so changing the section title doesn't add much. But there does seem to be some uncertainty from the earlier sections whether DPC can be used for physical access, which should be clarified.

**Comment by regenscheid** [comment]
Accept in principle. While we don't intend to change the titles of the sections, we can clarify that these subsections are only intended to map the PIV authentication mechanisms to the assurance levels.  This might be accomplished with new text in Section 6.3.
