### ISSUE TITLE
"Relying Party", "Relying System" and "Relying Subsystem": Suggest deciding on a single term. 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#570]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: General
 
**Comment (Include rationale for comment)**: "Relying Party", "Relying System" and "Relying Subsystem": These terms are used for what appears to be the same thing, and/or are not specifically defined or distinguished from each other. 
 
**Suggested Change**: Suggest deciding on a single term. Note that SP 800-63-3/63A/63B/63C use "relying party".
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion

**Comment by jricher** [comment]
Duplicate of #331
