### ISSUE TITLE
Did something else replace Temporary Residence Card?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#574]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7 

**Comment (Include rationale for comment)**: Temporary Resident Card:  Temporary Resident Card has been removed from the list of Forms of Identification.  
 
**Suggested Change**: Was this intentional?  Did something else replace Temporary Residence Card?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Assigning to Hildy and Andy as Sec 2.7 references Identity Proofing.

**Comment by hferraio** [comment]
suggest to close issue as it is a duplicate of [334](https://github.com/usnistgov/FIPS201/issues/334)
