### ISSUE TITLE
OCSP [RFC2560] status responders shall be implemented as a SUPPLEMENTARY certificate status mechanism.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#575]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 5.5.2 Line 2140
 
**Comment (Include rationale for comment)**: Maintain the FIPS 201-2 original language here.  Rational: Can be interpreted by PIV-I and CIV issuers, outside the federal government, the OCSP responder capability is supported on a "stakeholders need" basis.
 
**Suggested Change**: OCSP [RFC2560] status responders shall be implemented as a supplementary certificate status mechanism.  (emphasis added)
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion

**Comment by regenscheid** [comment]
Decline.  OCSP responders were required under FIPS 201-2, and continue to be required under FIPS 201-3.  Removing "supplementary" from FIPS 201-3 was intended to clarify that they are required.
