### ISSUE TITLE
Explicitly categorize non- REAL ID state IDs as acceptable?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#576]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7 Line 739-740
 
**Comment (Include rationale for comment)**: Explicitly categorize non- REAL ID  state IDs as acceptable for 
Fair evidence or that it is not usable.
 
**Suggested Change**: ID card issued by a federal, state, or local government agency or entity, provided that it contains a photograph **to include non-REAL ID state issued driver licenses, mobile driver license, or state or jurisdictional ID card**
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
suggest closing as it is represented in issue [376](https://github.com/usnistgov/FIPS201/issues/376)
