### ISSUE TITLE
Add Logical integrity with action to be further defined in SP 800-63

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#579]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.7.1 Line 792
 
**Comment (Include rationale for comment)**: Add Logical integrity with 
action to be further defined in SP 800-63
 
**Suggested Change**: ensuring that the physical and **logical** integrity of the station
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion

**Comment by hferraio** [comment]
suggest to decline as this section is about physical control of station/environment.

**Comment by regenscheid** [comment]
We will investigate possible ways to cover logical security, such as computer security controls.

**Comment by regenscheid** [comment]
Added new language covering malicious code threats to supervised remote identity proofing stations.
