### ISSUE TITLE
Missing words, “or the virtual contact interface”.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#581]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.6 para. 1 Line 1900
 
**Comment (Include rationale for comment)**: The words “or the virtual contact interface” are missing at the end of the first sentence. 
According to the definition of the virtual contact interface earlier in this standard, “Any operation that MAY be performed over the contact interface of the PIV Card MAY also be performed over the virtual contact interface.” See FIPS 201-3 draft line 1814 and previous FIPS 201-2 section 4.2.2 paragraph 4.  Besides both FIPS 201-2 and FIPS 201-3 draft include in section 4.2.2 Cryptographic Specifications , a sentence stating: “With the exception of the card authentication key and keys used to establish secure messaging, cryptographic private key operations SHALL be performed only through the contact interface or the virtual contact interface.“ (see FIPS 201-3 draft line 1812)
Allowing the PIV card administrator to authenticate to the PIV card through a VCI enables to service the card through the NFC interface of a smart phone, for instance to reset a card when the PIV card holder is working remotely and can no longer boot his PC because his PIN is blocked.
Since the card application administrative key is optional, why prevent its use for Post Issuance Update over the contactless interface? That would give cards that do not use the application administrative key to service the card, like some cards that use Global Platform Secure Channel (that works in both contact and contactless), an unfair competitive advantage.
 
**Suggested Change**: Change the last sentence of this paragraph to read: If present, the cryptographic operations that use the PIV Card application administration key SHALL only be accessible using the contact interface, or the virtual contact interface, of the PIV Card."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
Need discussion: is the VCI allowed for this action, or not? It seems like it already is and specifying it is redundant here.

**Comment by hferraio** [comment]
More context: This is a repeat request from FIPS 201-2 comments and SP 800-73-4 comments (see [OT-6)](https://csrc.nist.gov/CSRC/media/Publications/sp/800-73/4/archive/2015-05-29/documents/sp800_73-4_2014_draft_comments_and_dispositions.pdf). Our response still holds that:

_The purpose of the virtual contact interface is to permit operations performed by the cardholder to be
performed over the contactless interface of the card. Operations involving the PIV Card Application Administration key (the '9B' key) are performed by the PIV Card Application Administrator, not the cardholder._ 

This is still true today. Card management functionality have their own secure messaging mechanisms which should not be mixed with user functionality.

**Comment by jricher** [comment]
Accept in principle to evaluate possibilities.

**Comment by hferraio** [comment]
Recent conversations with commentor:
- there is a potential that admin key can be brute forced unbeknownst to cardholder
- since VCI does not mutual authenticate as required in section 2.9.2 (mutual authenticated secure channel for post issuance update). It only authenticates the card-to-host and not host-to-card
- admin key, therefore could be brute forced after VCI is established  - unless there is a throttle mechanism
- Opacity Full forward secrecy would "likely' mutual authenticate, but that is not specified in the PIV specs

**Comment by jglosx3** [comment]
Final resolution was to clarify text to indicate that Application Administration Key can only be used on contact interface
