### ISSUE TITLE
Welcome addition to the FIPS 201 standard  (on-card fingerprint comparison).

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#582]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.4 Line 594-595
 
**Comment (Include rationale for comment)**: This is a welcomed addition to the FIPS 201 standard, thank you! Some issuers may be tempted to use the same set of fingerprints for off-card authentication and on-card comparison simply for user convenience, without realizing the security issue such personalization could introduce. Fingerprints from OCC are freely readable from an activated card, and converting the ANSI 378 template in the card holder fingerprint data object to an ISO 19794-2 template to be used by OCC is a trivial operation. So having for on-card comparison the same set of fingerprints as for off-card authentication, results in being able to read from the card data needed to perform a card activation with OCC, and use it  another time in place of PIN verification to activate the card prior to PIV Authentication or digital signature.
 
**Suggested Change**: Keep this important addition in the final version.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Suggest "noted".
