### ISSUE TITLE
Add "through an on-card one-to-one comparison" after "PIV Card".

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#584]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 2.9.3 para. 4 Line 1028
 
**Comment (Include rationale for comment)**: Same comment as above. This paragraph is about resetting a PIV card. If the PIV card needs to be reset, that means its PIN has been blocked due to too many consecutive failed verification attempts and therefore none of the biometric data on the card can be read.
 
**Suggested Change**: Add "through an on-card one-to-one comparison" after "PIV Card" in the sentence "… elicit a positive biometric verification decision when compared to biometric data records stored either on the PIV Card or in the PIV enrollment record." 
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Commenter asking to expand description to explicitly state OCC is used to verify biometric on the PIV card.
(is clarification necessary?)

**Comment by regenscheid** [comment]
Accept- we will add OCC as an explicit option.

**Comment by regenscheid** [comment]
Note that #583 commented on the same issue that appeared on a different line (1001).
