### ISSUE TITLE
Convert one of the depreciated bar code zones to store a PIV Pairing Code.

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#586]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.1.4.3, Zone 8B Line 1674
 
**Comment (Include rationale for comment)**: Depreciation of Linear 3 of 9 Bar Code. There may be a new use case for some kind of bar code in this zone on the back of the card.  A bar code could be used to store the PIV Pairing Code. That would facilitate and expedite VCI establishment when readers are equipped with a low cost bar code scanner. The Pairing code would be read automatically as the card holder approaches the PIV card to the contactless PACS reader. The Pairing Code could also be encoded as a QR code or Micro QR code.
 
**Suggested Change**: Consider converting one of the depreciated bar code zones to store a micro QR code or PDF 417 with the PIV Pairing Code.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
For consideration: [ SP 800-73-4](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-73-4.pdf) states another location for printing the pairing code (if department/agencies choose to print it). It states:

_The pairing code ....... may be printed on the back of the card in an agency-specific text area (Zones 9B or 10B)._

**Comment by regenscheid** [comment]
Decline per above.
