### ISSUE TITLE
Remove "or generated on the card"

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#588]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.3 para. 2 Line 1869
 
**Comment (Include rationale for comment)**: This paragraph states that ""If used, the symmetric card authentication key MAY be imported onto the card by the
issuer or be generated on the card."" It does not seem to make sense to generate on the card a symmetric key used for authentication, unless the key can be exported. Does that mean that cryptographic keys can be exported from the PIV card? 
 
**Suggested Change**: Remove "or generated on the card"
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
OBE because we are deprecating the mechanism.

**Comment by regenscheid** [comment]
Decline.  This language was not changed from FIPS 201-3, and SYM-CAK is being deprecated as part of the FIPS 201-3 revision.
