### ISSUE TITLE
Import of asymmetric card keys: Will the [SP 800-73] be enhanced with this feature?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#590]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 4.2.2.2 Line 1850, 1890
 
**Comment (Include rationale for comment)**: Import of asymmetric card keys.
Will the [SP 800-73] be enhanced with this feature?
 
**Suggested Change**: MAY be generated on the PIV Card by an administrator or imported to a new PIV Card by the issuer."
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
Suggest to note.  Import of the asymmetric card authentication key has been possible since FIPS 201-2 and hence in SP 800-73-4. 

Note: It is out of scope to specify protocol steps for import as it is a card management function.
