### ISSUE TITLE
What is the origin of the expiration date of the PIV card?

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#591]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 5.2.1 Line 2100
 
**Comment (Include rationale for comment)**: The expiration date of the PIV authentication and card authentication certificates SHALL NOT be after the expiration date of the PIV Card.

What is the origin of the expiration date of the PIV card?
 
**Suggested Change**: Need clarification of what Expiration Date is used. Expiration date taken from the CHUID?
Or the expiration date from list on a service?
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Accept -Recommend added clarification text.  PIV card expiration is date based on CHUID.  

" For example, the BIO, BIO-A, and SYM-CAK authentication mechanisms use the CHUID data element as a source for the card’s expiration date. "

**Comment by hferraio** [comment]
Suggest to decline or clarify. The expiration date is the date printed on the card (zone 14F). The CHUID contains the 'digital copy'/representation of that date.  See line 1757 and further specification in SP 800-73-4.

**Comment by regenscheid** [comment]
Expand Section 4.2.1 to state that the CHUID data object is the electronic source for the card's expiration date.
