### ISSUE TITLE
Make the CardHolder [PERSON] UUID Mandatory. 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#592]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: [blank]

**Comment (Include rationale for comment)**: Cardholder UUID was Optional in FIPS 201-2. This is a very valuable data object and should be MANDATORY in FIPS 201-3. Also suggest changing the term to Person UUID for an intuitive term.
 
**Suggested Change**: Make the CardHolder UUID Mandatory. Change the name to Person UUID.
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by currydm** [comment]
Propose team discussion

**Comment by regenscheid** [comment]
Decline.  This was discussed in the FIPS 201-2 revision cycle and the recent FIPS 201-3 business requirements meeting, and we determined that a government-wide stable identifier was not necessary and may not be appropriate in some environments.  We will, however, address stable subject identifiers for relying parties as part of the upcoming federation SP.
