### ISSUE TITLE
Does the PIV Card support other card activation  mechanisms than specified by [SP800-73]? 

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#593]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: 6.2.3.1 Line 2264
 
**Comment (Include rationale for comment)**: Other card activation mechanisms, as specified in [SP 800-73], MAY be used to activate the card.

Does the PIV Card support other mechanisms than specified by [SP800-73]? 
In what states are these mechanisms allowed?
 
**Suggested Change**: Add specific language to show example or, include reference to specific section in SP 800-73. During initialization or personalization, other mechanism as specified …
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jglosx3** [comment]
Discussion required: Should we specify specific example in FIP201-3 or just leave reference to SP800-73 in case additional card activation methods are added?  Current version of 800-73 allows on-card biometric comparison as alternate activation  mechanism.

**Comment by regenscheid** [comment]
Follow-up with @hferraio and review SP 800-73

**Comment by hferraio** [comment]
OCC  (of finger images) and PIN are the only mechanisms specified in SP 800-73. To add others (including other modality of OCC), it would have to be specified in SP 800-73 and SP 800-76 - so that interoperability can be maintained. 

Suggest leave the text as is.

**Comment by regenscheid** [comment]
Decline per above.
