### ISSUE TITLE
Need for Consistency in Performing Incremental or Partial Enrollments for PIV Credential

### ISSUE THREAD

**Issue by wszwerc** [usnistgov/FIPS201#595]
### All Fields Are Required
**Organization Name (N/A, if individual)**: Secure Technology Alliance

**Organization Type (see below for codes)**: 2 - Industry
 
**Reference (Include section/paragraph or pdf line number)**: [blank]
 
**Comment (Include rationale for comment)**: Need for Consistency in Performing Incremental or Partial Enrollments for PIV Credential Problem: Under emergency situations, FIPS-201 issuers and security officials may be required to perform incremental or partial enrollments.  This may be due to the inability for issuers to provide in-person proofing and data capture support on-local because of social distancing requirement or an applicant's inability to visit a credentialing facility.   This creates inconsistencies in approaches and best practices
 
**Suggested Change**: 
**Recommendation**: It is recommended that FIPS-201 provide a common baseline approach,  consistent across Departments and Agencies, for applicants to receive an alternate token or Derived Alternate Credential (DAC) to employees in lieu of a Personal Identity Verification (PIV) credential that will allow personnel to gain system access to the Department and Agency networks without visiting a Credentialing Facility. See Reference DHS OCSO DAC Policies & Procedures.
**Key Points:**
-- It is the decision of the employee’s supervisor or the contractor’s program manager to determine if an applicant requires a DAC in lieu of a PIV card, then the following process must be adhered to. If a DAC is needed by a new employee or contractor -- supervisors, contract program managers, or Contracting Officer’s Representatives must inform the Department or Agency Credentialing Facility. Applicants must provide a valid personal email and home address when where they can receive and sign for their pre-activated DAC and government-furnished equipment (GFE) as applicable.
--  Acceptable forms of partial enrollment would include the ability to capture and electronically validate Form I-9 Acceptable Documents, List A or “List A” documents against known authoritative identity libraries.  Further, once the applicant's “List A” documents have been electronically adjudicated, the applicant can proceed with remote proofing as outlined in SP-800-63. This includes a photographic, facial, self-capture with liveness detection incorporated into the capture. Using facial recognition technology, this photo must be digitally compared against the previously captured applicant “List A” document photos for final adjudication for a DAC.
-- As a final step in the incremental or partial enrollment process, applicants must also electronically sign and submit the Department or Agency Authorized Authoritative Credential Holder Responsibility Agreement.
-- Upon successful adjudication of the self-photo to the “List A” document photos, the applicant can then be issued a DAC. Personnel who obtain a DAC will have to get a PIV card at a later time following the policies and procedures contained in FIPS 201.                                                                                                                                                      **References**                                                   https://www.dhs.gov/sites/default/files/publications/dhs_authorized_authoritative_credential_holder_responsibility_agreement.pdf           
https://www.dhs.gov/sites/default/files/publications/covid_19_new_empoyee_onboarding_guidance_1.pdf
https://www.dhs.gov/sites/default/files/publications/covid_19_dac_faq_1.pdf
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jimfenton** [comment]
Needs discussion to decide whether alternative credentials are in scope or not.

**Comment by jimfenton** [comment]
Alternative credentials are out of scope for FIPS 201. Per [OPM policy memo](https://www.opm.gov/policy-data-oversight/covid-19/opm-memorandum-on-boarding-processes-for-new-employees-during-the-covid-19-emergency/), agencies are able to make risk-based decisions to issue alternative credentials in certain circumstances.
