### ISSUE TITLE
Reusing Biometric Data for PIV

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#596]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 941
 
**Comment (Include rationale for comment)**: As indicated in line 941, previously collected biometric data can be reused with a new PIV card if the expiration date of the new PIV card ins no less than 12 years after the date that the biometric data was obtained. That duration seems over-long. The Canadian Government, for example, has a 10-year validity period for their visa-related biometrics.
 
**Suggested Change**: N/A
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by gfiumara** [comment]
See also #369

**Comment by hferraio** [comment]
See also #400.

**Comment by regenscheid** [comment]
Decline- studies show that biometrics remain matchable for >12 years, which aligns with PIV card lifecycles.
