### ISSUE TITLE
20 retired key management keys

### ISSUE THREAD

**Issue by currydm** [usnistgov/FIPS201#598]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NSA Center for Cybersecurity Standards

**Organization Type (see below for codes)**: 1 - Federal
 
**Reference (Include section/paragraph or pdf line number)**: Line 1798
 
**Comment (Include rationale for comment)**: In line 1798, it indicates that a card may store up to 20 retired key
management keys. Again, this number seems large. We would welcome answers from NIST as to why they are pushing for 20 here. 

**Suggested Change**: N/A
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by hferraio** [comment]
FYI: The retired key management keys was one of the major update from SP 800-73-2 to SP 800-73-3. The number of KMK included in the PIV card is based on feedback received during commenting period.

**Comment by regenscheid** [comment]
This is not required.  FIPS 201 states that "optionally, up to 20 retired key management keys may also be stored."
