### ISSUE TITLE
Find source for 18h revocation time

### ISSUE THREAD

**Issue by jricher** [usnistgov/FIPS201#610]
Add a footnote reference for the 18h revocation and collection window in 2.9.1.

**Comment by hferraio** [comment]
no reference found. There is a reference in COMMON, but pointing to COMMON only covers PKI cred. revocation and not everything else that we bundle under "termination procedure" such as removing FASC-N from any databases.

Revocation of certificate is covered, btw, in section 5.3 and it does point to COMMON as DHS requested. So, we should be good there.
