### ISSUE TITLE
typeface

### ISSUE THREAD

**Issue by hferraio** [usnistgov/FIPS201#658]
### All Fields Are Required
**Organization Name (N/A, if individual)**: N/A

**Organization Type (see below for codes)**: 5
 
**Reference (Include section/paragraph or pdf line number)**: Figure 4-1
 
**Comment (Include rationale for comment)**: 
Hi 

, can I suggest a change for the next FIPS 201 revision? The standard currently requires the typeface on the card to be 'Arial' despite the fact the typeface is vendor locked to Microsoft products. 
 
**Suggested Change**: 

Public Sans would be a much better choice in my opinion. 

 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by nist** [comment]
@nist is not [NIST](https://www.nist.gov/), it's me. The correct user is @usnistgov.
