### ISSUE TITLE
updated front end of FIPS201-3 section 9 Effective date

### ISSUE THREAD

**Issue by jglosx3** [usnistgov/FIPS201#696]
### All Fields Are Required
**Organization Name (N/A, if individual)**: NIST

**Organization Type (see below for codes)**: 1
 
**Reference (Include section/paragraph or pdf line number)**:  "The effective dates of these features depend upon the release of revised NIST Special Publications or the release of new NIST Special Publications that are targeted to be released within 18 months of publication of this Standard.
 
**Comment (Include rationale for comment)**: Based on discussion with Hildy and Andy change below is recommend to remove timeline for updated Special pubs.
 
**Suggested Change**: The effective date of new and updated features depend upon the release of revised NIST Special Publications or the release of new NIST Special Publications that will be developed following the publication of this Standard.  
 
---
 
Organization Type: 1 = Federal, 2 = Industry, 3 = Academia, 4 = Self, 5 = Other

**Comment by jricher** [comment]
I believe this has already been included in the text, which no longer mentions "18 months" in that section.

**Comment by jricher** [comment]
Fixed by 566b918edea4f14d7877c4ca3fef7c7afec813be

**Comment by jglosx3** [comment]
Concur that issue was address by change in PR#695
